{
  "hash": "334d10d0fdb96a73171294429d7dc9bf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 10: MLR: Using the F-test\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"2026-02-18\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 10: MLR 2\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n# Learning Objectives\n\n1.  Understand the use of the general F-test and interpret what it measures.\n2.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n3.  Understand the context of the **single covariate/coefficient F-test**, conduct the needed hypothesis test, and interpret the results.\n4.  Understand the context of the **group of covariates/coefficients F-test**, conduct the needed hypothesis test, and interpret the results.\n\n\n::: {.cell}\n<style type=\"text/css\">\n.reveal code {\n  max-height: 100% !important;\n}\n</style>\n:::\n\n\n## Let's map that to our regression analysis process\n\n::: box\n![](../img_slides/arrow2.png){.absolute top=\"13.5%\" right=\"62.1%\" width=\"155\"} ![](../img_slides/arrow2.png){.absolute top=\"13.5%\" right=\"28.4%\" width=\"155\"}![](../img_slides/arrow_back4.png){.absolute top=\"7.5%\" right=\"30.5%\" width=\"820\"} ![](../img_slides/arrow_down.png){.absolute top=\"60.5%\" right=\"48%\" width=\"85\"}\n\n::: columns\n::: {.column width=\"30%\"}\n::: RAP1\n::: RAP1-title\nModel Selection\n:::\n\n::: RAP1-cont\n-   Building a model\n\n-   Selecting variables\n\n-   Prediction vs interpretation\n\n-   Comparing potential models\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP2\n::: RAP2-title\nModel Fitting\n:::\n\n::: RAP2-cont\n-   Find best fit line\n\n-   Using OLS in this class\n\n-   Parameter estimation\n\n-   Categorical covariates\n\n-   Interactions\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP3\n::: RAP3-title\nModel Evaluation\n:::\n\n::: RAP3-cont\n-   Evaluation of model fit\n-   Testing model assumptions\n-   Residuals\n-   Transformations\n-   Influential points\n-   Multicollinearity\n:::\n:::\n:::\n:::\n:::\n\n::: RAP4\n::: RAP4-title\nModel Use (Inference)\n:::\n\n::: RAP4-cont\n::: columns\n::: {.column width=\"50%\"}\n-   Inference for coefficients\n-   Hypothesis testing for coefficients\n:::\n\n::: {.column width=\"50%\"}\n-   Inference for expected $Y$ given $X$\n:::\n:::\n:::\n:::\n\n## How do we estimate the model parameters?\n\n-   We need to estimate the population model coefficients $\\widehat{\\beta}_0, \\widehat{\\beta}_1, \\widehat{\\beta}_2, \\ldots, \\widehat{\\beta}_k$\n-   This can be done using the **ordinary least-squares method**\n    -   Find the $\\widehat{\\beta}$ values that **minimize** the sum of squares due to error ($SSE$)\n\n$$ \\begin{aligned}\nSSE & = \\displaystyle\\sum^n_{i=1} \\widehat\\epsilon_i^2 \\\\\nSSE & = \\displaystyle\\sum^n_{i=1} (Y_i - \\widehat{Y}_i)^2 \\\\\nSSE & = \\displaystyle\\sum^n_{i=1} (Y_i - (\\widehat{\\beta}_0 +\\widehat{\\beta}_1 X_{i1}+ \\ldots+\\widehat{\\beta}_1 X_{ik}))^2 \\\\\nSSE & = \\displaystyle\\sum^n_{i=1} (Y_i - \\widehat{\\beta}_0 -\\widehat{\\beta}_1 X_{i1}- \\ldots-\\widehat{\\beta}_1 X_{ik})^2\n\\end{aligned}$$\n\n## LINE model assumptions in MLR\n\n::: columns\n::: column\n::: definition\n::: def-title\n**\\[L\\] Linearity** of relationship between variables\n:::\n\n::: def-cont\nThe mean value of $Y$ given any combination of $X_1, X_2, \\ldots, X_k$ values, is a linear function of $\\beta_0, \\beta_1, \\beta_2, \\ldots, \\beta_k$:\n\n$$\\mu_{Y|X_1, \\ldots, X_k} = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\ldots + \\beta_k X_k$$\n:::\n:::\n:::\n\n::: column\n::: proof1\n::: proof-title\n**\\[I\\] Independence** of the $Y$ values\n:::\n\n::: proof-cont\nObservations ($X_1, X_2, \\ldots, X_k, Y$) are independent from one another\n:::\n:::\n:::\n\n::: column\n::: theorem\n::: thm-title\n**\\[N\\] Normality** of the $Y$'s given $X$ (residuals)\n:::\n\n::: thm-cont\n$Y$ has a normal distribution for any any combination of $X_1, X_2, \\ldots, X_k$ values\n\n-   Thus, the residuals are normally distributed\n:::\n:::\n:::\n\n::: column\n::: fact\n::: fact-title\n**\\[E\\] Equality** of variance of the residuals (homoscedasticity)\n:::\n\n::: fact-cont\nThe variance of $Y$ is the same for any any combination of $X_1, X_2, \\ldots, X_k$ values\n\n$$\\sigma^2_{Y|X_1, X_2, \\ldots, X_k} = Var(Y|X_1, X_2, \\ldots, X_k) = \\sigma^2$$\n:::\n:::\n:::\n:::\n\n## Summary of the LINE assumptions\n\n-   Equivalently, the **residuals** are independently and identically distributed (iid):\n    -   normal\n    -   with mean 0 and\n    -   constant variance $\\sigma^2$\n\n \n    \n- Residuals are still $\\widehat{\\epsilon}_i=Y_i - \\widehat{Y}_i$ for each observation\n  - It's just that $\\widehat{Y}_i$ is now calculated with many covariates ($X_1, X_2, \\ldots, X_k$)\n\n\n# Learning Objectives\n\n::: lob\n1.  Understand the use of the general F-test and interpret what it measures.\n:::\n\n2.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n3.  Understand the context of the **single covariate/coefficient F-test**, conduct the needed hypothesis test, and interpret the results.\n4.  Understand the context of the **group of covariates/coefficients F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## *Remember from Lesson 6:* F-test vs. t-test for the population slope\n\nThe square of a $t$-distribution with $df = \\nu$ is an $F$-distribution with $df = 1, \\nu$\n\n$$T_{\\nu}^2 \\sim F_{1,\\nu}$$\n\n-   We can use **either F-test** or **t-test** to run the following hypothesis test:\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n-   Note that the F-test does not support one-sided alternative tests, but the t-test does!\n\n## *Remember from Lesson 6:* Planting a seed about the F-test\n\nWe can think about the hypothesis test for the slope...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=0$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_1\\neq0$\n:::\n:::\n:::\n:::\n\nin a slightly different way...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull model ($\\beta_1=0$)\n:::\n\n::: proof-cont\n-   $Y = \\beta_0 + \\epsilon$\n-   Smaller (reduced) model\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative model ($\\beta_1\\neq0$)\n:::\n\n::: def-cont\n-   $Y = \\beta_0 + \\beta_1 X + \\epsilon$\n-   Larger (full) model\n:::\n:::\n:::\n:::\n\n-   In multiple linear regression, we can start using this framework to test multiple coefficient parameters at once\n\n    -   Decide whether or not to reject the smaller reduced model in favor of the larger full model\n\n    -   Cannot do this with the t-test!\n\n## *Remember from Lesson 6:* We can extend this!!\n\nWe can create a hypothesis test for more than one coefficient at a time...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=\\beta_2=0$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_1\\neq0$ and/or $\\beta_2\\neq0$\n:::\n:::\n:::\n:::\n\nin a slightly different way...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull model\n:::\n\n::: proof-cont\n-   $Y = \\beta_0 + \\epsilon$\n-   Smaller (reduced) model\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative\\* model\n:::\n\n::: def-cont\n-   $Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\epsilon$\n-   Larger (full) model\n:::\n:::\n:::\n:::\n\n\\*This is **not quite** the alternative, but if we reject the null, then this is the model we move forward with\n\n## Poll Everywhere Question 1\n\n## Variation: Explained vs. Unexplained\n\n$$\\begin{aligned}\n\\sum_{i=1}^n (Y_i - \\overline{Y})^2 &= \\sum_{i=1}^n (\\widehat{Y}_i- \\overline{Y})^2 + \\sum_{i=1}^n (Y_i - \\widehat{Y}_i)^2 \\\\\nSSY &= SSR + SSE\n\\end{aligned}$$\n\n-   $Y_i - \\overline{Y}$ = the deviation of $Y_i$ around the mean $\\overline{Y}$\n    -   the **total** amount deviation\n-   $\\widehat{Y}_i- \\overline{Y}$ = the deviation of the fitted value $\\widehat{Y}_i$ around the mean $\\overline{Y}$\n    -   the amount deviation **explained** by the regression at $X_{i1},\\ldots,X_{ik}$\n-   $Y_i - \\widehat{Y}_i$ = the deviation of the observation $Y$ around the fitted regression line\n    -   the amount deviation **unexplained** by the regression at $X_{i1},\\ldots,X_{ik}$\n\n## Building the ANOVA table {visibility=\"hidden\"}\n\nANOVA table ($k$ = \\# of predictors, $n$ = \\# of observations)\n\n::: columns\n::: {.column width=\"8%\"}\n:::\n\n::: {.column width=\"84%\"}\n| Variation Source | df      | SS    | MS                        | test statistic        | p-value                 |\n|------------|------------|------------|------------|------------|------------|\n| Regression       | $k$     | $SSR$ | $MSR = \\frac{SSR}{k}$     | $F = \\frac{MSR}{MSE}$ | $P(F_{(k, n-k-1)}>F)$ |\n| Error            | $n-k-1$ | $SSE$ | $MSE = \\frac{SSE}{n-k-1}$ |                       |                         |\n| Total            | $n-1$   | $SSY$ |                           |                       |                         |\n:::\n:::\n\n \n\n\n::: {.cell}\n\n:::\n\n\n## SLR: Another way to think of SSY, SSR, and SSE\n\n-   Let's create a data frame of each component within the SS's\n\n    -   Deviation in SSY: $Y_i - \\overline{Y}$\n    -   Deviation in SSR: $\\widehat{Y}_i- \\overline{Y}$\n    -   Deviation in SSE: $Y_i - \\widehat{Y}_i$\n\n-   Using our simple linear regression model as an example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslr1 <- gapm %>% \n  lm(formula = life_exp ~ cell_phones_100)\naug_slr1 = augment(slr1)\nSS_dev_slr = gapm %>% select(life_exp) %>%\n  mutate(SSY_dev = life_exp - mean(life_exp),\n         y_hat = aug_slr1$.fitted, \n         SSR_dev = y_hat - mean(life_exp), \n         SSE_dev = aug_slr1$.resid)\n```\n:::\n\n\n## *SLR*: Plot the components of each sum of squares\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to make the below plots\"}\nSSY_plot = ggplot(SS_dev_slr, aes(SSY_dev)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) + xlab(expression(Y[i] - bar(Y)))\nSSR_plot = ggplot(SS_dev_slr, aes(SSR_dev)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) +xlab(expression(hat(Y)[i] - bar(Y)))\nSSE_plot = ggplot(SS_dev_slr, aes(SSE_dev)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) + xlab(expression(Y[i] - hat(Y)[i]))\ngrid.arrange(SSY_plot, SSR_plot, SSE_plot, nrow = 3)\n```\n:::\n\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"right\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='right' width=576}\n:::\n:::\n\n:::\n\n::: column\n$$SSY = \\sum_{i=1}^n (Y_i - \\overline{Y})^2 = 45.75$$ \n\n \n\n$$SSR = \\sum_{i=1}^n (\\widehat{Y}_i- \\overline{Y})^2 = 10.52$$\n\n \n\n$$SSE =\\sum_{i=1}^n (Y_i - \\widehat{Y}_i)^2 = 35.23$$\n:::\n:::\n\n## *MLR:* Another way to think of SSY, SSR, and SSE\n\n-   Let's create a data frame of each component within the SS's\n\n    -   Deviation in SSY: $Y_i - \\overline{Y}$\n    -   Deviation in SSR: $\\widehat{Y}_i- \\overline{Y}$\n    -   Deviation in SSE: $Y_i - \\widehat{Y}_i$\n\n-   Using our simple linear regression model as an example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr1 <- gapm %>% \n  lm(formula = life_exp ~ cell_phones_100 + vax_rate)\naug_mlr1 = augment(mlr1)\nSS_df = gapm %>% select(life_exp) %>%\n  mutate(SSY_dev = life_exp - mean(life_exp),\n         y_hat = aug_mlr1$.fitted, \n         SSR_dev = y_hat - mean(life_exp), \n         SSE_dev = aug_mlr1$.resid)\n```\n:::\n\n\n## *MLR:* Plot the components of each sum of squares\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to make the below plots\"}\nSSY_plot = ggplot(SS_df, aes(SSY_dev)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) + xlab(expression(Y[i] - bar(Y)))\nSSR_plot = ggplot(SS_df, aes(SSR_dev)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) +xlab(expression(hat(Y)[i] - bar(Y)))\nSSE_plot = ggplot(SS_df, aes(SSE_dev)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) + xlab(expression(Y[i] - hat(Y)[i]))\ngrid.arrange(SSY_plot, SSR_plot, SSE_plot, nrow = 3)\n```\n:::\n\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"right\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='right' width=576}\n:::\n:::\n\n:::\n\n::: column\n$$SSY = \\sum_{i=1}^n (Y_i - \\overline{Y})^2 = 45.75$$ \n\n \n\n$$SSR = \\sum_{i=1}^n (\\widehat{Y}_i- \\overline{Y})^2 = 12.28$$\n\n \n\n$$SSE =\\sum_{i=1}^n (Y_i - \\widehat{Y}_i)^2 = 33.47$$\n:::\n:::\n\n## What did you notice in the plots?\n\n::: columns\n::: {.column width=\"50%\"}\n::: L1\nSimple Linear Regression\n:::\n:::\n::: {.column width=\"50%\"}\n::: E1\nMultiple Linear Regression\n:::\n:::\n:::\n\n::: columns\n::: {.column width=\"35%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"15%\"}\n$$SSY = 45.75$$ \n\n \n\n \n\n$$SSR = 10.52$$\n\n \n\n \n\n$$SSE =35.23$$\n:::\n\n::: {.column width=\"35%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n::: {.column width=\"15%\"}\n$$SSY = 45.75$$ \n\n \n\n \n\n$$SSR = 12.28$$\n\n \n\n \n\n$$SSE =33.47$$\n:::\n:::\n\n- With F-test: we can determine if model fit is better by comparing the SSE's of different models\n\n## When running a F-test for linear models...\n\n-   We need to define a [larger, full model (more parameters)]{style=\"color: #4FADF3; font-weight: bold;\"}\n-   We need to define a [smaller, reduced model (fewer parameters)]{style=\"color: #FF8021; font-weight: bold;\"}\n-   Use the F-statistic to decide whether or not we reject the smaller model\n    -   The F-statistic compares the SSE of each model to determine if the full model explains a significant amount of additional variance\n\n::: columns\n::: {.column width=\"30%\"}\n \n\n$$\nF = \\dfrac{\\frac{SSE_{red} - SSE_{full}}{df_{red} - df_{full}}}{\\frac{SSE_{full}}{df_{full}}}\n$$\n:::\n\n::: {.column width=\"70%\"}\n-   [$SSE(R)$]{style=\"color: #FF8021;\"} $\\geq$ [$SSE(F)$]{style=\"color: #4FADF3;\"}\n-   Numerator measures difference in **unexplained** variation between the models\n    -   Big difference = added parameters greatly reduce the unexplained variation (increase explained variation)\n    -   Smaller difference = added parameters don't reduce the unexplained variation\n-   Take ratio of difference to the unexplained variation in the full model\n:::\n:::\n\n## Poll Everywhere Question 2\n\n## We will keep working with the MLR model from last class\n\nNew population model for example:\n\n$$\\text{LE} = \\beta_0 + \\beta_1 \\text{CP} + \\beta_2 \\text{VR} + \\epsilon$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr1 <- gapm %>% lm(formula = life_exp ~ cell_phones_100 + vax_rate)\ntidy(mlr1, conf.int=T) %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qnqtwncekq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qnqtwncekq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qnqtwncekq thead, #qnqtwncekq tbody, #qnqtwncekq tfoot, #qnqtwncekq tr, #qnqtwncekq td, #qnqtwncekq th {\n  border-style: none;\n}\n\n#qnqtwncekq p {\n  margin: 0;\n  padding: 0;\n}\n\n#qnqtwncekq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qnqtwncekq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qnqtwncekq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qnqtwncekq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qnqtwncekq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qnqtwncekq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qnqtwncekq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qnqtwncekq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qnqtwncekq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qnqtwncekq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qnqtwncekq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qnqtwncekq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qnqtwncekq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qnqtwncekq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qnqtwncekq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qnqtwncekq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qnqtwncekq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qnqtwncekq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qnqtwncekq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qnqtwncekq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qnqtwncekq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qnqtwncekq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qnqtwncekq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qnqtwncekq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qnqtwncekq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qnqtwncekq .gt_left {\n  text-align: left;\n}\n\n#qnqtwncekq .gt_center {\n  text-align: center;\n}\n\n#qnqtwncekq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qnqtwncekq .gt_font_normal {\n  font-weight: normal;\n}\n\n#qnqtwncekq .gt_font_bold {\n  font-weight: bold;\n}\n\n#qnqtwncekq .gt_font_italic {\n  font-style: italic;\n}\n\n#qnqtwncekq .gt_super {\n  font-size: 65%;\n}\n\n#qnqtwncekq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qnqtwncekq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qnqtwncekq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qnqtwncekq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qnqtwncekq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qnqtwncekq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qnqtwncekq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qnqtwncekq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qnqtwncekq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">46.833</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">6.042</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.751</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">34.848</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">58.818</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.075</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.018</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.074</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.039</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.112</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">vax_rate</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.168</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.073</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.318</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.022</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.024</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.312</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nFitted multiple regression model:\n\n$$\\begin{aligned}\n\\widehat{\\text{LE}} &= \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\text{CP} + \\widehat{\\beta}_2 \\text{VR} \\\\\n\\widehat{\\text{LE}} &= 46.833 + 0.075 \\ \\text{CP} \n+ 0.168\\ \\text{VR}\n\\end{aligned}$$\n\n## Building a very important toolkit: three types of tests\n\n::: fact\n::: fact-title\nOverall test\n:::\n\n::: fact-cont\nDoes at least one of the covariates/predictors contribute significantly to the prediction of Y?\n:::\n:::\n\n::: example\n::: ex-title\nTest for addition of a single variable's coefficient (covariate subset test)\n:::\n\n::: ex-cont\nDoes the addition of one particular covariate (with a single coefficient) add significantly to the prediction of Y achieved by other covariates already present in the model?\n:::\n:::\n\n::: proposition\n::: prop-title\nTest for addition of group of variables' coefficient (covariate subset test)\n:::\n\n::: prop-cont\nDoes the addition of some group of covariates (or one covariate with multiple coefficients) add significantly to the prediction of Y achieved by other covariates already present in the model?\n:::\n:::\n\n\n\n# Learning Objectives\n\n1.  Understand the use of the general F-test and interpret what it measures.\n\n::: lob\n2.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n:::\n\n3.  Understand the context of the **single covariate/coefficient F-test**, conduct the needed hypothesis test, and interpret the results.\n4.  Understand the context of the **group of covariates/coefficients F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## Overall F-test\n\nDoes at least one of the covariates/predictors contribute significantly to the prediction of Y?\n\n-   For a general population MLR model, $$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\ldots + \\beta_k X_k + \\epsilon$$\n\nWe can create a hypothesis test for all the covariate coefficients...\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=\\beta_2= \\ldots=\\beta_k=0$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\nAt least one $\\beta_j\\neq0$ (for $j=1, 2, \\ldots, k$)\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$Y = \\beta_0 + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\ldots + \\beta_k X_k + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n## Overall F-test: general steps for hypothesis test\n\n::: columns\n::: {.column width=\"48%\"}\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n    - Often, we are curious if the coefficient is 0 or not:\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1=\\beta_2= \\ldots=\\beta_k=0\\\\\n\\text{vs. } H_A&: \\text{At least one } \\beta_j\\neq0, \\text{for }j=1, 2, \\ldots, k\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $F$, and follows an F-distribution with numerator $df=k$ and denominator $df=n-k-1$. ($n$ = \\# obversation, $k$ = \\# covariates)\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"}\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}} = \\frac{MSR_{full}}{MSE_{full}}$$\n\n6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\n    - We are generally calculating: $P(F_{k, n-k-1} > F)$\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\n    - Reject: $P(F_{k, n-k-1} > F) < \\alpha$\n\nWe (reject/fail to reject) the null hypothesis at the $100\\alpha\\%$ significance level. There is\n(sufficient/ insufficient) evidence that at least one of the coefficients is not 0 (p-value = $P(F_{k, n-k-1} > F)$).\n:::\n:::\n\n## Overall F-test: a word on the conclusion\n\n-   If $H_0$ is rejected, we conclude there is sufficient evidence that at least one predictor's coefficient is different from zero.\n-   Same as: at least one independent variable contributes significantly to the prediction of $Y$\n\n \n\n-   If $H_0$ is not rejected, we conclude there is insufficient evidence that at least one predictor's coefficient is different from zero.\n-   Same as: Not enough evidence that at least one independent variable contributes significantly to the prediction of $Y$\n\n## Let's think about our MLR example for life expectancy\n\nOur proposed population model\n\n$$\\text{LE} = \\beta_0 + \\beta_1 \\text{CP} + \\beta_2 \\text{VR} + \\epsilon$$\n\nFitted multiple regression model:\n\n$$\\begin{aligned}\n\\widehat{\\text{LE}} &= \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\text{CP} + \\widehat{\\beta}_2 \\text{VR} \\\\\n\\widehat{\\text{LE}} &= 46.833 + 0.075 \\ \\text{CP} \n+ 0.168\\ \\text{VR}\n\\end{aligned}$$\n\n**Our main question for the Overall F-test:** Is the regression model containing cell phones and vaccination rate useful in estimating countries' life expectancy?\n\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$LE = \\beta_0 + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$LE = \\beta_0 + \\beta_1 CP + \\beta_2 VR + \\epsilon$\n:::\n:::\n:::\n:::\n\n## Comparing the SSY, SSR, and SSE for reduced and full model (reference) {visibility=\"hidden\"}\n\n- Fit and get augmented values for reduced model:\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_red1 = gapm %>% \n  lm(formula = life_exp ~ 1)\naug_red1  = augment(mod_red1)\n```\n:::\n\n\n- Fit and get augmented values for full model:\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_full1 = gapm %>% \n  lm(formula = life_exp ~ cell_phones_100 + vax_rate)\naug_full1  = augment(mod_full1)\n```\n:::\n\n\n- Calculate the deviances for each model:\n\n::: {.cell}\n\n```{.r .cell-code}\nSS_df2 = gapm %>% select(life_exp) %>%\n  mutate(SSY_diff_r1 = life_exp - mean(life_exp),\n         SSR_diff_r1 = aug_red1$.fitted - mean(life_exp), \n         SSE_diff_r1 = aug_red1$.resid, \n         SSY_diff_f1 = life_exp - mean(life_exp),\n         SSR_diff_f1 = aug_full1$.fitted - mean(life_exp), \n         SSE_diff_f1 = aug_full1$.resid)\n```\n:::\n\n\n## Comparing the SSY, SSR, and SSE for reduced and full model\n\n::: columns\n::: column\n::: I1\nReduced / null model\n:::\n\n$$LE = \\beta_0 + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 45.75$$ \n\n \n\n$$SSR = 0$$\n\n \n\n$$SSE = 45.75$$\n:::\n\n:::\n\n:::\n\n::: column\n::: L1\nFull / Alternative model\n:::\n\n$$LE = \\beta_0 + \\beta_1 CP + \\beta_2 VR + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 45.75$$ \n\n \n\n$$SSR = 12.28$$\n\n \n\n$$SSE = 33.47$$\n:::\n\n:::\n\n:::\n:::\n\n## Poll Everywhere Question 3\n\n\n\n## So let's step through our hypothesis test (1/3)\n\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1=\\beta_2=0\\\\\n\\text{vs. } H_A&: \\text{At least one } \\beta_1\\neq0 \\text{ or } \\beta_2\\neq0\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $F$, and follows an F-distribution with numerator $df=k=2$ and denominator $df=n-k-1=105 - 2-1=102$. ($n$ = \\# obversation, $k$ = \\# covariates)\n\n## So let's step through our hypothesis test (2/3)\n\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"} / 6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}=44.443$$\nOR use ANOVA table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_red1, mod_full1) %>% tidy() %>% gt() %>% \n  tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gxwetpkapy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gxwetpkapy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gxwetpkapy thead, #gxwetpkapy tbody, #gxwetpkapy tfoot, #gxwetpkapy tr, #gxwetpkapy td, #gxwetpkapy th {\n  border-style: none;\n}\n\n#gxwetpkapy p {\n  margin: 0;\n  padding: 0;\n}\n\n#gxwetpkapy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gxwetpkapy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gxwetpkapy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gxwetpkapy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gxwetpkapy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gxwetpkapy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gxwetpkapy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gxwetpkapy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gxwetpkapy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gxwetpkapy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gxwetpkapy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gxwetpkapy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gxwetpkapy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gxwetpkapy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gxwetpkapy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gxwetpkapy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gxwetpkapy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gxwetpkapy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gxwetpkapy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gxwetpkapy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gxwetpkapy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gxwetpkapy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gxwetpkapy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gxwetpkapy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gxwetpkapy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gxwetpkapy .gt_left {\n  text-align: left;\n}\n\n#gxwetpkapy .gt_center {\n  text-align: center;\n}\n\n#gxwetpkapy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gxwetpkapy .gt_font_normal {\n  font-weight: normal;\n}\n\n#gxwetpkapy .gt_font_bold {\n  font-weight: bold;\n}\n\n#gxwetpkapy .gt_font_italic {\n  font-style: italic;\n}\n\n#gxwetpkapy .gt_super {\n  font-size: 65%;\n}\n\n#gxwetpkapy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gxwetpkapy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gxwetpkapy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gxwetpkapy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gxwetpkapy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gxwetpkapy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gxwetpkapy .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gxwetpkapy .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gxwetpkapy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ 1</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">104.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">4,757.848</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ cell_phones_100 + vax_rate</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">102.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,480.371</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">1,277.478</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">18.720</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## So let's step through our hypothesis test (3/3)\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\n \n\nWe reject the null hypothesis at the 5% significance level. There is sufficient evidence that either countries' number of cell phones or vaccination rate (or both) contributes significantly to the prediction of life expectancy (p-value < 0.001).\n\n# Learning Objectives\n\n1.  Understand the use of the general F-test and interpret what it measures.\n2.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n\n::: lob\n3.  Understand the context of the **single covariate/coefficient F-test**, conduct the needed hypothesis test, and interpret the results.\n:::\n\n4.  Understand the context of the **group of covariates/coefficients F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## Covariate subset test: Single variable\n\nDoes the addition of one particular covariate of interest (a numeric covariate with only one coefficient) add significantly to the prediction of Y achieved by other covariates already present in the model?\n\n-   For a general population MLR model, $$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\beta_j X_j +\\ldots + \\beta_k X_k + \\epsilon$$\n\nWe can create a hypothesis test for a single $j$ covariate coefficient (where $j$ can be any value $1, 2, \\ldots, k$)...\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_j=0$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_j\\neq0$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\ldots + \\beta_k X_k + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$\\begin{aligned}Y = &\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_j X_j +\\\\ &\\ldots + \\beta_k X_k + \\epsilon \\end{aligned}$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n## Single covariate F-test: general steps for hypothesis test (reference)\n\n::: columns\n::: {.column width=\"48%\"}\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_j=0\\\\\n\\text{vs. } H_A&: \\beta_j\\neq 0\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $F$, and follows an F-distribution with numerator $df=k$ and denominator $df=n-k-1$. ($n$ = \\# obversation, $k$ = \\# covariates)\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"}\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\n\n6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\nWe are generally calculating: $P(F_{k, n-k-1} > F)$\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\nWe (reject/fail to reject) the null hypothesis at the $100\\alpha\\%$ significance level. There is (sufficient/insufficient) evidence that predictor/covariate $j$ significantly improves the prediction of Y, given all the other covariates are in the model (p-value = $P(F_{1, n-2} > F)$).\n:::\n:::\n\n## Let's think about our MLR example for life expectancy\n\nOur proposed population model\n\n$$\\text{LE} = \\beta_0 + \\beta_1 \\text{CP} + \\beta_2 \\text{VR} + \\epsilon$$\n\nFitted multiple regression model:\n\n$$\\begin{aligned}\n\\widehat{\\text{LE}} &= \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\text{CP} + \\widehat{\\beta}_2 \\text{VR} \\\\\n\\widehat{\\text{LE}} &= 33.595 + 0.157\\ \\text{CP} \n+ 0.008\\ \\text{VR}\n\\end{aligned}$$\n\n**Our main question for the single covariate subset F-test:** Is the regression model containing vaccination rate improve the estimation of countries' life expectancy, given cell phones per 100 people is already in the model?\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$LE = \\beta_0 + \\beta_1 CP + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$LE = \\beta_0 + \\beta_1 CP + \\beta_2 VR + \\epsilon$\n:::\n:::\n:::\n:::\n\n## Comparing the SSY, SSR, and SSE for reduced and full model\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: column\n::: I1\nReduced / null model\n:::\n\n$$LE = \\beta_0 + \\beta_1 CP + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 45.75$$ \n\n \n\n$$SSR = 10.52$$\n\n \n\n$$SSE = 35.23$$\n:::\n\n:::\n\n:::\n\n::: column\n::: L1\nFull / Alternative model\n:::\n\n$$LE = \\beta_0 + \\beta_1 CP + \\beta_2 VR + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 45.75$$ \n\n \n\n$$SSR = 12.28$$\n\n \n\n$$SSE = 33.47$$\n:::\n\n:::\n\n:::\n:::\n\n## Poll Everywhere Question 4\n\n## So let's step through our hypothesis test (1/3)\n\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_2=0\\\\\n\\text{vs. } H_A&: \\beta_2\\neq0 \n\\end{align}\n```\n\nOften we use $\\alpha = 0.05$\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $F$, and follows an F-distribution with numerator $df=k=2$ and denominator $df=n-k-1=105 - 2-1=102$. ($n$ = \\# obversation, $k$ = \\# covariates)\n\n## So let's step through our hypothesis test (2/3)\n\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"} / 6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\nANOVA table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_red2, mod_full2) %>% tidy() %>% gt() %>% \n  tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ggcdltkkch\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ggcdltkkch table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ggcdltkkch thead, #ggcdltkkch tbody, #ggcdltkkch tfoot, #ggcdltkkch tr, #ggcdltkkch td, #ggcdltkkch th {\n  border-style: none;\n}\n\n#ggcdltkkch p {\n  margin: 0;\n  padding: 0;\n}\n\n#ggcdltkkch .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ggcdltkkch .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ggcdltkkch .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ggcdltkkch .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ggcdltkkch .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ggcdltkkch .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ggcdltkkch .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ggcdltkkch .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ggcdltkkch .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ggcdltkkch .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ggcdltkkch .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ggcdltkkch .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ggcdltkkch .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ggcdltkkch .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ggcdltkkch .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggcdltkkch .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ggcdltkkch .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ggcdltkkch .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ggcdltkkch .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggcdltkkch .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ggcdltkkch .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggcdltkkch .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ggcdltkkch .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggcdltkkch .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ggcdltkkch .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ggcdltkkch .gt_left {\n  text-align: left;\n}\n\n#ggcdltkkch .gt_center {\n  text-align: center;\n}\n\n#ggcdltkkch .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ggcdltkkch .gt_font_normal {\n  font-weight: normal;\n}\n\n#ggcdltkkch .gt_font_bold {\n  font-weight: bold;\n}\n\n#ggcdltkkch .gt_font_italic {\n  font-style: italic;\n}\n\n#ggcdltkkch .gt_super {\n  font-size: 65%;\n}\n\n#ggcdltkkch .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ggcdltkkch .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ggcdltkkch .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ggcdltkkch .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ggcdltkkch .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ggcdltkkch .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ggcdltkkch .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ggcdltkkch .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ggcdltkkch div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ cell_phones_100</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">103.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,663.747</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ cell_phones_100 + vax_rate</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">102.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,480.371</td>\n<td headers=\"df\" class=\"gt_row gt_right\">1.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">183.376</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.374</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.022</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## So let's step through our hypothesis test (3/3)\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\n \n\nWe reject the null hypothesis at the 5% significance level. There is sufficient evidence that countries' vaccination rate contributes significantly to the prediction of life expectancy, given that cell phones per 100 people is already in the model (p-value < 0.001).\n\n# Learning Objectives\n\n1.  Understand the use of the general F-test and interpret what it measures.\n2.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n3.  Understand the context of the **single covariate/coefficient F-test**, conduct the needed hypothesis test, and interpret the results.\n\n::: lob\n4.  Understand the context of the **group of covariates/coefficients F-test**, conduct the needed hypothesis test, and interpret the results.\n:::\n\n## Covariate subset test: group of coefficients\n\nDoes the addition of some group of covariates of interest (or a multi-level categorical variable) add significantly to the prediction of Y obtained through other independent variables already present in the model?\n\n-   For a general population MLR model, $$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\ldots + \\beta_k X_k + \\epsilon$$\n\nWe can create a hypothesis test for a group of covariate coefficients (subset of many)... **For example...**\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=\\beta_3 =0$ (this can be any coefficients)\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\nAt least one $\\beta_j\\neq0$ (for $j=2,3$)\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$Y = \\beta_0 + \\beta_2 X_2 + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$Y = \\beta_0 + \\beta_1 X + \\beta_2 X + \\beta_3 X_3+\\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n## Covariate subset F-test: general steps for hypothesis test (reference)\n\n::: columns\n::: {.column width=\"48%\"}\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\nFor example: \n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = \\beta_3 = 0\\\\\n\\text{vs. } H_A&: \\text{At least one } \\beta_j\\neq0, \\text{for }j=1,3\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $F$, and follows an F-distribution with numerator $df=k$ and denominator $df=n-k-1$. ($n$ = \\# obversation, $k$ = \\# covariates)\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"}\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\n\n6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\nWe are generally calculating: $P(F_{k, n-k-1} > F)$\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\nWe (reject/fail to reject) the null hypothesis at the $100\\alpha\\%$ significance level. There is (sufficient/insufficient) evidence that predictors/covariates $2,3$ significantly improve the prediction of Y, given all the other covariates are in the model (p-value = $P(F_{1, n-2} > F)$).\n:::\n:::\n\n## We need to slightly alter our MLR example for life expectancy\n\nOur proposed population model to include percent access to basic sanitation (BS):\n\n$$\\text{LE} = \\beta_0 + \\beta_1 \\text{CP} + \\beta_2 \\text{VR} + \\beta_3 BS + \\epsilon$$\n\n-   We don't have a fitted multiple regression model for this yet!\n\n**Our main question for the group covariate subset F-test:** Is the regression model containing vaccination rate and basic sanitation percent improve the estimation of countries' life expectancy, given percent cell phones per 100 people is already in the model?\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$LE = \\beta_0 + \\beta_1 CP + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$LE = \\beta_0 + \\beta_1 CP + \\beta_2 VR + \\beta_3 BS + \\epsilon$\n:::\n:::\n:::\n:::\n\n## Comparing the SSY, SSR, and SSE for reduced and full model\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: column\n::: I1\nReduced / null model\n:::\n\n$$LE = \\beta_0 + \\beta_1 CP + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-24-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 45.75$$ \n\n \n\n$$SSR = 10.52$$\n\n \n\n$$SSE = 35.23$$\n:::\n\n:::\n\n:::\n\n::: column\n::: L1\nFull / Alternative model\n::: \n\n$$LE = \\beta_0 + \\beta_1 CP + \\beta_2 VR + \\beta_3 BS + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_MLR_F-test_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 45.75$$ \n\n \n\n$$SSR = 24.47$$\n\n \n\n$$SSE = 21.28$$\n:::\n\n:::\n\n:::\n:::\n\n## So let's step through our hypothesis test (1/3)\n\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_2=\\beta_3=0\\\\\n\\text{vs. } H_A&: \\beta_2\\neq0 \\text{ and/or } \\beta_3\\neq0\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $F$, and follows an F-distribution with numerator $df=k=2$ and denominator $df=n-k-1=105 - 2-1=102$. ($n$ = \\# obversation, $k$ = \\# covariates)\n\n## So let's step through our hypothesis test (2/3)\n\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"} / 6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\nANOVA table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_red3, mod_full3) %>% tidy() %>% gt() %>% \n  tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rkfonasurk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rkfonasurk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rkfonasurk thead, #rkfonasurk tbody, #rkfonasurk tfoot, #rkfonasurk tr, #rkfonasurk td, #rkfonasurk th {\n  border-style: none;\n}\n\n#rkfonasurk p {\n  margin: 0;\n  padding: 0;\n}\n\n#rkfonasurk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rkfonasurk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rkfonasurk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rkfonasurk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rkfonasurk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rkfonasurk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rkfonasurk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rkfonasurk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rkfonasurk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rkfonasurk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rkfonasurk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rkfonasurk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rkfonasurk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rkfonasurk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rkfonasurk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkfonasurk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rkfonasurk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rkfonasurk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rkfonasurk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkfonasurk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rkfonasurk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkfonasurk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rkfonasurk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkfonasurk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rkfonasurk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rkfonasurk .gt_left {\n  text-align: left;\n}\n\n#rkfonasurk .gt_center {\n  text-align: center;\n}\n\n#rkfonasurk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rkfonasurk .gt_font_normal {\n  font-weight: normal;\n}\n\n#rkfonasurk .gt_font_bold {\n  font-weight: bold;\n}\n\n#rkfonasurk .gt_font_italic {\n  font-style: italic;\n}\n\n#rkfonasurk .gt_super {\n  font-size: 65%;\n}\n\n#rkfonasurk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rkfonasurk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rkfonasurk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rkfonasurk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rkfonasurk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rkfonasurk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rkfonasurk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rkfonasurk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rkfonasurk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ cell_phones_100</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">103.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,663.747</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ cell_phones_100 + vax_rate + basic_sani</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">101.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">2,213.194</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">1,450.552</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">33.098</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## So let's step through our hypothesis test (3/3)\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\n \n\nWe reject the null hypothesis at the 5% significance level. There is sufficient evidence that countries' vaccination rate or basic sanitation (or both) contribute significantly to the prediction of life expectancy, given that cell phones per 100 people is already in the model (p-value < 0.001).\n\n## Other ways to word the hypothesis tests (reference)\n\n-   Single covariate subset F-test\n\n    -   $H_0:$ $X^*$ does not significantly improve the prediction of $Y$, given that $X_1, X_2, \\ldots, X_p$ are already in the model\n    -   $H_A:$ $X^*$ significantly improves the prediction of $Y$, given that $X_1, X_2, \\ldots, X_p$ are already in the model\n    \n-   Group covariate subset F-test\n\n    -   $H_0:$ The addition of the $s$ variables $X_1^*, X_2^*, \\ldots, X_s^*$ does not significantly improve the prediction of $Y$, given that $X_1, X_2, \\ldots, X_q$ are already in the model\n    -   $H_A:$ The addition of the $s$ variables $X_1^*, X_2^*, \\ldots, X_s^*$ significantly improves the prediction of $Y$, given that $X_1, X_2, \\ldots, X_q$ are already in the model",
    "supporting": [
      "10_MLR_F-test_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}