{
  "hash": "ca2053ae25e407b9364faa6e4f61e82e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 4: SLR Inference and Prediction\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"2026-01-14\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 4: SLR 2\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n\n\n\n\n\n# Learning Objectives\n\n1.  Estimate the variance of the residuals\n2.  Using a hypothesis test, determine if there is enough evidence that\n    population slope $\\beta_1$ is not 0 (applies to $\\beta_0$ as well)\n3.  Calculate and report the estimate and confidence interval for the\n    population slope $\\beta_1$ (applies to $\\beta_0$ as well)\n4.  Calculate and report the estimate and confidence interval for the\n    expected/mean response given $X$\n    \n\n::: {.cell}\n<style type=\"text/css\">\n.reveal code {\n  max-height: 100% !important;\n}\n</style>\n:::\n\n\n## Process of regression data analysis\n\n::: box\n![](../img_slides/arrow2.png){.absolute top=\"13.5%\" right=\"62.1%\" width=\"155\"} ![](../img_slides/arrow2.png){.absolute top=\"13.5%\" right=\"28.4%\" width=\"155\"}![](../img_slides/arrow_back4.png){.absolute top=\"7.5%\" right=\"30.5%\" width=\"820\"} ![](../img_slides/arrow_down.png){.absolute top=\"60.5%\" right=\"48%\" width=\"85\"}\n\n::: columns\n::: {.column width=\"30%\"}\n::: RAP1\n::: RAP1-title\nModel Selection\n:::\n\n::: RAP1-cont\n-   Building a model\n\n-   Selecting variables\n\n-   Prediction vs interpretation\n\n-   Comparing potential models\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP2\n::: RAP2-title\nModel Fitting\n:::\n\n::: RAP2-cont\n-   Find best fit line\n\n-   Using OLS in this class\n\n-   Parameter estimation\n\n-   Categorical covariates\n\n-   Interactions\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP3\n::: RAP3-title\nModel Evaluation\n:::\n\n::: RAP3-cont\n-   Evaluation of model fit\n-   Testing model assumptions\n-   Residuals\n-   Transformations\n-   Influential points\n-   Multicollinearity\n:::\n:::\n:::\n:::\n:::\n\n::: RAP4\n::: RAP4-title\nModel Use (Inference)\n:::\n\n::: RAP4-cont\n::: columns\n::: {.column width=\"50%\"}\n-   Inference for coefficients\n-   Hypothesis testing for coefficients\n:::\n\n::: {.column width=\"50%\"}\n-   Inference for expected $Y$ given $X$\n-   Prediction of new $Y$ given $X$\n:::\n:::\n:::\n:::\n\n\n## Let's remind ourselves of the model that we fit last lesson\n\n-   We fit Gapminder data with cell phones as our independent\n    variable and life expectancy as our dependent variable\n\n-   We used OLS to find the coefficient estimates of our best-fit line\n\n::: columns\n::: {.column width=\"53%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- gapm %>% \n  lm(formula = life_exp ~ cell_phones_100)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntidy(model1) %>% gt() %>% \n tab_options(table.font.size = 40) %>%\n fmt_number(decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mddjfxbdyz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mddjfxbdyz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mddjfxbdyz thead, #mddjfxbdyz tbody, #mddjfxbdyz tfoot, #mddjfxbdyz tr, #mddjfxbdyz td, #mddjfxbdyz th {\n  border-style: none;\n}\n\n#mddjfxbdyz p {\n  margin: 0;\n  padding: 0;\n}\n\n#mddjfxbdyz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mddjfxbdyz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mddjfxbdyz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mddjfxbdyz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mddjfxbdyz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mddjfxbdyz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mddjfxbdyz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mddjfxbdyz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mddjfxbdyz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mddjfxbdyz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mddjfxbdyz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mddjfxbdyz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mddjfxbdyz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mddjfxbdyz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mddjfxbdyz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mddjfxbdyz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mddjfxbdyz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mddjfxbdyz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mddjfxbdyz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mddjfxbdyz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mddjfxbdyz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mddjfxbdyz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mddjfxbdyz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mddjfxbdyz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mddjfxbdyz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mddjfxbdyz .gt_left {\n  text-align: left;\n}\n\n#mddjfxbdyz .gt_center {\n  text-align: center;\n}\n\n#mddjfxbdyz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mddjfxbdyz .gt_font_normal {\n  font-weight: normal;\n}\n\n#mddjfxbdyz .gt_font_bold {\n  font-weight: bold;\n}\n\n#mddjfxbdyz .gt_font_italic {\n  font-style: italic;\n}\n\n#mddjfxbdyz .gt_super {\n  font-size: 65%;\n}\n\n#mddjfxbdyz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mddjfxbdyz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mddjfxbdyz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mddjfxbdyz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mddjfxbdyz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mddjfxbdyz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mddjfxbdyz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mddjfxbdyz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mddjfxbdyz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.04</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.06</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.21</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.09</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.02</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.55</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n```{=tex}\n\\begin{aligned}\n\\widehat{Y} &= \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot X\\\\\n\\widehat{\\textrm{life expectancy}} &= 60.041 + 0.094 \\cdot \\textrm{cell phones}\n\\end{aligned}\n```\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-7-1.png){width=1056}\n:::\n:::\n\n:::\n:::\n\n## Fitted line is derived from the population SLR model\n\n \n\nThe (population) regression model is denoted by:\n\n::: heq\n$$Y =  \\beta_0 + \\beta_1X + \\epsilon$$\n:::\n\n-   $\\beta_0$ and $\\beta_1$ are **unknown** population parameters\n\n-   $\\epsilon$ (epsilon) is the error about the line\n\n    -   It is assumed to be a random variable with a...\n\n        -   Normal distribution with mean 0 and constant variance\n            $\\sigma^2$\n\n        -   i.e. $\\epsilon \\sim N(0, \\sigma^2)$\n\n## Poll Everywhere Question 1\n\n# Learning Objectives\n\n::: lob\n1.  Estimate the variance of the residuals\n:::\n\n2.  Using a hypothesis test, determine if there is enough evidence that\n    population slope $\\beta_1$ is not 0 (applies to $\\beta_0$ as well)\n3.  Calculate and report the estimate and confidence interval for the\n    population slope $\\beta_1$ (applies to $\\beta_0$ as well)\n4.  Calculate and report the estimate and confidence interval for the\n    expected/mean response given $X$\n\n## Residuals recap\n\n- Recall our population model residuals are distributed by\n    $\\epsilon \\sim N(0, \\sigma^2)$\n- And our estimated residuals are\n        $\\widehat\\epsilon \\sim N(0, \\widehat\\sigma^2)$\n\n \n\n::: columns\n::: {.column width=\"33%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n::: {.column width=\"33%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n\n::: {.column width=\"33%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n:::\n\n\n## $\\widehat\\sigma^2$: Needed ingredient for inference\n\n- **We need the variance of the residuals $\\sigma^2$ to perform inference on our\n    coefficients**\n\n-   The *variance* of the errors (residuals) is estimated by\n    $\\widehat{\\sigma}^2$\n\n::: heq\n$$\\widehat{\\sigma}^2 = S_{y|x}^2= \\frac{1}{n-2}\\sum_{i=1}^n (Y_i - \\widehat{Y}_i)^2 =\\frac{1}{n-2}SSE = MSE$$\n:::\n\n## $\\widehat\\sigma^2$: I hope R can calculate that for me... (1/2)\n\n::: columns\n::: {.column width=\"33%\"}\n-   The *standard deviation* $\\widehat{\\sigma}$ is given in the R output\n    as the `Residual standard error`\n\n    -   $4^{th}$ line from the bottom in the `summary()` output of the\n        model:\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"65%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_exp ~ cell_phones_100, data = .)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-17.211  -3.268   0.615   3.818  12.449 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     60.04051    2.05567  29.207  < 2e-16 ***\ncell_phones_100  0.09384    0.01692   5.546 2.27e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.964 on 103 degrees of freedom\nMultiple R-squared:   0.23,\tAdjusted R-squared:  0.2225 \nF-statistic: 30.76 on 1 and 103 DF,  p-value: 2.271e-07\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## $\\widehat\\sigma^2$: I hope R can calculate that for me... (2/2)\n\n- It can!!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_sum = summary(model1)\nm1_sum$sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.964089\n```\n\n\n:::\n\n```{.r .cell-code}\n# number of observations (pairs of data) used to run the model\nn = nobs(model1) \nn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 105\n```\n\n\n:::\n:::\n\n\n## $\\widehat\\sigma^2$ to SSE\n\n-   Recall how we minimized the SSE to find our line of best fit\n-   SSE and $\\widehat\\sigma^2$ are closely related:\n\n$$\\begin{aligned}\n\\widehat{\\sigma}^2 & = \\frac{1}{n-2}SSE\\\\\n5.964^2 & = \\frac{1}{105-2}SSE\\\\\nSSE & = 103 \\cdot 5.964^2 = 3663.75 \n\\end{aligned}$$\n\n-   3663.75 is the smallest sums of squares of all possible regression\n    lines through the data\n\n# Learning Objectives\n\n1.  Estimate the variance of the residuals\n\n::: lob\n2.  Using a hypothesis test, determine if there is enough evidence\n        that population slope $\\beta_1$ is not 0 (applies to $\\beta_0$\n        as well)\n\n3.  Calculate and report the estimate and confidence interval for\n        the population slope $\\beta_1$ (applies to $\\beta_0$ as well)\n:::\n\n4.  Calculate and report the estimate and confidence interval for the\n    expected/mean response given $X$\n\n## Do we trust our estimate $\\widehat\\beta_1$?\n\n-   So far, we have shown that we think the estimate is 0.094 \n\n \n\n-   $\\widehat\\beta_1$ (coefficient estimate) uses our sample data to estimate the population parameter $\\beta_1$\n\n \n\n-   Inference helps us figure out *mathematically* how much we trust our best-fit line \n\n \n\n-   Are we certain that the relationship between $X$ and $Y$ that we estimated reflects the true, underlying relationship?\n\n## Poll Everywhere Question 2\n\n## Inference for the population **slope**: hypothesis test and CI\n\n::: columns\n::: {.column width=\"45%\"}\n::: fact\n::: fact-title\nPopulation model\n:::\n\n::: fact-cont\n*line + random \"noise\"*\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\varepsilon$$ with\n$\\varepsilon \\sim N(0,\\sigma^2)$\\\n$\\sigma^2$ is the variance of the residuals\n:::\n:::\n\n::: proposition\n::: prop-title\nSample best-fit (least-squares) line\n:::\n\n::: prop-cont\n$$\\widehat{Y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot X $$\n\nNote: Some sources use $b$ instead of $\\widehat{\\beta}$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"50%\"}\n \n\nWe have two options for inference:\n\n1.  Conduct the **hypothesis test**\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n<br>\n\n*Note: R reports p-values for 2-sided tests*\n\n2.  Construct a **95% confidence interval** for the **population slope**\n    $\\beta_1$\n\n<br>\n:::\n:::\n\n# Learning Objectives\n\n1.  Estimate the variance of the residuals\n\n::: lob\n2.  Using a hypothesis test, determine if there is enough evidence that\n    population slope $\\beta_1$ is not 0 (applies to $\\beta_0$ as well)\n:::\n\n3.  Calculate and report the estimate and confidence interval for the\n    population slope $\\beta_1$ (applies to $\\beta_0$ as well)\n4.  Calculate and report the estimate and confidence interval for the\n    expected/mean response given $X$\n\n## Reference: Steps in a Hypothesis Test\n\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n    - What sampling distribution are you using? What assumptions are required for it?\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"} $\\alpha$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n    -  In symbols and/or in words\n    -  Alternative: one- or two-sided?\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"}.\n\n6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"} based on the observed test statistic and its sampling distribution\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"} to the hypothesis test\n\n    -  Do we reject or fail to reject $H_0$?\n    -  Write a conclusion in the context of the problem\n    \n\n\n## Steps for hypothesis test for population **slope** $\\beta_1$ (using t-test)\n\n::: columns\n::: {.column width=\"48%\"}\n\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n    - Often, we are curious if the coefficient is 0 or not:\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $t$, and follows a Student's t-distribution.\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n5.  Calculate the [**test statistic**]{style=\"color:#4FADF3\"}.\n\n    - The calculated **test statistic** for $\\widehat\\beta_1$ is $$t = \\frac{ \\widehat\\beta_1 - \\beta_1}{ \\text{SE}_{\\widehat\\beta_1}} = \\frac{ \\widehat\\beta_1}{ \\text{SE}_{\\widehat\\beta_1}}$$ when we assume $H_0: \\beta_1 = 0$ is true.\n\n6.  Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\n    - We are generally calculating: $2\\cdot P(T > |t|)$\n\n7.  Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\n    - We (reject/fail to reject) the null hypothesis that the slope is 0 at the $100\\alpha\\%$ significiance level. There is (sufficient/insufficient) evidence that there is significant association between ($Y$) and ($X$) (p-value = $P(T > t)$).\n:::\n:::\n\n## Standard error of fitted slope $\\widehat\\beta_1$\n\n![](../img_slides/pause.png){.absolute top=\"1%\" right=\"0%\" width=\"120\" height=\"120\"}\n\n   \n\n::: columns\n::: {.column width=\"50%\"}\n$$\\text{SE}_{\\widehat\\beta_1} = \\frac{\\widehat{\\sigma}}{s_X\\sqrt{n-1}}$$\n:::\n\n::: {.column width=\"50%\"}\n$\\text{SE}_{\\widehat\\beta_1}$ is a measure of **variability** of the estimate\n$\\widehat\\beta_1$\n:::\n:::\n\n   \n\n::: {style=\"font-size: 90%;\"}\n::: columns\n::: {.column width=\"32%\"}\n-   $\\widehat{\\sigma}$ is the standard deviation of the residuals\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"32%\"}\n-   $s_X$ is the sample standard deviation of the explanatory variable $X$\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"32%\"}\n-   $n$ is the sample size, or the number of observations in the model\n:::\n:::\n:::\n\n## Calculating standard error for $\\widehat\\beta_1$ (1/2)\n\n![](../img_slides/pause.png){.absolute top=\"1%\" right=\"0%\" width=\"120\" height=\"120\"}\n\n-   **Option 1:** Calculate using the formula\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic     p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>       <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.230         0.222  5.96      30.8 0.000000227     1  -335.  677.  685.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n\n```{.r .cell-code}\n# standard deviation of the residuals (Residual standard error in summary() output)\n(s_resid <- glance(model1)$sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.964089\n```\n\n\n:::\n\n```{.r .cell-code}\n# standard deviation of x's\n(s_x <- sd(gapm$cell_phones_100, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34.56469\n```\n\n\n:::\n\n```{.r .cell-code}\n# number of pairs of complete observations\n(n <- nobs(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 105\n```\n\n\n:::\n\n```{.r .cell-code}\n(se_b1 <- s_resid/(s_x * sqrt(n-1))) # compare to SE in regression output\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01691978\n```\n\n\n:::\n:::\n\n\n## Calculating standard error for $\\widehat\\beta_1$ (2/2)\n\n![](../img_slides/pause.png){.absolute top=\"1%\" right=\"0%\" width=\"120\" height=\"120\"}\n\n-   **Option 2:** Use regression table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# recall model1_b1 is regression table restricted to b1 row\nmodel1_b1 <-tidy(model1) %>% filter(term == \"cell_phones_100\")\nmodel1_b1 %>% gt() %>%\n  tab_options(table.font.size = 45) %>% fmt_number(decimals = 4)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"astammslxm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#astammslxm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#astammslxm thead, #astammslxm tbody, #astammslxm tfoot, #astammslxm tr, #astammslxm td, #astammslxm th {\n  border-style: none;\n}\n\n#astammslxm p {\n  margin: 0;\n  padding: 0;\n}\n\n#astammslxm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 45px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#astammslxm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#astammslxm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#astammslxm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#astammslxm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#astammslxm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#astammslxm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#astammslxm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#astammslxm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#astammslxm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#astammslxm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#astammslxm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#astammslxm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#astammslxm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#astammslxm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#astammslxm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#astammslxm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#astammslxm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#astammslxm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#astammslxm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#astammslxm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#astammslxm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#astammslxm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#astammslxm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#astammslxm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#astammslxm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#astammslxm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#astammslxm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#astammslxm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#astammslxm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#astammslxm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#astammslxm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#astammslxm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#astammslxm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#astammslxm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#astammslxm .gt_left {\n  text-align: left;\n}\n\n#astammslxm .gt_center {\n  text-align: center;\n}\n\n#astammslxm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#astammslxm .gt_font_normal {\n  font-weight: normal;\n}\n\n#astammslxm .gt_font_bold {\n  font-weight: bold;\n}\n\n#astammslxm .gt_font_italic {\n  font-style: italic;\n}\n\n#astammslxm .gt_super {\n  font-size: 65%;\n}\n\n#astammslxm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#astammslxm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#astammslxm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#astammslxm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#astammslxm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#astammslxm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#astammslxm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#astammslxm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#astammslxm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.0938</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.0169</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.5461</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.0000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Some important notes\n\n-   Today we are discussing the hypothesis test for a **single**\n    coefficient\n\n \n\n-   The test statistic for a single coefficient follows a Student's\n    t-distribution\n\n     \n\n    -   It can also follow an F-distribution, but we will discuss this\n        more with multiple linear regression and multi-level categorical\n        covariates\n\n \n\n-   Single coefficient testing can be done on any coefficient, but it is\n    most useful for continuous covariates or binary covariates\n\n     \n\n    -   This is because testing the single coefficient will still tell\n        us something about the overall relationship between the\n        covariate and the outcome\n\n     \n\n    -   We will talk more about this with multiple linear regression and\n        multi-level categorical covariates\n\n## Poll Everywhere Question 3\n\n## Life expectancy example: hypothesis test for population **slope** $\\beta_1$ (1/4)\n\n-   Steps 1-4 are setting up our hypothesis test: not much change from\n    the general steps\n\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}: We have met the underlying assumptions (checked in our Model Evaluation step)\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n    - We are testing if the slope is 0 or not:\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - The test statistic is $t$, and follows a Student's t-distribution.\n\n## Life expectancy example: hypothesis test for population **slope** $\\beta_1$ (2/4)\n\n5.Calculate the [**test statistic**]{style=\"color:#4FADF3\"} \n\n::: columns\n::: {.column width=\"49%\"}\n**Option 1:** Calculate the test statistic using the values in the\n    regression table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b1 <-tidy(model1) %>% \n  filter(term == \"cell_phones_100\")\nmodel1_b1 %>% gt() %>%\n  tab_options(table.font.size = 40) %>% \n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jeoknqbfut\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jeoknqbfut table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jeoknqbfut thead, #jeoknqbfut tbody, #jeoknqbfut tfoot, #jeoknqbfut tr, #jeoknqbfut td, #jeoknqbfut th {\n  border-style: none;\n}\n\n#jeoknqbfut p {\n  margin: 0;\n  padding: 0;\n}\n\n#jeoknqbfut .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jeoknqbfut .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jeoknqbfut .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jeoknqbfut .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jeoknqbfut .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jeoknqbfut .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jeoknqbfut .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jeoknqbfut .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jeoknqbfut .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jeoknqbfut .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jeoknqbfut .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jeoknqbfut .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jeoknqbfut .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jeoknqbfut .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jeoknqbfut .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jeoknqbfut .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jeoknqbfut .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jeoknqbfut .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jeoknqbfut .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jeoknqbfut .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jeoknqbfut .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jeoknqbfut .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jeoknqbfut .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jeoknqbfut .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jeoknqbfut .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jeoknqbfut .gt_left {\n  text-align: left;\n}\n\n#jeoknqbfut .gt_center {\n  text-align: center;\n}\n\n#jeoknqbfut .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jeoknqbfut .gt_font_normal {\n  font-weight: normal;\n}\n\n#jeoknqbfut .gt_font_bold {\n  font-weight: bold;\n}\n\n#jeoknqbfut .gt_font_italic {\n  font-style: italic;\n}\n\n#jeoknqbfut .gt_super {\n  font-size: 65%;\n}\n\n#jeoknqbfut .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jeoknqbfut .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jeoknqbfut .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jeoknqbfut .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jeoknqbfut .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jeoknqbfut .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jeoknqbfut .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jeoknqbfut .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jeoknqbfut div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.094</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.546</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n(TestStat_b1 <- model1_b1$estimate / \n    model1_b1$std.error)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.546063\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"49%\"}\n**Option 2:** Get the test statistic value ($t^*$) from `R`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b1 %>% gt() %>%\n  tab_options(table.font.size = 40) %>% \n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uomiivlsnj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uomiivlsnj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uomiivlsnj thead, #uomiivlsnj tbody, #uomiivlsnj tfoot, #uomiivlsnj tr, #uomiivlsnj td, #uomiivlsnj th {\n  border-style: none;\n}\n\n#uomiivlsnj p {\n  margin: 0;\n  padding: 0;\n}\n\n#uomiivlsnj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uomiivlsnj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uomiivlsnj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uomiivlsnj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uomiivlsnj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uomiivlsnj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uomiivlsnj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uomiivlsnj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uomiivlsnj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uomiivlsnj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uomiivlsnj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uomiivlsnj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uomiivlsnj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uomiivlsnj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uomiivlsnj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uomiivlsnj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uomiivlsnj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uomiivlsnj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uomiivlsnj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uomiivlsnj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uomiivlsnj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uomiivlsnj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uomiivlsnj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uomiivlsnj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uomiivlsnj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uomiivlsnj .gt_left {\n  text-align: left;\n}\n\n#uomiivlsnj .gt_center {\n  text-align: center;\n}\n\n#uomiivlsnj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uomiivlsnj .gt_font_normal {\n  font-weight: normal;\n}\n\n#uomiivlsnj .gt_font_bold {\n  font-weight: bold;\n}\n\n#uomiivlsnj .gt_font_italic {\n  font-style: italic;\n}\n\n#uomiivlsnj .gt_super {\n  font-size: 65%;\n}\n\n#uomiivlsnj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uomiivlsnj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uomiivlsnj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uomiivlsnj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uomiivlsnj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uomiivlsnj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uomiivlsnj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uomiivlsnj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uomiivlsnj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.094</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.546</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n:::\n\n## Life expectancy example: hypothesis test for population **slope** $\\beta_1$ (3/4)\n\n6.Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\n-   The $p$-value is the *probability of obtaining a test statistic*\n    **just as extreme or more extreme** *than the **observed** test\n    statistic assuming the null hypothesis* $H_0$ *is true*\n\n-   We know the probability distribution of the test statistic (the\n    *null distribution*) assuming $H_0$ is true\n\n-   Statistical theory tells us that the test statistic $t$ can be\n    modeled by a $t$-distribution with $df = n-2$.\n\n    -   We had 105 countries' data, so $n=105$\n\n::: columns\n::: {.column width=\"49%\"}\n**Option 1:** Use `pt()` and our calculated test statistic\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pv = 2*pt(TestStat_b1, \n           df=n-2, \n           lower.tail=F))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.271176e-07\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"2%\"}\n:::\n::: {.column width=\"49%\"}\n**Option 2:** Use the regression table output\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b1 %>% gt() %>% \n  tab_options(table.font.size = 40) %>% \n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"afrhtxmvgj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#afrhtxmvgj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#afrhtxmvgj thead, #afrhtxmvgj tbody, #afrhtxmvgj tfoot, #afrhtxmvgj tr, #afrhtxmvgj td, #afrhtxmvgj th {\n  border-style: none;\n}\n\n#afrhtxmvgj p {\n  margin: 0;\n  padding: 0;\n}\n\n#afrhtxmvgj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#afrhtxmvgj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#afrhtxmvgj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#afrhtxmvgj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#afrhtxmvgj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#afrhtxmvgj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#afrhtxmvgj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#afrhtxmvgj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#afrhtxmvgj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#afrhtxmvgj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#afrhtxmvgj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#afrhtxmvgj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#afrhtxmvgj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#afrhtxmvgj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#afrhtxmvgj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afrhtxmvgj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#afrhtxmvgj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#afrhtxmvgj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#afrhtxmvgj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afrhtxmvgj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#afrhtxmvgj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afrhtxmvgj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#afrhtxmvgj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afrhtxmvgj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#afrhtxmvgj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afrhtxmvgj .gt_left {\n  text-align: left;\n}\n\n#afrhtxmvgj .gt_center {\n  text-align: center;\n}\n\n#afrhtxmvgj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#afrhtxmvgj .gt_font_normal {\n  font-weight: normal;\n}\n\n#afrhtxmvgj .gt_font_bold {\n  font-weight: bold;\n}\n\n#afrhtxmvgj .gt_font_italic {\n  font-style: italic;\n}\n\n#afrhtxmvgj .gt_super {\n  font-size: 65%;\n}\n\n#afrhtxmvgj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#afrhtxmvgj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#afrhtxmvgj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#afrhtxmvgj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#afrhtxmvgj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#afrhtxmvgj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#afrhtxmvgj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#afrhtxmvgj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#afrhtxmvgj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.094</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.546</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n:::\n\n## Life expectancy example: hypothesis test for population **slope** $\\beta_1$ (4/4)\n\n7. Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\n \n\nWe reject the null hypothesis that the slope is 0 at the $5\\%$\nsignificance level. There is sufficient evidence that there is\nassociation between life expectancy and number of cell phones per 100 people (p-value \\< 0.0001).\n\n## Note on hypothesis testing using `R`\n\n-   We can basically combine Step 5 and 6 if we are using the \"Option 2\" route\n\n \n\n-   In our assignments: if you use Option 2, Step 5and 6 become one\n\n    -   Unless I specifically ask for the test statistic!!\n\n## Life expectancy ex: hypothesis test for population **intercept** $\\beta_0$ (1/4)\n\n1.  Check the [**assumptions**]{style=\"color:#4FADF3\"}: We have met the underlying assumptions (checked in our Model Evaluation step)\n\n2.  Set the [**level of significance**]{style=\"color:#4FADF3\"}\n\n    - Often we use $\\alpha = 0.05$\n\n3.  Specify the [**null**]{style=\"color:#4FADF3\"} ( $H_0$ ) and [**alternative**]{style=\"color:#4FADF3\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#4FADF3\"}\n\n    - We are testing if the intercept is 0 or not:\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_0 = 0\\\\\n\\text{vs. } H_A&: \\beta_0 \\neq 0\n\\end{align}\n```\n\n4.  Specify the test statistic and its [**distribution under the null**]{style=\"color:#4FADF3\"}\n\n    - This is the same as the slope. The test statistic is $t$, and follows a Student's t-distribution.\n\n## Life expectancy ex: hypothesis test for population **intercept** $\\beta_0$ (2/4)\n\n5.Calculate the [**test statistic**]{style=\"color:#4FADF3\"} \n\n::: columns\n::: {.column width=\"49%\"}\n**Option 1:** Calculate the test statistic using the values in the\n    regression table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b0 <- tidy(model1) %>% \n  filter(term == \"(Intercept)\")\nmodel1_b0 %>% gt() %>%\n  tab_options(table.font.size = 40) %>% \n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ptgtabdcxh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ptgtabdcxh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ptgtabdcxh thead, #ptgtabdcxh tbody, #ptgtabdcxh tfoot, #ptgtabdcxh tr, #ptgtabdcxh td, #ptgtabdcxh th {\n  border-style: none;\n}\n\n#ptgtabdcxh p {\n  margin: 0;\n  padding: 0;\n}\n\n#ptgtabdcxh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ptgtabdcxh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ptgtabdcxh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ptgtabdcxh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ptgtabdcxh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ptgtabdcxh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ptgtabdcxh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ptgtabdcxh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ptgtabdcxh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ptgtabdcxh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ptgtabdcxh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ptgtabdcxh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ptgtabdcxh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ptgtabdcxh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ptgtabdcxh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptgtabdcxh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ptgtabdcxh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ptgtabdcxh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ptgtabdcxh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptgtabdcxh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ptgtabdcxh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptgtabdcxh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ptgtabdcxh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptgtabdcxh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ptgtabdcxh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptgtabdcxh .gt_left {\n  text-align: left;\n}\n\n#ptgtabdcxh .gt_center {\n  text-align: center;\n}\n\n#ptgtabdcxh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ptgtabdcxh .gt_font_normal {\n  font-weight: normal;\n}\n\n#ptgtabdcxh .gt_font_bold {\n  font-weight: bold;\n}\n\n#ptgtabdcxh .gt_font_italic {\n  font-style: italic;\n}\n\n#ptgtabdcxh .gt_super {\n  font-size: 65%;\n}\n\n#ptgtabdcxh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ptgtabdcxh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ptgtabdcxh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ptgtabdcxh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ptgtabdcxh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ptgtabdcxh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ptgtabdcxh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ptgtabdcxh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ptgtabdcxh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.056</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.207</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n(TestStat_b0 <- model1_b0$estimate / \n    model1_b0$std.error)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 29.20728\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"49%\"}\n**Option 2:** Get the test statistic value ($t^*$) from `R`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b0 %>% gt() %>% \n  tab_options(table.font.size = 40) %>% \n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"aisnlylvdv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#aisnlylvdv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#aisnlylvdv thead, #aisnlylvdv tbody, #aisnlylvdv tfoot, #aisnlylvdv tr, #aisnlylvdv td, #aisnlylvdv th {\n  border-style: none;\n}\n\n#aisnlylvdv p {\n  margin: 0;\n  padding: 0;\n}\n\n#aisnlylvdv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#aisnlylvdv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#aisnlylvdv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#aisnlylvdv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#aisnlylvdv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#aisnlylvdv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#aisnlylvdv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#aisnlylvdv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#aisnlylvdv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#aisnlylvdv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#aisnlylvdv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#aisnlylvdv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#aisnlylvdv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#aisnlylvdv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#aisnlylvdv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aisnlylvdv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#aisnlylvdv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#aisnlylvdv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#aisnlylvdv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aisnlylvdv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#aisnlylvdv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aisnlylvdv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#aisnlylvdv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aisnlylvdv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aisnlylvdv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aisnlylvdv .gt_left {\n  text-align: left;\n}\n\n#aisnlylvdv .gt_center {\n  text-align: center;\n}\n\n#aisnlylvdv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#aisnlylvdv .gt_font_normal {\n  font-weight: normal;\n}\n\n#aisnlylvdv .gt_font_bold {\n  font-weight: bold;\n}\n\n#aisnlylvdv .gt_font_italic {\n  font-style: italic;\n}\n\n#aisnlylvdv .gt_super {\n  font-size: 65%;\n}\n\n#aisnlylvdv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#aisnlylvdv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#aisnlylvdv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#aisnlylvdv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#aisnlylvdv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#aisnlylvdv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#aisnlylvdv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#aisnlylvdv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#aisnlylvdv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.056</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.207</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n:::\n\n## Life expectancy ex: hypothesis test for population **intercept** $\\beta_0$ (3/4)\n\n6.Calculate the [**p-value**]{style=\"color:#4FADF3\"}\n\n \n\n::: columns\n::: {.column width=\"49%\"}\n**Option 1:** Use `pt()` and our calculated test statistic\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pv = 2*pt(TestStat_b0, \n           df=n-2, \n           lower.tail=F))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.215444e-51\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"2%\"}\n:::\n::: {.column width=\"49%\"}\n**Option 2:** Use the regression table output\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b0 %>% gt() %>%\n  tab_options(table.font.size = 40) %>%\n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wlevpwfsma\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wlevpwfsma table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wlevpwfsma thead, #wlevpwfsma tbody, #wlevpwfsma tfoot, #wlevpwfsma tr, #wlevpwfsma td, #wlevpwfsma th {\n  border-style: none;\n}\n\n#wlevpwfsma p {\n  margin: 0;\n  padding: 0;\n}\n\n#wlevpwfsma .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wlevpwfsma .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wlevpwfsma .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wlevpwfsma .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wlevpwfsma .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wlevpwfsma .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wlevpwfsma .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wlevpwfsma .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wlevpwfsma .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wlevpwfsma .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wlevpwfsma .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wlevpwfsma .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wlevpwfsma .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wlevpwfsma .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wlevpwfsma .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wlevpwfsma .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wlevpwfsma .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wlevpwfsma .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wlevpwfsma .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wlevpwfsma .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wlevpwfsma .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wlevpwfsma .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wlevpwfsma .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wlevpwfsma .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wlevpwfsma .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wlevpwfsma .gt_left {\n  text-align: left;\n}\n\n#wlevpwfsma .gt_center {\n  text-align: center;\n}\n\n#wlevpwfsma .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wlevpwfsma .gt_font_normal {\n  font-weight: normal;\n}\n\n#wlevpwfsma .gt_font_bold {\n  font-weight: bold;\n}\n\n#wlevpwfsma .gt_font_italic {\n  font-style: italic;\n}\n\n#wlevpwfsma .gt_super {\n  font-size: 65%;\n}\n\n#wlevpwfsma .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wlevpwfsma .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wlevpwfsma .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wlevpwfsma .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wlevpwfsma .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wlevpwfsma .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wlevpwfsma .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wlevpwfsma .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wlevpwfsma div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.056</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.207</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n:::\n\n## Life expectancy ex: hypothesis test for population **intercept** $\\beta_0$ (4/4)\n\n7. Write a [**conclusion**]{style=\"color:#4FADF3\"}\n\n \n\nWe reject the null hypothesis that the intercept is 0 at the $5\\%$\nsignificance level. There is sufficient evidence that the intercept for\nthe association between life expectancy and number of cell phones per 100 people is different from 0 (p-value \\< 0.0001).\n\n   \n\n-   Note: if we fail to reject $H_0$, then we *could* decide to remove the\n    intercept from the model to force the regression line to go through\n    the origin (0,0) if it makes sense to do so for the application\n    - Not typical to remove the intercept\n\n# Learning Objectives\n\n1.  Estimate the variance of the residuals\n2.  Using a hypothesis test, determine if there is enough evidence that\n    population slope $\\beta_1$ is not 0 (applies to $\\beta_0$ as well)\n    \n::: lob\n3.  Calculate and report the estimate and confidence interval for the\n    population slope $\\beta_1$ (applies to $\\beta_0$ as well)\n:::\n\n4.  Calculate and report the estimate and confidence interval for the\n    expected/mean response given $X$\n\n## Inference for the population **slope**: hypothesis test and CI\n\n::: columns\n::: {.column width=\"45%\"}\n::: fact\n::: fact-title\nPopulation model\n:::\n\n::: fact-cont\n*line + random \"noise\"*\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\varepsilon$$ with\n$\\varepsilon \\sim N(0,\\sigma^2)$\\\n$\\sigma^2$ is the variance of the residuals\n:::\n:::\n\n::: proposition\n::: prop-title\nSample best-fit (least-squares) line\n:::\n\n::: prop-cont\n$$\\widehat{Y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot X $$\n\nNote: Some sources use $b$ instead of $\\widehat{\\beta}$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"50%\"}\n \n\nWe have two options for inference:\n\n1.  Conduct the **hypothesis test**\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n<br>\n\n*Note: R reports p-values for 2-sided tests*\n\n2.  Construct a **95% confidence interval** for the **population slope**\n    $\\beta_1$\n\n<br>\n:::\n:::\n\n## Confidence interval for population **slope** $\\beta_1$\n\nRecall the general CI formula:\n\n$$\\widehat{\\beta}_1 \\pm t_{\\alpha, n-2}^* \\cdot SE_{\\widehat{\\beta}_1}$$\n\nTo construct the confidence interval, we need to:\n\n-   Set our $\\alpha$-level\n\n-   Find $\\widehat\\beta_1$\n\n-   Calculate the $t_{n-2}^*$\n\n-   Calculate $SE_{\\widehat{\\beta}_1}$\n\n## Calculate CI for population **slope** $\\beta_1$ (1/2)\n\n::: columns\n::: {.column width=\"50%\"}\n$$\\widehat{\\beta}_1  \\pm t^*\\cdot SE_{\\beta_1}$$\n:::\n\n::: {.column width=\"50%\"}\nwhere $t^*$ is the $t$-distribution critical value with $df = n -2$.\n:::\n:::\n\n-   **Option 1:** Calculate using each value\n\nSave values needed for CI:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb1 <- model1_b1$estimate\nSE_b1 <- model1_b1$std.error\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnobs(model1) # sample size n\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 105\n```\n\n\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, df = n - 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.983264\n```\n\n\n:::\n:::\n\n\nUse formula to calculate each bound\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(CI_LB <- b1 - tstar*SE_b1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06028178\n```\n\n\n:::\n\n```{.r .cell-code}\n(CI_UB <- b1 + tstar*SE_b1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1273946\n```\n\n\n:::\n:::\n\n\n## Calculate CI for population **slope** $\\beta_1$ (2/2)\n\n::: columns\n::: {.column width=\"50%\"}\n$$\\widehat{\\beta}_1  \\pm t^*\\cdot SE_{\\beta_1}$$\n:::\n\n::: {.column width=\"50%\"}\nwhere $t^*$ is the $t$-distribution critical value with $df = n -2$.\n:::\n:::\n\n-   **Option 2:** Use the regression table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = T) %>% gt() %>%\n  tab_options(table.font.size = 40) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vbyprptwsp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vbyprptwsp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vbyprptwsp thead, #vbyprptwsp tbody, #vbyprptwsp tfoot, #vbyprptwsp tr, #vbyprptwsp td, #vbyprptwsp th {\n  border-style: none;\n}\n\n#vbyprptwsp p {\n  margin: 0;\n  padding: 0;\n}\n\n#vbyprptwsp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vbyprptwsp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vbyprptwsp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vbyprptwsp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vbyprptwsp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vbyprptwsp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vbyprptwsp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vbyprptwsp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vbyprptwsp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vbyprptwsp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vbyprptwsp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vbyprptwsp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vbyprptwsp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vbyprptwsp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vbyprptwsp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbyprptwsp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vbyprptwsp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vbyprptwsp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vbyprptwsp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbyprptwsp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vbyprptwsp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbyprptwsp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vbyprptwsp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbyprptwsp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vbyprptwsp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vbyprptwsp .gt_left {\n  text-align: left;\n}\n\n#vbyprptwsp .gt_center {\n  text-align: center;\n}\n\n#vbyprptwsp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vbyprptwsp .gt_font_normal {\n  font-weight: normal;\n}\n\n#vbyprptwsp .gt_font_bold {\n  font-weight: bold;\n}\n\n#vbyprptwsp .gt_font_italic {\n  font-style: italic;\n}\n\n#vbyprptwsp .gt_super {\n  font-size: 65%;\n}\n\n#vbyprptwsp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vbyprptwsp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vbyprptwsp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vbyprptwsp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vbyprptwsp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vbyprptwsp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vbyprptwsp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vbyprptwsp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vbyprptwsp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.056</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.207</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">55.964</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">64.117</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.094</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.546</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.060</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.127</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Interpreting the coefficient estimate of the population slope with CIs\n\n-   When we report our results to someone else, we don't usually show\n    them our full hypothesis test\n\n    -   In an informal setting, someone may want to see it\n\n-   Typically, we report the estimate with the confidence interval\n\n    -   From the confidence interval, your audience can also deduce the\n        results of a hypothesis test\n\n-   Once we found our CI, we often just write the interpretation of the\n    coefficient estimate:\n\n::: definition\n::: def-title\nGeneral statement for population slope inference\n:::\n\n::: def-cont\nFor every increase of 1 unit in the $X$-variable, there is an expected/average (pick one) increase of $\\widehat\\beta_1$ units in the $Y$-variable (95%:\nLB, UB).\n:::\n:::\n\n-   **In our example:** For every additional cell phone per 100 people, life expectancy increases, on average,\n    0.094 years (95% CI: 0.06, 0.127)\n    \n## Usually three options for your interpretations\n\n- **Option 1:** For every additional cell phone per 100 people, life expectancy increases, **on average**,\n    0.094 years (95% CI: 0.06, 0.127)\n    \n \n\n- **Option 2:** For every additional cell phone per 100 people, **average** life expectancy increases\n    0.094 years (95% CI: 0.06, 0.127)\n    \n \n\n- **Option 3:** For every additional cell phone per 100 people, **expected** life expectancy increases\n    0.094 years (95% CI: 0.06, 0.127)\n\n## Poll Everywhere Question 4\n\n## For reference: quick CI for $\\beta_0$\n\n-   Calculate CI for population **intercept** $\\beta_0$:\n    $\\widehat{\\beta}_0 \\pm t^*\\cdot SE_{\\widehat{\\beta}_0}$\n\nwhere $t^*$ is the $t$-distribution critical value with $df = n -2$\n\n-   Use the regression table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = T) %>% gt() %>%\n  tab_options(table.font.size = 40) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ealliinvtd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ealliinvtd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ealliinvtd thead, #ealliinvtd tbody, #ealliinvtd tfoot, #ealliinvtd tr, #ealliinvtd td, #ealliinvtd th {\n  border-style: none;\n}\n\n#ealliinvtd p {\n  margin: 0;\n  padding: 0;\n}\n\n#ealliinvtd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ealliinvtd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ealliinvtd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ealliinvtd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ealliinvtd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ealliinvtd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ealliinvtd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ealliinvtd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ealliinvtd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ealliinvtd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ealliinvtd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ealliinvtd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ealliinvtd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ealliinvtd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ealliinvtd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ealliinvtd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ealliinvtd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ealliinvtd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ealliinvtd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ealliinvtd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ealliinvtd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ealliinvtd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ealliinvtd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ealliinvtd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ealliinvtd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ealliinvtd .gt_left {\n  text-align: left;\n}\n\n#ealliinvtd .gt_center {\n  text-align: center;\n}\n\n#ealliinvtd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ealliinvtd .gt_font_normal {\n  font-weight: normal;\n}\n\n#ealliinvtd .gt_font_bold {\n  font-weight: bold;\n}\n\n#ealliinvtd .gt_font_italic {\n  font-style: italic;\n}\n\n#ealliinvtd .gt_super {\n  font-size: 65%;\n}\n\n#ealliinvtd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ealliinvtd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ealliinvtd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ealliinvtd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ealliinvtd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ealliinvtd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ealliinvtd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ealliinvtd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ealliinvtd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.056</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.207</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">55.964</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">64.117</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.094</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.546</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.060</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.127</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: definition\n::: def-title\nGeneral statement for population intercept inference\n:::\n\n::: def-cont\nThe expected outcome for the $Y$-variable is ($\\widehat\\beta_0$) when\nthe $X$-variable is 0 (95% CI: LB, UB).\n:::\n:::\n\n-   **For example:** The average life expectancy is 60.04 years\n    when the number of cell phones per 100 people is 0 (95% CI: 55.96, 64.12).\n\n# Learning Objectives\n\n1.  Estimate the variance of the residuals\n2.  Using a hypothesis test, determine if there is enough evidence that\n    population slope $\\beta_1$ is not 0 (applies to $\\beta_0$ as well)\n3.  Calculate and report the estimate and confidence interval for the\n    population slope $\\beta_1$ (applies to $\\beta_0$ as well)\n\n::: lob\n4.  Calculate and report the estimate and confidence interval for the\n    expected/mean response given $X$\n:::\n\n## Finding a mean response given a value of our independent variable\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"opfpdzfnnm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#opfpdzfnnm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#opfpdzfnnm thead, #opfpdzfnnm tbody, #opfpdzfnnm tfoot, #opfpdzfnnm tr, #opfpdzfnnm td, #opfpdzfnnm th {\n  border-style: none;\n}\n\n#opfpdzfnnm p {\n  margin: 0;\n  padding: 0;\n}\n\n#opfpdzfnnm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#opfpdzfnnm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#opfpdzfnnm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#opfpdzfnnm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#opfpdzfnnm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#opfpdzfnnm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#opfpdzfnnm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#opfpdzfnnm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#opfpdzfnnm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#opfpdzfnnm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#opfpdzfnnm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#opfpdzfnnm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#opfpdzfnnm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#opfpdzfnnm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#opfpdzfnnm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opfpdzfnnm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#opfpdzfnnm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#opfpdzfnnm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#opfpdzfnnm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opfpdzfnnm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#opfpdzfnnm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opfpdzfnnm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#opfpdzfnnm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opfpdzfnnm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#opfpdzfnnm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opfpdzfnnm .gt_left {\n  text-align: left;\n}\n\n#opfpdzfnnm .gt_center {\n  text-align: center;\n}\n\n#opfpdzfnnm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#opfpdzfnnm .gt_font_normal {\n  font-weight: normal;\n}\n\n#opfpdzfnnm .gt_font_bold {\n  font-weight: bold;\n}\n\n#opfpdzfnnm .gt_font_italic {\n  font-style: italic;\n}\n\n#opfpdzfnnm .gt_super {\n  font-size: 65%;\n}\n\n#opfpdzfnnm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#opfpdzfnnm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#opfpdzfnnm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#opfpdzfnnm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#opfpdzfnnm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#opfpdzfnnm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#opfpdzfnnm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#opfpdzfnnm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#opfpdzfnnm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.041</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.056</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.207</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">cell_phones_100</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.094</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.546</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\\widehat{\\textrm{life expectancy}} = 60.041 + 0.094 \\cdot \\textrm{cell phones} $$\n\n-   What is the expected/predicted life expectancy for any country with 60 cell phones per 100 people?\n\n$$\\widehat{\\textrm{life expectancy}} = 60.041 + 0.094 \\cdot 60 = 65.671$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(y_60 <- tidy(model1)$estimate[1] + tidy(model1)$estimate[2]*60)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 65.6708\n```\n\n\n:::\n:::\n\n\n-   How do we interpret the expected value?\n\n    -   We sometimes call this \"predicted\" value, since we can\n        technically use a number (of cell phones) that is not in our sample\n\n-   How variable is it?\n\n## Mean response/prediction with regression line\n\n::: columns\n::: {.column width=\"55%\"}\nRecall the population model:\n\n*line + random \"noise\"*\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\varepsilon$$ with\n$\\varepsilon \\sim N(0,\\sigma^2)$\n\n<br>\n\n-   When we take the expected value, at a given value $X^*$, the average/expected response at $X^*$ is:\n\n$$\\widehat{E}[Y|X^*] = \\widehat\\beta_0 + \\widehat\\beta_1 X^*$$\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-30-1.png){width=864}\n:::\n:::\n\n:::\n:::\n\n-   These are the points on the regression line\n-   The mean responses have variability, and we can calculate a CI for\n    it, for every value of $X^*$\n\n## CI for population mean response ($\\widehat{E}[Y|X^*]$ or $\\mu_{Y|X^*})$\n\n$$\\widehat{E}[Y|X^*] \\pm t_{n-2}^* \\cdot SE_{\\widehat{E}[Y|X^*]}$$\n\n$$SE_{\\widehat{E}[Y|X^*]} = \\widehat{\\sigma} \\sqrt{\\frac{1}{n} + \\frac{(X^* - \\overline{X})^2}{(n-1)s_X^2}}$$\n\n-   $\\widehat{E}[Y|X^*]$ is the predicted value at the specified point\n    $X^*$ of the explanatory variable\n-   $\\widehat{\\sigma}^2$ is the sd of the residuals\n-   $n$ is the sample size, or the number of (complete) pairs of points\n-   $\\overline{X}$ is the sample mean of the explanatory variable $x$\n-   $s_X$ is the sample sd of the explanatory variable $X$\n\n<br>\n\n-   Recall that $t_{n-2}^*$ is calculated using `qt()` and depends on\n    the confidence level ($1-\\alpha$)\n\n## Example Option 1: CI for mean response $\\mu_{Y|X^*}$\n\n**Find the 95% CI's for mean life expectancy for 60 cell phones per 100 people:**\n\n\n::: {.cell}\n\n:::\n\n\n```{=tex}\n\\begin{align}\n\\widehat{E}[Y|X^*] &\\pm t_{n-2}^* \\cdot SE_{\\widehat{E}[Y|X^*]}\\\\\n\n65.671 &\\pm 1.983 \\cdot \\widehat{\\sigma} \\sqrt{\\frac{1}{n} + \\frac{(X^* - \\bar{x})^2}{(n-1)s_X^2}}\\\\\n\n65.671 &\\pm 1.983 \\cdot 5.964 \\sqrt{\\frac{1}{105} + \\frac{(60 - 116.523)^2}{(105-1)34.565^2}}\\\\\n\n65.671 &\\pm 1.983 \\cdot 1.12\\\\\n\n65.671 &\\pm 2.22\\\\\n\n(63.45 &, 67.891)\n\\end{align}\n```\n\n## Example Option 2: CI for mean response $\\mu_{Y|X^*}$\n\n**Find the 95% CI's for mean life expectancy for 60 and 80 cell phones per 100 people, respectively.**\n\n-   Use the base R `predict()` function\n-   Requires specification of a `newdata` \"value\"\n    -   The `newdata` value is $X^*$\n    -   This has to be in the format of a data frame though\n    -   with column name identical to the predictor variable in the\n        model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata <- data.frame(cell_phones_100 = c(60, 80)) \nnewdata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  cell_phones_100\n1              60\n2              80\n```\n\n\n:::\n:::\n\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model1, \n        newdata=newdata, \n        interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 65.67080 63.45044 67.89117\n2 67.54757 65.86395 69.23118\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n::: fact\n::: fact-title\nInterpretation\n:::\n\n::: fact-cont\nWe are 95% confident that the **average** life expectancy for a country\nwith a 60 cell phones per 100 people will be between 63.45 and 67.89 years.\n:::\n:::\n:::\n:::\n\n## Poll Everywhere Question 5\n\n\n## Confidence bands for mean response $\\mu_{Y|X^*}$\n\n-   Often we plot the CI for many values of X, creating **confidence\n    bands**\n-   The confidence bands are what ggplot creates when we set `se = TRUE`\n    within `geom_smooth`\n-   Think about it: for what values of X are the confidence bands\n    (intervals) narrowest?\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\ngapm %>%\n  ggplot(\n    aes(\n      x=cell_phones_100, \n      y=life_exp\n      )\n    ) +\n  geom_point() +\n  geom_smooth(method = lm, se=TRUE) +\n  labs(\n    x = \"Cell phones per 100 people\",\n    y = \"Life expectancy (years)\",\n    title = \"Life expectancy vs. cell phones\"\n    )\n```\n\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-35-1.png){fig-align='center' width=1056}\n:::\n:::\n\n\n## Width of confidence bands for mean response $\\mu_{Y|X^*}$\n\n-   For what values of $X^*$ are the confidence bands (intervals)\n    narrowest? widest?\n\n```{=tex}\n\\begin{align}\n\\widehat{E}[Y|X^*] &\\pm t_{n-2}^* \\cdot SE_{\\widehat{E}[Y|X^*]}\\\\\n\\widehat{E}[Y|X^*] &\\pm t_{n-2}^* \\cdot \\widehat{\\sigma} \\sqrt{\\frac{1}{n} + \\frac{(X^* - \\bar{x})^2}{(n-1)s_x^2}}\n\\end{align}\n```\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-36-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Textbook readings\n\n- [Introduction to Regression Methods for Public Health Using R](https://bookdown.org/rwnahhas/RMPH/)\n  - [4.5 Interpreting p-values](https://bookdown.org/rwnahhas/RMPH/slr-pvalues.html#slr-pvalues)\n  - [4.6 Predictions from the model](https://bookdown.org/rwnahhas/RMPH/slr-prediction.html#slr-prediction)\n  - [4.7 Confidence intervals and prediction intervals](https://bookdown.org/rwnahhas/RMPH/slr-confints.html)\n  \n- [A Progressive Introduction to Linear Models](https://jfrench.github.io/LinearRegression/)\n  - Not really any good sections\n\n\n    \n\n",
    "supporting": [
      "04_SLR_Inf_Pred_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}