---
title: "Schedule"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 30px;
  color: #213c96;
  background-color: #fff;
  padding: 0px;
}
```

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

| Week | Date | Les-son | Topic | [TB 1](https://jfrench.github.io/LinearRegression/) | [TB 2](https://bookdown.org/rwnahhas/RMPH/) | Key Info | Slides HTML | Slides PDF | Slides Notes | Exit tix | Record-ing | Muddy Points |
|------|------|------|------|------|------|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 1 | `{r} w1d1 %>% format("%m/%d")` | 0 | Welcome |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Welcome/00_Welcome_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Welcome/00_Welcome.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Welcome/00_Welcome.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 1 | Review |  |  |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Review/01_Review.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Review/01_Review.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w1d2 %>% format("%m/%d")` | 2 | Data and File Management |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/02_Data_Management/02_Data_Management_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Data_Management/02_Data_Management.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Data_Management/02_Data_Management.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw0 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**HW 0 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1 %>% format("%m/%d")` | 3 | Simple Linear Regression | 3.1-3.2, 3.4 | 4.1-4.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/03_SLR/03_SLR_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_SLR/03_SLR.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/03_SLR/03_SLR.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w2d2 %>% format("%m/%d")` | 4 | SLR: Inference and Prediction | 3.3 | 4.3, 4.5-4.7 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r lab1 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Lab 1 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 3 | `{r} w3d1 %>% format("%m/%d")` |  | No Class, MLKJ Day |  |  |  |  |  |  |  |  |  |
|  | `{r} w3d2 %>% format("%m/%d")` | 5 | SLR: Categorical Covariates | 3.8-3.9 | 4.4 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/05_Cat_covariates/05_Cat_covariates_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_Cat_covariates/05_Cat_covariates.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/05_Cat_covariates/05_Cat_covariates.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | Lab 1 Discussion |  |  |  |  |  |  |  |  |  |
|  | [**`r hw1 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**HW 1 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 4 | `{r} w4d1 %>% format("%m/%d")` | 6 | SLR: More inference | 6.10 | NA | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/06_SLR_Eval/06_SLR_Eval_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/06_SLR_Eval/06_SLR_Eval.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/06_SLR_Eval/06_SLR_Eval.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w4d2 %>% format("%m/%d")` | 7 | SLR: Checking model assumptions | 5.1-5.2 | 5.13-5.17 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q1_open %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Quiz 1 opens \@ 3pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  | [**`r hw2 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**HW 2 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  | [**`r q1_close %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Quiz 1 closes \@11pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 5 | `{r} w5d1 %>% format("%m/%d")` | 8 | SLR: Diagnostics |  | 5.21-5.22, 5.25.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w5d2 %>% format("%m/%d")` | 9 | Multiple Linear Regression | 3.5-3.6, 4.1 | 5.1-5.2, 5.5-5.6 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/09_MLR_Intro/09_MLR_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_MLR_Intro/09_MLR_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/09_MLR_Intro/09_MLR_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r lab2 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Lab 2 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 6 | `{r} w6d1 %>% format("%m/%d")` | 10 | MLR: Using the F-test | 6.9-6.10 |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/10_MLR_F-test/10_MLR_F-test_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_MLR_F-test/10_MLR_F-test.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/10_MLR_F-test/10_MLR_F-test.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w6d2 %>% format("%m/%d")` |  | Lab 2 Review |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/11_Interactions_01/11_Interactions_01_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/Review-slides_HW-Labs/Review_HW_02_Lab_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/Review-slides_HW-Labs/Review_HW_02_Lab_02.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 11 | Interactions, Part 1 |  | 5.10 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Interactions_01/11_Interactions_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/11_Interactions_01/11_Interactions_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw3 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**HW 3 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 7 | `{r} w7d1 %>% format("%m/%d")` |  | No Class, President's Day |  |  |  |  |  |  |  |  |  |
|  | `{r} w7d2 %>% format("%m/%d")` | 12 | Interactions, Part 2 |  | 5.10 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/12_Interactions_02/12_Interactions_02_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Interactions_02/12_Interactions_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/12_Interactions_02/12_Interactions_02.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q2_open %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Quiz 2 opens \@ 3pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  | [**`r lab3 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Lab 3 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  | [**`r q2_close %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Quiz 2 closes \@ 11pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 8 | `{r} w8d1 %>% format("%m/%d")` |  | Lab 3 Discussion |  |  |  |  |  |  |  |  |  |
|  | `{r} w8d2 %>% format("%m/%d")` | 13 | Model Selection |  | 5.24 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/13_Model_selection/13_Model_selection_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/13_Model_selection/13_Model_selection.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/13_Model_selection/13_Model_selection.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw4 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**HW 4 due 11pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 9 | `{r} w9d1 %>% format("%m/%d")` | 14 | Purposeful Selection |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/14_Purposeful_selection/14_Purposeful_selection_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_Purposeful_selection/14_Purposeful_selection.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/14_Purposeful_selection/14_Purposeful_selection.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w9d2 %>% format("%m/%d")` | 15 | MLR: Diagnostics |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/15_MLR_Diagnostics/15_MLR_Diagnostics_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_MLR_Diagnostics/15_MLR_Diagnostics.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/15_MLR_Diagnostics/15_MLR_Diagnostics.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r lab4 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Lab 4 due 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 10 | `{r} w10d1 %>% format("%m/%d")` |  | Poster info / Lab 4 Discussion |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/16_Poster_help/16_Poster_help.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w10d2 %>% format("%m/%d")` |  | Catch-up day, virtual |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q3_open %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Quiz 3 opens \@ 3pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  | [**`r hw5 %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**HW 5 due 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  | [**`r q3_close %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Quiz 3 closes \@ 11pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 11 | `{r} w11d1 %>% format("%m/%d")` |  | Project Day!! |  |  |  |  |  |  |  |  |  |
|  | [**`r proj %>% format("%m/%d")`**]{style="color:#213c96;"} |  | [**Project due 11pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 30,8, 8, 6, 6, 6,6, 6\]"}
