---
title: "Key Info and Announcements"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements

- I mostly caught up on muddy points!

- Today is last day of new material

- Next class, I will cover some good ways to communicate and visualize results 
  - Will be helpful in final project!
  
- Class on Wednesday is INFORMAL
  - I will be here in person
  
- Classes on Monday (3/10) and Wednesday (3/12) will be virtual!
  - Basically like office hours for your project and final homework

- Lab 4 up!

- Homework 5 is up!

## Key Dates

- Lab 4 due 3/7
- HW 5 due 3/14
- Project poster due 3/17

## Last class

We went through the steps of purposeful selection:

0.  Exploratory data analysis

1.  Check unadjusted associations in simple linear regression

2.  Enter all covariates in model that meet some threshold

    -   [One textbook](https://onlinelibrary.wiley.com/doi/book/10.1002/9781118548387) suggest $p<0.2$ or $p<0.25$: great for modest sized datasets
    -   PLEASE keep in mind sample size in your study
    -   Can also use magnitude of association rather than, or along with, p-value

3.  Remove those that no longer reach some threshold

    -   Compare magnitude of associations to unadjusted version (univariable)

4.  Check scaling of continuous and coding of categorical covariates

5.  Check for interactions

6.  Assess model fit

    -   Model assumptions, diagnostics, overall fit