---
title: "Lab 3"
author: "Your name here!!"
subtitle: "BSTA 512/612"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    embed-resources: true
    number-sections: true
    number-depth: 4
---

```{r}
#| message: false

# PLEASE DO NOT REMOVE THIS CODE CHUNK!!!
### ADD YOUR LIBRARIES HERE!!! ####

library(tidyverse)
library(gtsummary)
library(here)
```

## Lab activities

**If you did not save your dataset in Lab 2:** Before starting this lab, you should go back to Lab 2, save a new `.rda` file that contains all the new variables from that Lab. Then you can load it here!

::: callout-note
I have left it up to you to load the needed packages for this lab.
:::

### Restate research question

::: callout-important
#### Task

Please restate your research question below using the provided format (1 sentence). You can change the wording if you'd like, but please make sure it is still clear. It’s repetitive, but it helps me contextualize my feedback as I look through your lab.
:::

### Thinking about potential confounders and effect modifiers

::: callout-important
##### Task

For each variable, consider how each could alter the relationship between IAT score and your variable of interest (from your research question). For each covariate, explain how it might or might not change the relationship. You can add to the table below, write in bullets, or however you prefer to organize the information. 

Note: you can consider the race/ethnicity variables as a single "variable" since we are trying to capture the same demogrpahic measurement (race/ethnicity).
:::



| Variable name | Confounder, Effect modifier, or nothing? | Reasoning (1-2 sentences) |
|-----------------|-----------------------------|-----------------------------|
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |
|               |                                          |                           |

### Continuing data exploration

#### Bivariate exploration

::: callout-important
##### Task

For each variable outside of your research question, create the appropriate plot to visualize the relationship between IAT score and the variable. Comment if there is an obvious trend or not.
:::

#### Multivariate exploration

::: callout-important
##### Task

Create the appropriate plot to visualize the relationship between IAT score, your main variable (in research question), and the variable identified in your subquestion. Comment whether you can determine anything from the plot or not. If you can, is there any indication that the variable is a confounder or effect modifier?
:::


### Fit a multiple linear regression model

::: callout-important
#### Task

Fit a model with you variable of interest (the one in the research question), the variable in your research subquestion, and 1 other covariate. This will not necessarily be your final model, but we can construct interpretations and code that will be useful in your final model. 
:::

### Interpret the coefficient estimate(s) for your main covariate

::: callout-important
#### Task

Interpret the estimated coefficents for the covariate from your research question. Make sure to include the 95% confidence intervals and what other variables you adjusted for. 
:::
