---
title: "Key Info and Announcements"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements
- Questions from exit tickets:
  - Is the Project Day mandatory? YES
  - Would it be possible for those of us in 612 to get more information on what is required for the readings that are part of our grade?
    - Yes! I will email you all shortly!

- New to R? Check out [my old class site](https://nwakim.github.io/F24_EPI_525/schedule.html)
  - Video recordings will be in Student folder
  
- MPH Student Focus Group
  - From the principal investigator, Seth Igarta: As the Professional and Career Development Specialist at OHSU, I am seeking current Master of Public Health (MPH) students to participate in a focus group study titled Your MPH, Your Voice. The purpose of this study is to understand the MPH student career preparation experience and how students describe their needs for public health careers. Participants will help shape future student success programming and services in the School of Public Health.
  - Participation in this study involves:
    - A time commitment of about 60 minutes between January 20-23
    - Zoom virtual attendance or in-person attendance at the Vanport Building on 1810 SW 5th Ave in Portland, OR.
    - **A $20 gift card to Ovation Coffee & Tea for participation.**
  - [Click here to sign up!](https://urldefense.com/v3/__https:/forms.gle/TMxWy9poRmySC2Y47__;!!Mi0JBg!KFwLgbCS6Utp1_DHZglX5RSNielzIYhUdKtzdFecHSBVSUkDScVYvR0uRqRXvbS-14QtQOGOM8liCN3He9KaYqUIrnc$) For more information about this study, please contact the principal investigator, Seth Igarta, by email at <igarta@ohsu.edu>
 

- Anything else?

## Key Dates
- Homework 0 due this Thursday at 11pm
  - Let me know if you have issues with turning it in on Sakai
- Lab 1 due next Thursday at 11pm
  - I am double checking that the lab is updated correctly!

