{
  "hash": "11ab48aa62762b94bed680e8f34343c1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 12: Interactions, Part 2\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"2026-02-25\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 12: Interactions 2\"\n    highlight-style: ayu\n    html-math-method: mathjax\nexecute:\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n\n# Learning Objectives\n\n**Last time:**\n\n1.  Define confounders and effect modifiers, and how they interact with the main relationship we model.\n2.  Interpret the interaction component of a model with **a binary categorical covariate and continuous covariate**, and how the main variable's effect changes.\n3.  Interpret the interaction component of a model with **a multi-level categorical covariate and continuous covariate**, and how the main variable's effect changes.\n\n**This time:**\n\n4.  Interpret the interaction component of a model with **two categorical covariates**, and how the main variable's effect changes.\n5.  Interpret the interaction component of a model with **two continuous covariates**, and how the main variable's effect changes.\n6. Report results for a best-fit line (with confidence intervals) at different levels of an effect measure modifier\n\n# Learning Objectives\n\n**Last time:**\n\n1.  Define confounders and effect modifiers, and how they interact with the main relationship we model.\n2.  Interpret the interaction component of a model with **a binary categorical covariate and continuous covariate**, and how the main variable's effect changes.\n3.  Interpret the interaction component of a model with **a multi-level categorical covariate and continuous covariate**, and how the main variable's effect changes.\n\n**This time:**\n\n::: lob\n4.  Interpret the interaction component of a model with **two categorical covariates**, and how the main variable's effect changes.\n:::\n\n5.  Interpret the interaction component of a model with **two continuous covariates**, and how the main variable's effect changes.\n6. Report results for a best-fit line (with confidence intervals) at different levels of an effect measure modifier\n\n## Do we think income level can be an effect modifier for freedom status?\n\n::: columns\n::: column\n-   Taking a break from cell phones to demonstrate interactions for two categorical variables\n\n-   We can start by visualizing the relationship between life expectancy and freedom status *by income level*\n\n-   Questions of interest: Does the effect of freedom status on life expectancy differ depending on income level?\n\n    -   This is the same as: Is income level an effect modifier for freedom status?\n\n-   Let's run an interaction model to see!\n:::\n\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12_Interactions_02_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=864}\n:::\n:::\n\n:::\n:::\n\n## Model with interaction between a *multi-level categorical and binary variables*\n\nModel we are fitting:\n\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\beta_2 I(\\text{FS} = \\text{PF}) + \\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\beta_4 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + \\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F}) + \\epsilon \\end{aligned}$$\n\n-   $LE$ as life expectancy\n-   $I(\\text{high income})$ as indicator of high income\n-   $I(\\text{FS} = \\text{PF})$ and $I(\\text{FS} = \\text{F})$ as the indicator for each freedom status\n\nIn R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_wr_inc = gapm %>% \n  lm(formula = life_exp ~ income_level_2 + freedom_status + income_level_2*freedom_status)\nm_int_wr_inc = gapm %>% \n  lm(formula = life_exp ~ income_level_2*freedom_status)\n```\n:::\n\n\n## Displaying the regression table and writing fitted regression equation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_m_int_wr_inc = tidy(m_int_wr_inc, conf.int=T)\ntidy_m_int_wr_inc %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"suqqdsmqjn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#suqqdsmqjn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#suqqdsmqjn thead, #suqqdsmqjn tbody, #suqqdsmqjn tfoot, #suqqdsmqjn tr, #suqqdsmqjn td, #suqqdsmqjn th {\n  border-style: none;\n}\n\n#suqqdsmqjn p {\n  margin: 0;\n  padding: 0;\n}\n\n#suqqdsmqjn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#suqqdsmqjn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#suqqdsmqjn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#suqqdsmqjn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#suqqdsmqjn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#suqqdsmqjn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#suqqdsmqjn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#suqqdsmqjn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#suqqdsmqjn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#suqqdsmqjn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#suqqdsmqjn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#suqqdsmqjn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#suqqdsmqjn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#suqqdsmqjn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#suqqdsmqjn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#suqqdsmqjn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#suqqdsmqjn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#suqqdsmqjn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#suqqdsmqjn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#suqqdsmqjn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#suqqdsmqjn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#suqqdsmqjn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#suqqdsmqjn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#suqqdsmqjn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#suqqdsmqjn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#suqqdsmqjn .gt_left {\n  text-align: left;\n}\n\n#suqqdsmqjn .gt_center {\n  text-align: center;\n}\n\n#suqqdsmqjn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#suqqdsmqjn .gt_font_normal {\n  font-weight: normal;\n}\n\n#suqqdsmqjn .gt_font_bold {\n  font-weight: bold;\n}\n\n#suqqdsmqjn .gt_font_italic {\n  font-style: italic;\n}\n\n#suqqdsmqjn .gt_super {\n  font-size: 65%;\n}\n\n#suqqdsmqjn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#suqqdsmqjn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#suqqdsmqjn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#suqqdsmqjn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#suqqdsmqjn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#suqqdsmqjn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#suqqdsmqjn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#suqqdsmqjn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#suqqdsmqjn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">67.355</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.179</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">57.126</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">65.015</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">69.695</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_level_2Higher income</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">5.645</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.188</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.580</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.011</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.303</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">9.987</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">freedom_statusPF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.029</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.588</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.018</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.985</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−3.123</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">3.181</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">freedom_statusF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−5.665</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">3.404</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−1.664</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.099</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−12.419</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.089</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_level_2Higher income:freedom_statusPF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.633</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.595</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.553</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−3.813</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">7.078</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_level_2Higher income:freedom_statusF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">8.287</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">4.026</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.058</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.042</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.299</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">16.275</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\widehat\\beta_4 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + \\widehat\\beta_5\\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F})\\\\\n\\widehat{LE} = & 67.35 + 5.64 \\cdot I(\\text{high income}) + 0.03 \\cdot I(\\text{FS} = \\text{PF})  -5.67 \\cdot I(\\text{FS} = \\text{F}) + \\\\ & 1.63 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + 8.29\\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F})\\\\\n\\end{aligned}$$\n\n## Poll Everywhere Question 4\n\n::: columns\n::: {.column width=\"60%\"}\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12_Interactions_02_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n:::\n\n\n## Comparing fitted regression *means* for each freedom status\n\n$$\\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\widehat\\beta_4 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + \\widehat\\beta_5\\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F})\\\\\n\\widehat{LE} = & 67.35 + 5.64 \\cdot I(\\text{high income}) + 0.03 \\cdot I(\\text{FS} = \\text{PF})  -5.67 \\cdot I(\\text{FS} = \\text{F}) + \\\\ & 1.63 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + 8.29\\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F})\n\\end{aligned}$$\n\n::::::::::::::::::: columns\n:::::: {.column width=\"33%\"}\n::::: proof1\n::: proof-title\nNot free\n:::\n\n::: proof-cont\n$$\\begin{aligned} \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\\\ \n& \\widehat\\beta_2 \\cdot 0 + \\widehat\\beta_3 \\cdot 0  + \\\\ \n& \\widehat\\beta_4 \\cdot I(\\text{high income}) \\cdot 0 + \\\\\n& \\widehat\\beta_5\\cdot I(\\text{high income}) \\cdot 0 \\\\ \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income})\n\\end{aligned}$$\n:::\n:::::\n::::::\n\n:::::: {.column width=\"33%\"}\n::::: fact\n::: fact-title\nPartly free\n:::\n\n::: fact-cont\n$$\\begin{aligned} \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\\\ \n& \\widehat\\beta_2 \\cdot 1 + \\widehat\\beta_3 \\cdot 0  + \\\\ \n& \\widehat\\beta_4 \\cdot I(\\text{high income}) \\cdot 1 + \\\\\n& \\widehat\\beta_5\\cdot I(\\text{high income}) \\cdot 0 \\\\ \n\\widehat{LE} = & \\big(\\widehat\\beta_0 + \\widehat\\beta_2 \\big) + \\\\ & \\big(\\widehat\\beta_1 + \\widehat\\beta_4  \\big) I(\\text{high income}) \\\\\n\\end{aligned}$$\n:::\n:::::\n::::::\n\n\n:::::: {.column width=\"33%\"}\n::::: definition\n::: def-title\nFree\n:::\n\n::: def-cont\n$$\\begin{aligned} \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\\\ \n& \\widehat\\beta_2 \\cdot 1 + \\widehat\\beta_3 \\cdot 0  + \\\\ \n& \\widehat\\beta_4 \\cdot I(\\text{high income}) \\cdot 1 + \\\\\n& \\widehat\\beta_5\\cdot I(\\text{high income}) \\cdot 0 \\\\ \n\\widehat{LE} = & \\big(\\widehat\\beta_0 + \\widehat\\beta_3 \\big) + \\\\ & \\big(\\widehat\\beta_1 + \\widehat\\beta_5  \\big) I(\\text{high income}) \\\\\n\\end{aligned}$$\n:::\n:::::\n::::::\n:::::::::::::::::::\n## Comparing fitted regression *means* for each income level {.smaller}\n\n$$\\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\widehat\\beta_4 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + \\widehat\\beta_5\\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F})\\\\\n\\widehat{LE} = & 67.35 + 5.64 \\cdot I(\\text{high income}) + 0.03 \\cdot I(\\text{FS} = \\text{PF})  -5.67 \\cdot I(\\text{FS} = \\text{F}) + \\\\ & 1.63 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + 8.29\\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F})\n\\end{aligned}$$\n\n::: columns\n::: column\n::: proof1\n::: proof-title\nFor lower income countries: $I(\\text{high income})=0$\n:::\n\n::: proof-cont\n$$ \\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 0 + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\widehat\\beta_4 \\cdot 0 \\cdot I(\\text{FS} = \\text{PF}) + \\widehat\\beta_5 \\cdot 0 \\cdot I(\\text{FS} = \\text{F})\\\\\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F})  \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: column\n::: fact\n::: fact-title\nFor higher income countries: $I(\\text{high income}) =1$\n:::\n\n::: fact-cont\n$$ \\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 1 + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\widehat\\beta_4 \\cdot 1 \\cdot I(\\text{FS} = \\text{PF}) + \\widehat\\beta_5 \\cdot 1 \\cdot I(\\text{FS} = \\text{F})\\\\\n\\widehat{LE} = & \\big(\\widehat\\beta_0 + \\widehat\\beta_1 \\big) + \\big(\\widehat\\beta_2 + \\widehat\\beta_4 \\big) I(\\text{FS} = \\text{PF}) + \\\\ & \\big(\\widehat\\beta_3 + \\widehat\\beta_5 \\big) I(\\text{FS} = \\text{F})  \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n- Example interpretation: The America's effect on mean life expectancy increases $\\widehat{\\beta}_5$ comparing high income to low income countries.\n\n## Let's take a look back at the plot\n\n::: columns\n::: {.column width=\"50%\"}\n::: proof1\n::: proof-title\nFor lower income countries: $I(\\text{high income}) =0$\n:::\n\n::: proof-cont\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F}) \\\\\n\\end{aligned}$$\n:::\n:::\n\n::: fact\n::: fact-title\nFor higher income countries: $I(\\text{high income}) =1$\n:::\n\n::: fact-cont\n$$ \\begin{aligned}\n\\widehat{LE} = & \\big(\\widehat\\beta_0 + \\widehat\\beta_1 \\big) + \\big(\\widehat\\beta_2 + \\widehat\\beta_4 \\big) I(\\text{FS} = \\text{PF}) + \\\\ & \\big(\\widehat\\beta_3 + \\widehat\\beta_5 \\big) I(\\text{FS} = \\text{F}) \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12_Interactions_02_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=816}\n:::\n:::\n\n:::\n:::\n\n## Interpretation for interaction between two categorical variables\n\n$$ \\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 1 + \\widehat\\beta_2 I(\\text{FS} = \\text{PF}) + \\widehat\\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\widehat\\beta_4 \\cdot 1 \\cdot I(\\text{FS} = \\text{PF}) + \\widehat\\beta_5 \\cdot 1 \\cdot I(\\text{FS} = \\text{F})\\\\\n\\widehat{LE} = & \\bigg[\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{high income})\\bigg]  + \\bigg[\\widehat\\beta_2 + \\widehat\\beta_4 \\cdot I(\\text{high income})\\bigg] I(\\text{FS} = \\text{PF}) + \\\\ & \\bigg[\\widehat\\beta_3 + \\widehat\\beta_5 \\cdot I(\\text{high income})\\bigg]  I(\\text{FS} = \\text{F}) \\\\\n\\end{aligned}$$\n\n-   Interpretation:\n    -   $\\widehat\\beta_1$ = mean change in life expectancy comparing high income to low income countries, for countries/territories that are [**not free**]{style=\"color: #FF8021\"}\n    -   $\\widehat\\beta_4$ = mean change in life expectancy comparing high income to low income countries, for countries/territories that are [**partly free**]{style=\"color: #34AC8B\"}\n    -   $\\widehat\\beta_5$ = mean change in life expectancy comparing high income to low income countries, for countries/territories that are [**free**]{style=\"color: #4FADF3\"}\n\n## Test interaction between two categorical variables (1/2)\n\n-   We run an F-test for a group of coefficients ($\\beta_4$, $\\beta_5$) in the below model (see lesson 9)\n\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\beta_2 I(\\text{FS} = \\text{PF}) + \\beta_3 I(\\text{FS} = \\text{F})  + \\\\ & \\beta_4 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + \\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F}) + \\epsilon \\end{aligned}$$\n\n::: columns\n::: {.column width=\"42%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_4= \\beta_5 =0$\n:::\n:::\n:::\n\n::: {.column width=\"58%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_4\\neq0$ and/or $\\beta_5\\neq0$ \n:::\n:::\n:::\n:::\n\n::: columns\n::: {.column width=\"42%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\\\\n&\\beta_2 I(\\text{FS} = \\text{PF}) + \\beta_3 I(\\text{FS} = \\text{F}) + \\\\\n& \\epsilon \\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"58%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\beta_2 I(\\text{FS} = \\text{PF}) + \\\\ & \\beta_3 I(\\text{FS} = \\text{F})  + \\beta_4 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{PF}) + \\\\ & \\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{FS} = \\text{F}) + \\epsilon \\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Test interaction between two categorical variables (2/2)\n\n-   Fit the reduced and full model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_wr_inc_red = gapm %>% \n  lm(formula = life_exp ~ income_level_2 + freedom_status)\nm_int_wr_inc_full = gapm %>% \n  lm(formula = life_exp ~ income_level_2*freedom_status)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Display the ANOVA table with F-statistic and p-value\"}\nanova_table = anova(m_int_wr_inc_red, m_int_wr_inc_full)\nanova_table %>% tidy() %>% gt() %>% tab_options(table.font.size = 35) %>% \n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ciiisklhnp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ciiisklhnp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ciiisklhnp thead, #ciiisklhnp tbody, #ciiisklhnp tfoot, #ciiisklhnp tr, #ciiisklhnp td, #ciiisklhnp th {\n  border-style: none;\n}\n\n#ciiisklhnp p {\n  margin: 0;\n  padding: 0;\n}\n\n#ciiisklhnp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ciiisklhnp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ciiisklhnp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ciiisklhnp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ciiisklhnp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ciiisklhnp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ciiisklhnp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ciiisklhnp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ciiisklhnp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ciiisklhnp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ciiisklhnp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ciiisklhnp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ciiisklhnp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ciiisklhnp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ciiisklhnp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ciiisklhnp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ciiisklhnp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ciiisklhnp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ciiisklhnp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ciiisklhnp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ciiisklhnp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ciiisklhnp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ciiisklhnp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ciiisklhnp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ciiisklhnp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ciiisklhnp .gt_left {\n  text-align: left;\n}\n\n#ciiisklhnp .gt_center {\n  text-align: center;\n}\n\n#ciiisklhnp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ciiisklhnp .gt_font_normal {\n  font-weight: normal;\n}\n\n#ciiisklhnp .gt_font_bold {\n  font-weight: bold;\n}\n\n#ciiisklhnp .gt_font_italic {\n  font-style: italic;\n}\n\n#ciiisklhnp .gt_super {\n  font-size: 65%;\n}\n\n#ciiisklhnp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ciiisklhnp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ciiisklhnp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ciiisklhnp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ciiisklhnp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ciiisklhnp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ciiisklhnp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ciiisklhnp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ciiisklhnp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ income_level_2 + freedom_status</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">101.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,160.771</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ income_level_2 * freedom_status</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">99.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,027.855</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">132.915</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.173</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.119</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n-   **Conclusion:** There is not a significant interaction between freedom status and income level (p = 0.119). \n\n# Learning Objectives\n\n**Last time:**\n\n1.  Define confounders and effect modifiers, and how they interact with the main relationship we model.\n2.  Interpret the interaction component of a model with **a binary categorical covariate and continuous covariate**, and how the main variable's effect changes.\n3.  Interpret the interaction component of a model with **a multi-level categorical covariate and continuous covariate**, and how the main variable's effect changes.\n\n**This time:**\n\n4.  Interpret the interaction component of a model with **two categorical covariates**, and how the main variable's effect changes.\n\n::: lob\n5.  Interpret the interaction component of a model with **two continuous covariates**, and how the main variable's effect changes.\n:::\n\n6. Report results for a best-fit line (with confidence intervals) at different levels of an effect measure modifier\n\n## Do we think vaccination rate is an effect modifier for cell phones?\n\n::: columns\n::: {.column width=\"40%\"}\n-   We can start by visualizing the relationship between life expectancy and cell phones *by vaccination rate*\n\n-   Questions of interest: Does the effect of cell phones on life expectancy differ depending on vaccination rate?\n\n    -   This is the same as: Is vaccination rate is an effect modifier for cell phones? Is vaccination rate an effect modifier of the association between life expectancy and cell phones?\n\n-   Let's run an interaction model to see!\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"girafe html-widget html-fill-item\" id=\"htmlwidget-b3f54f342008198869e7\" style=\"width:576px;height:384px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b3f54f342008198869e7\">{\"x\":{\"html\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='graphics-document' id='svg_d0389b9b09825998' viewBox='0 0 432 288'>\\n <defs id='svg_d0389b9b09825998_defs'>\\n  <clipPath id='svg_d0389b9b09825998_c1'>\\n   <rect x='0' y='0' width='432' height='288'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_d0389b9b09825998_c2'>\\n   <rect x='33.27' y='5.48' width='329.14' height='250.79'/>\\n  <\\/clipPath>\\n <\\/defs>\\n <g id='svg_d0389b9b09825998_rootg' class='ggiraph-svg-rootg'>\\n  <g clip-path='url(#svg_d0389b9b09825998_c1)'>\\n   <rect x='0' y='0' width='432' height='288' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\\n   <rect x='0' y='0' width='432' height='288' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_d0389b9b09825998_c2)'>\\n   <rect x='33.27' y='5.48' width='329.14' height='250.79' fill='#EBEBEB' fill-opacity='1' stroke='none'/>\\n   <polyline points='33.27,216.42 362.40,216.42' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,150.41 362.40,150.41' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,84.40 362.40,84.40' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,18.40 362.40,18.40' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='39.92,256.27 39.92,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='123.03,256.27 123.03,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='206.15,256.27 206.15,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='289.26,256.27 289.26,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,249.42 362.40,249.42' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,183.41 362.40,183.41' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,117.41 362.40,117.41' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,51.40 362.40,51.40' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='81.47,256.27 81.47,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='164.59,256.27 164.59,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='247.70,256.27 247.70,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='330.82,256.27 330.82,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <circle id='svg_d0389b9b09825998_e1' cx='91.89' cy='165.99' r='1.47pt' fill='#214668' fill-opacity='1' stroke='#214668' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='1' title='1&amp;lt;br/&amp;gt;cell_phones_100=56.2655&amp;lt;br/&amp;gt;life_exp=62.64'/>\\n   <circle id='svg_d0389b9b09825998_e2' cx='161.92' cy='77.34' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='2' title='2&amp;lt;br/&amp;gt;cell_phones_100=98.395&amp;lt;br/&amp;gt;life_exp=76.07'/>\\n   <circle id='svg_d0389b9b09825998_e3' cx='323.55' cy='94.9' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='3' title='3&amp;lt;br/&amp;gt;cell_phones_100=195.625&amp;lt;br/&amp;gt;life_exp=73.41'/>\\n   <circle id='svg_d0389b9b09825998_e4' cx='216.93' cy='81.96' r='1.47pt' fill='#4B9BDA' fill-opacity='1' stroke='#4B9BDA' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='4' title='4&amp;lt;br/&amp;gt;cell_phones_100=131.484&amp;lt;br/&amp;gt;life_exp=75.37'/>\\n   <circle id='svg_d0389b9b09825998_e5' cx='215.36' cy='93.25' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='5' title='5&amp;lt;br/&amp;gt;cell_phones_100=130.54&amp;lt;br/&amp;gt;life_exp=73.66'/>\\n   <circle id='svg_d0389b9b09825998_e6' cx='177.07' cy='108.36' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='6' title='6&amp;lt;br/&amp;gt;cell_phones_100=107.506&amp;lt;br/&amp;gt;life_exp=71.37'/>\\n   <circle id='svg_d0389b9b09825998_e7' cx='174.14' cy='157.28' r='1.47pt' fill='#4289C2' fill-opacity='1' stroke='#4289C2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='7' title='7&amp;lt;br/&amp;gt;cell_phones_100=105.745&amp;lt;br/&amp;gt;life_exp=63.96'/>\\n   <circle id='svg_d0389b9b09825998_e8' cx='180.99' cy='81.3' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='8' title='8&amp;lt;br/&amp;gt;cell_phones_100=109.867&amp;lt;br/&amp;gt;life_exp=75.47'/>\\n   <circle id='svg_d0389b9b09825998_e9' cx='192.32' cy='118.07' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='9' title='9&amp;lt;br/&amp;gt;cell_phones_100=116.679&amp;lt;br/&amp;gt;life_exp=69.9'/>\\n   <circle id='svg_d0389b9b09825998_e10' cx='196.08' cy='84.27' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='10' title='10&amp;lt;br/&amp;gt;cell_phones_100=118.944&amp;lt;br/&amp;gt;life_exp=75.02'/>\\n   <circle id='svg_d0389b9b09825998_e11' cx='167.2' cy='124.54' r='1.47pt' fill='#2C5D86' fill-opacity='1' stroke='#2C5D86' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='11' title='11&amp;lt;br/&amp;gt;cell_phones_100=101.572&amp;lt;br/&amp;gt;life_exp=68.92'/>\\n   <circle id='svg_d0389b9b09825998_e12' cx='166.66' cy='91.53' r='1.47pt' fill='#4186BD' fill-opacity='1' stroke='#4186BD' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='12' title='12&amp;lt;br/&amp;gt;cell_phones_100=101.245&amp;lt;br/&amp;gt;life_exp=73.92'/>\\n   <circle id='svg_d0389b9b09825998_e13' cx='294.59' cy='165.79' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='13' title='13&amp;lt;br/&amp;gt;cell_phones_100=178.205&amp;lt;br/&amp;gt;life_exp=62.67'/>\\n   <circle id='svg_d0389b9b09825998_e14' cx='222.96' cy='55.69' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='14' title='14&amp;lt;br/&amp;gt;cell_phones_100=135.114&amp;lt;br/&amp;gt;life_exp=79.35'/>\\n   <circle id='svg_d0389b9b09825998_e15' cx='266.38' cy='158.2' r='1.47pt' fill='#3B7BAF' fill-opacity='1' stroke='#3B7BAF' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='15' title='15&amp;lt;br/&amp;gt;cell_phones_100=161.232&amp;lt;br/&amp;gt;life_exp=63.82'/>\\n   <circle id='svg_d0389b9b09825998_e16' cx='147.68' cy='165.53' r='1.47pt' fill='#244D70' fill-opacity='1' stroke='#244D70' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='16' title='16&amp;lt;br/&amp;gt;cell_phones_100=89.8274&amp;lt;br/&amp;gt;life_exp=62.71'/>\\n   <circle id='svg_d0389b9b09825998_e17' cx='79.28' cy='153.91' r='1.47pt' fill='#2E608A' fill-opacity='1' stroke='#2E608A' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='17' title='17&amp;lt;br/&amp;gt;cell_phones_100=48.6774&amp;lt;br/&amp;gt;life_exp=64.47'/>\\n   <circle id='svg_d0389b9b09825998_e18' cx='258' cy='71.47' r='1.47pt' fill='#4186BD' fill-opacity='1' stroke='#4186BD' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='18' title='18&amp;lt;br/&amp;gt;cell_phones_100=156.195&amp;lt;br/&amp;gt;life_exp=76.96'/>\\n   <circle id='svg_d0389b9b09825998_e19' cx='256' cy='64.93' r='1.47pt' fill='#4D9FDE' fill-opacity='1' stroke='#4D9FDE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='19' title='19&amp;lt;br/&amp;gt;cell_phones_100=154.989&amp;lt;br/&amp;gt;life_exp=77.95'/>\\n   <circle id='svg_d0389b9b09825998_e20' cx='211.31' cy='62.36' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='20' title='20&amp;lt;br/&amp;gt;cell_phones_100=128.105&amp;lt;br/&amp;gt;life_exp=78.34'/>\\n   <circle id='svg_d0389b9b09825998_e21' cx='148.59' cy='92.46' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='21' title='21&amp;lt;br/&amp;gt;cell_phones_100=90.376&amp;lt;br/&amp;gt;life_exp=73.78'/>\\n   <circle id='svg_d0389b9b09825998_e22' cx='177.53' cy='72.19' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='22' title='22&amp;lt;br/&amp;gt;cell_phones_100=107.787&amp;lt;br/&amp;gt;life_exp=76.85'/>\\n   <circle id='svg_d0389b9b09825998_e23' cx='161.48' cy='71.4' r='1.47pt' fill='#2C5D86' fill-opacity='1' stroke='#2C5D86' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='23' title='23&amp;lt;br/&amp;gt;cell_phones_100=98.1309&amp;lt;br/&amp;gt;life_exp=76.97'/>\\n   <circle id='svg_d0389b9b09825998_e24' cx='149.1' cy='118.86' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='24' title='24&amp;lt;br/&amp;gt;cell_phones_100=90.6795&amp;lt;br/&amp;gt;life_exp=69.78'/>\\n   <circle id='svg_d0389b9b09825998_e25' cx='251.48' cy='61.1' r='1.47pt' fill='#448DC6' fill-opacity='1' stroke='#448DC6' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='25' title='25&amp;lt;br/&amp;gt;cell_phones_100=152.271&amp;lt;br/&amp;gt;life_exp=78.53'/>\\n   <circle id='svg_d0389b9b09825998_e26' cx='93.05' cy='126.38' r='1.47pt' fill='#1F4364' fill-opacity='1' stroke='#1F4364' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='26' title='26&amp;lt;br/&amp;gt;cell_phones_100=56.9643&amp;lt;br/&amp;gt;life_exp=68.64'/>\\n   <circle id='svg_d0389b9b09825998_e27' cx='211.17' cy='35.89' r='1.47pt' fill='#4B9BDA' fill-opacity='1' stroke='#4B9BDA' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='27' title='27&amp;lt;br/&amp;gt;cell_phones_100=128.023&amp;lt;br/&amp;gt;life_exp=82.35'/>\\n   <circle id='svg_d0389b9b09825998_e28' cx='191.1' cy='29.16' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='28' title='28&amp;lt;br/&amp;gt;cell_phones_100=115.951&amp;lt;br/&amp;gt;life_exp=83.37'/>\\n   <circle id='svg_d0389b9b09825998_e29' cx='203.21' cy='137.94' r='1.47pt' fill='#316793' fill-opacity='1' stroke='#316793' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='29' title='29&amp;lt;br/&amp;gt;cell_phones_100=123.233&amp;lt;br/&amp;gt;life_exp=66.89'/>\\n   <circle id='svg_d0389b9b09825998_e30' cx='254.38' cy='107.37' r='1.47pt' fill='#4D9FDE' fill-opacity='1' stroke='#4D9FDE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='30' title='30&amp;lt;br/&amp;gt;cell_phones_100=154.014&amp;lt;br/&amp;gt;life_exp=71.52'/>\\n   <circle id='svg_d0389b9b09825998_e31' cx='199.17' cy='147.11' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='31' title='31&amp;lt;br/&amp;gt;cell_phones_100=120.803&amp;lt;br/&amp;gt;life_exp=65.5'/>\\n   <circle id='svg_d0389b9b09825998_e32' cx='179.36' cy='180.18' r='1.47pt' fill='#275379' fill-opacity='1' stroke='#275379' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='32' title='32&amp;lt;br/&amp;gt;cell_phones_100=108.885&amp;lt;br/&amp;gt;life_exp=60.49'/>\\n   <circle id='svg_d0389b9b09825998_e33' cx='175.86' cy='144.8' r='1.47pt' fill='#3874A6' fill-opacity='1' stroke='#3874A6' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='33' title='33&amp;lt;br/&amp;gt;cell_phones_100=106.782&amp;lt;br/&amp;gt;life_exp=65.85'/>\\n   <circle id='svg_d0389b9b09825998_e34' cx='189.78' cy='129.55' r='1.47pt' fill='#3F82B8' fill-opacity='1' stroke='#3F82B8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='34' title='34&amp;lt;br/&amp;gt;cell_phones_100=115.156&amp;lt;br/&amp;gt;life_exp=68.16'/>\\n   <circle id='svg_d0389b9b09825998_e35' cx='124.45' cy='117.8' r='1.47pt' fill='#336A98' fill-opacity='1' stroke='#336A98' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='35' title='35&amp;lt;br/&amp;gt;cell_phones_100=75.8551&amp;lt;br/&amp;gt;life_exp=69.94'/>\\n   <circle id='svg_d0389b9b09825998_e36' cx='174.22' cy='83.68' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='36' title='36&amp;lt;br/&amp;gt;cell_phones_100=105.794&amp;lt;br/&amp;gt;life_exp=75.11'/>\\n   <circle id='svg_d0389b9b09825998_e37' cx='202.61' cy='123.41' r='1.47pt' fill='#4997D5' fill-opacity='1' stroke='#4997D5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='37' title='37&amp;lt;br/&amp;gt;cell_phones_100=122.873&amp;lt;br/&amp;gt;life_exp=69.09'/>\\n   <circle id='svg_d0389b9b09825998_e38' cx='131.65' cy='133.18' r='1.47pt' fill='#4D9FDE' fill-opacity='1' stroke='#4D9FDE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='38' title='38&amp;lt;br/&amp;gt;cell_phones_100=80.1818&amp;lt;br/&amp;gt;life_exp=67.61'/>\\n   <circle id='svg_d0389b9b09825998_e39' cx='182.22' cy='35.03' r='1.47pt' fill='#4997D5' fill-opacity='1' stroke='#4997D5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='39' title='39&amp;lt;br/&amp;gt;cell_phones_100=110.609&amp;lt;br/&amp;gt;life_exp=82.48'/>\\n   <circle id='svg_d0389b9b09825998_e40' cx='268.84' cy='76.62' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='40' title='40&amp;lt;br/&amp;gt;cell_phones_100=162.713&amp;lt;br/&amp;gt;life_exp=76.18'/>\\n   <circle id='svg_d0389b9b09825998_e41' cx='163.15' cy='97.47' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='41' title='41&amp;lt;br/&amp;gt;cell_phones_100=99.1324&amp;lt;br/&amp;gt;life_exp=73.02'/>\\n   <circle id='svg_d0389b9b09825998_e42' cx='174.17' cy='84.14' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='42' title='42&amp;lt;br/&amp;gt;cell_phones_100=105.762&amp;lt;br/&amp;gt;life_exp=75.04'/>\\n   <circle id='svg_d0389b9b09825998_e43' cx='110.97' cy='75.49' r='1.47pt' fill='#4894D0' fill-opacity='1' stroke='#4894D0' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='43' title='43&amp;lt;br/&amp;gt;cell_phones_100=67.7457&amp;lt;br/&amp;gt;life_exp=76.35'/>\\n   <circle id='svg_d0389b9b09825998_e44' cx='207.21' cy='118.4' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='44' title='44&amp;lt;br/&amp;gt;cell_phones_100=125.642&amp;lt;br/&amp;gt;life_exp=69.85'/>\\n   <circle id='svg_d0389b9b09825998_e45' cx='199.78' cy='146.65' r='1.47pt' fill='#4B9BDA' fill-opacity='1' stroke='#4B9BDA' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='45' title='45&amp;lt;br/&amp;gt;cell_phones_100=121.169&amp;lt;br/&amp;gt;life_exp=65.57'/>\\n   <circle id='svg_d0389b9b09825998_e46' cx='176.1' cy='99.92' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='46' title='46&amp;lt;br/&amp;gt;cell_phones_100=106.926&amp;lt;br/&amp;gt;life_exp=72.65'/>\\n   <circle id='svg_d0389b9b09825998_e47' cx='186.85' cy='123.22' r='1.47pt' fill='#4D9FDE' fill-opacity='1' stroke='#4D9FDE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='47' title='47&amp;lt;br/&amp;gt;cell_phones_100=113.392&amp;lt;br/&amp;gt;life_exp=69.12'/>\\n   <circle id='svg_d0389b9b09825998_e48' cx='278.21' cy='37.8' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='48' title='48&amp;lt;br/&amp;gt;cell_phones_100=168.35&amp;lt;br/&amp;gt;life_exp=82.06'/>\\n   <circle id='svg_d0389b9b09825998_e49' cx='103.67' cy='118.46' r='1.47pt' fill='#448DC6' fill-opacity='1' stroke='#448DC6' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='49' title='49&amp;lt;br/&amp;gt;cell_phones_100=63.3546&amp;lt;br/&amp;gt;life_exp=69.84'/>\\n   <circle id='svg_d0389b9b09825998_e50' cx='51.66' cy='143.08' r='1.47pt' fill='#316793' fill-opacity='1' stroke='#316793' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='50' title='50&amp;lt;br/&amp;gt;cell_phones_100=32.0639&amp;lt;br/&amp;gt;life_exp=66.11'/>\\n   <circle id='svg_d0389b9b09825998_e51' cx='250.58' cy='65.2' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='51' title='51&amp;lt;br/&amp;gt;cell_phones_100=151.727&amp;lt;br/&amp;gt;life_exp=77.91'/>\\n   <circle id='svg_d0389b9b09825998_e52' cx='111.56' cy='244.87' r='1.47pt' fill='#3F82B8' fill-opacity='1' stroke='#3F82B8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='52' title='52&amp;lt;br/&amp;gt;cell_phones_100=68.1001&amp;lt;br/&amp;gt;life_exp=50.69'/>\\n   <circle id='svg_d0389b9b09825998_e53' cx='224.16' cy='88.89' r='1.47pt' fill='#4997D5' fill-opacity='1' stroke='#4997D5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='53' title='53&amp;lt;br/&amp;gt;cell_phones_100=135.834&amp;lt;br/&amp;gt;life_exp=74.32'/>\\n   <circle id='svg_d0389b9b09825998_e54' cx='234.19' cy='90.74' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='54' title='54&amp;lt;br/&amp;gt;cell_phones_100=141.87&amp;lt;br/&amp;gt;life_exp=74.04'/>\\n   <circle id='svg_d0389b9b09825998_e55' cx='226.4' cy='104.87' r='1.47pt' fill='#4997D5' fill-opacity='1' stroke='#4997D5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='55' title='55&amp;lt;br/&amp;gt;cell_phones_100=137.183&amp;lt;br/&amp;gt;life_exp=71.9'/>\\n   <circle id='svg_d0389b9b09825998_e56' cx='105.99' cy='151.47' r='1.47pt' fill='#18344F' fill-opacity='1' stroke='#18344F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='56' title='56&amp;lt;br/&amp;gt;cell_phones_100=64.7495&amp;lt;br/&amp;gt;life_exp=64.84'/>\\n   <circle id='svg_d0389b9b09825998_e57' cx='174.09' cy='76.02' r='1.47pt' fill='#4D9FDE' fill-opacity='1' stroke='#4D9FDE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='57' title='57&amp;lt;br/&amp;gt;cell_phones_100=105.713&amp;lt;br/&amp;gt;life_exp=76.27'/>\\n   <circle id='svg_d0389b9b09825998_e58' cx='183.38' cy='110.15' r='1.47pt' fill='#4997D5' fill-opacity='1' stroke='#4997D5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='58' title='58&amp;lt;br/&amp;gt;cell_phones_100=111.303&amp;lt;br/&amp;gt;life_exp=71.1'/>\\n   <circle id='svg_d0389b9b09825998_e59' cx='184.74' cy='173.05' r='1.47pt' fill='#336A98' fill-opacity='1' stroke='#336A98' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='59' title='59&amp;lt;br/&amp;gt;cell_phones_100=112.12&amp;lt;br/&amp;gt;life_exp=61.57'/>\\n   <circle id='svg_d0389b9b09825998_e60' cx='177.11' cy='116.48' r='1.47pt' fill='#316793' fill-opacity='1' stroke='#316793' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='60' title='60&amp;lt;br/&amp;gt;cell_phones_100=107.535&amp;lt;br/&amp;gt;life_exp=70.14'/>\\n   <circle id='svg_d0389b9b09825998_e61' cx='342.92' cy='79.98' r='1.47pt' fill='#3D7FB4' fill-opacity='1' stroke='#3D7FB4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='61' title='61&amp;lt;br/&amp;gt;cell_phones_100=207.278&amp;lt;br/&amp;gt;life_exp=75.67'/>\\n   <circle id='svg_d0389b9b09825998_e62' cx='235.75' cy='124.8' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='62' title='62&amp;lt;br/&amp;gt;cell_phones_100=142.809&amp;lt;br/&amp;gt;life_exp=68.88'/>\\n   <circle id='svg_d0389b9b09825998_e63' cx='74.52' cy='203.81' r='1.47pt' fill='#448DC6' fill-opacity='1' stroke='#448DC6' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='63' title='63&amp;lt;br/&amp;gt;cell_phones_100=45.8178&amp;lt;br/&amp;gt;life_exp=56.91'/>\\n   <circle id='svg_d0389b9b09825998_e64' cx='181.02' cy='119.32' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='64' title='64&amp;lt;br/&amp;gt;cell_phones_100=109.884&amp;lt;br/&amp;gt;life_exp=69.71'/>\\n   <circle id='svg_d0389b9b09825998_e65' cx='271.49' cy='88.83' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='65' title='65&amp;lt;br/&amp;gt;cell_phones_100=164.309&amp;lt;br/&amp;gt;life_exp=74.33'/>\\n   <circle id='svg_d0389b9b09825998_e66' cx='97.51' cy='160.44' r='1.47pt' fill='#3F82B8' fill-opacity='1' stroke='#3F82B8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='66' title='66&amp;lt;br/&amp;gt;cell_phones_100=59.6496&amp;lt;br/&amp;gt;life_exp=63.48'/>\\n   <circle id='svg_d0389b9b09825998_e67' cx='228.1' cy='80.84' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='67' title='67&amp;lt;br/&amp;gt;cell_phones_100=138.208&amp;lt;br/&amp;gt;life_exp=75.54'/>\\n   <circle id='svg_d0389b9b09825998_e68' cx='165.52' cy='183.15' r='1.47pt' fill='#4894D0' fill-opacity='1' stroke='#4894D0' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='68' title='68&amp;lt;br/&amp;gt;cell_phones_100=100.558&amp;lt;br/&amp;gt;life_exp=60.04'/>\\n   <circle id='svg_d0389b9b09825998_e69' cx='103.71' cy='172.19' r='1.47pt' fill='#4D9FDE' fill-opacity='1' stroke='#4D9FDE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='69' title='69&amp;lt;br/&amp;gt;cell_phones_100=63.3771&amp;lt;br/&amp;gt;life_exp=61.7'/>\\n   <circle id='svg_d0389b9b09825998_e70' cx='163.9' cy='149.02' r='1.47pt' fill='#29567D' fill-opacity='1' stroke='#29567D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='70' title='70&amp;lt;br/&amp;gt;cell_phones_100=99.5852&amp;lt;br/&amp;gt;life_exp=65.21'/>\\n   <circle id='svg_d0389b9b09825998_e71' cx='219.9' cy='104.07' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='71' title='71&amp;lt;br/&amp;gt;cell_phones_100=133.273&amp;lt;br/&amp;gt;life_exp=72.02'/>\\n   <circle id='svg_d0389b9b09825998_e72' cx='129.86' cy='146.85' r='1.47pt' fill='#4D9FDE' fill-opacity='1' stroke='#4D9FDE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='72' title='72&amp;lt;br/&amp;gt;cell_phones_100=79.1051&amp;lt;br/&amp;gt;life_exp=65.54'/>\\n   <circle id='svg_d0389b9b09825998_e73' cx='251.13' cy='57.87' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='73' title='73&amp;lt;br/&amp;gt;cell_phones_100=152.062&amp;lt;br/&amp;gt;life_exp=79.02'/>\\n   <circle id='svg_d0389b9b09825998_e74' cx='204.68' cy='69.02' r='1.47pt' fill='#4289C2' fill-opacity='1' stroke='#4289C2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='74' title='74&amp;lt;br/&amp;gt;cell_phones_100=124.119&amp;lt;br/&amp;gt;life_exp=77.33'/>\\n   <circle id='svg_d0389b9b09825998_e75' cx='243.43' cy='103.15' r='1.47pt' fill='#3F82B8' fill-opacity='1' stroke='#3F82B8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='75' title='75&amp;lt;br/&amp;gt;cell_phones_100=147.429&amp;lt;br/&amp;gt;life_exp=72.16'/>\\n   <circle id='svg_d0389b9b09825998_e76' cx='226.1' cy='70.08' r='1.47pt' fill='#4B9BDA' fill-opacity='1' stroke='#4B9BDA' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='76' title='76&amp;lt;br/&amp;gt;cell_phones_100=137.002&amp;lt;br/&amp;gt;life_exp=77.17'/>\\n   <circle id='svg_d0389b9b09825998_e77' cx='202.49' cy='36.48' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='77' title='77&amp;lt;br/&amp;gt;cell_phones_100=122.801&amp;lt;br/&amp;gt;life_exp=82.26'/>\\n   <circle id='svg_d0389b9b09825998_e78' cx='211.28' cy='95.36' r='1.47pt' fill='#316793' fill-opacity='1' stroke='#316793' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='78' title='78&amp;lt;br/&amp;gt;cell_phones_100=128.088&amp;lt;br/&amp;gt;life_exp=73.34'/>\\n   <circle id='svg_d0389b9b09825998_e79' cx='199.73' cy='96.55' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='79' title='79&amp;lt;br/&amp;gt;cell_phones_100=121.142&amp;lt;br/&amp;gt;life_exp=73.16'/>\\n   <circle id='svg_d0389b9b09825998_e80' cx='278.42' cy='122.69' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='80' title='80&amp;lt;br/&amp;gt;cell_phones_100=168.476&amp;lt;br/&amp;gt;life_exp=69.2'/>\\n   <circle id='svg_d0389b9b09825998_e81' cx='247.37' cy='83.74' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='81' title='81&amp;lt;br/&amp;gt;cell_phones_100=149.798&amp;lt;br/&amp;gt;life_exp=75.1'/>\\n   <circle id='svg_d0389b9b09825998_e82' cx='194.76' cy='131.53' r='1.47pt' fill='#4997D5' fill-opacity='1' stroke='#4997D5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='82' title='82&amp;lt;br/&amp;gt;cell_phones_100=118.15&amp;lt;br/&amp;gt;life_exp=67.86'/>\\n   <circle id='svg_d0389b9b09825998_e83' cx='285.95' cy='16.88' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='83' title='83&amp;lt;br/&amp;gt;cell_phones_100=173.005&amp;lt;br/&amp;gt;life_exp=85.23'/>\\n   <circle id='svg_d0389b9b09825998_e84' cx='177.69' cy='170.61' r='1.47pt' fill='#4997D5' fill-opacity='1' stroke='#4997D5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='84' title='84&amp;lt;br/&amp;gt;cell_phones_100=107.882&amp;lt;br/&amp;gt;life_exp=61.94'/>\\n   <circle id='svg_d0389b9b09825998_e85' cx='302.97' cy='87.18' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='85' title='85&amp;lt;br/&amp;gt;cell_phones_100=183.249&amp;lt;br/&amp;gt;life_exp=74.58'/>\\n   <circle id='svg_d0389b9b09825998_e86' cx='214.15' cy='96.68' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='86' title='86&amp;lt;br/&amp;gt;cell_phones_100=129.813&amp;lt;br/&amp;gt;life_exp=73.14'/>\\n   <circle id='svg_d0389b9b09825998_e87' cx='224.48' cy='82.95' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='87' title='87&amp;lt;br/&amp;gt;cell_phones_100=136.029&amp;lt;br/&amp;gt;life_exp=75.22'/>\\n   <circle id='svg_d0389b9b09825998_e88' cx='232.38' cy='29.75' r='1.47pt' fill='#4B9BDA' fill-opacity='1' stroke='#4B9BDA' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='88' title='88&amp;lt;br/&amp;gt;cell_phones_100=140.782&amp;lt;br/&amp;gt;life_exp=83.28'/>\\n   <circle id='svg_d0389b9b09825998_e89' cx='200.32' cy='221.5' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='89' title='89&amp;lt;br/&amp;gt;cell_phones_100=121.492&amp;lt;br/&amp;gt;life_exp=54.23'/>\\n   <circle id='svg_d0389b9b09825998_e90' cx='107.14' cy='182.82' r='1.47pt' fill='#4894D0' fill-opacity='1' stroke='#4894D0' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='90' title='90&amp;lt;br/&amp;gt;cell_phones_100=65.4378&amp;lt;br/&amp;gt;life_exp=60.09'/>\\n   <circle id='svg_d0389b9b09825998_e91' cx='118.4' cy='145.39' r='1.47pt' fill='#4690CB' fill-opacity='1' stroke='#4690CB' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='91' title='91&amp;lt;br/&amp;gt;cell_phones_100=72.2148&amp;lt;br/&amp;gt;life_exp=65.76'/>\\n   <circle id='svg_d0389b9b09825998_e92' cx='291.3' cy='57.21' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='92' title='92&amp;lt;br/&amp;gt;cell_phones_100=176.223&amp;lt;br/&amp;gt;life_exp=79.12'/>\\n   <circle id='svg_d0389b9b09825998_e93' cx='208.08' cy='117.54' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='93' title='93&amp;lt;br/&amp;gt;cell_phones_100=126.161&amp;lt;br/&amp;gt;life_exp=69.98'/>\\n   <circle id='svg_d0389b9b09825998_e94' cx='217.58' cy='78.2' r='1.47pt' fill='#52AAED' fill-opacity='1' stroke='#52AAED' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='94' title='94&amp;lt;br/&amp;gt;cell_phones_100=131.875&amp;lt;br/&amp;gt;life_exp=75.94'/>\\n   <circle id='svg_d0389b9b09825998_e95' cx='170.77' cy='57.74' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='95' title='95&amp;lt;br/&amp;gt;cell_phones_100=103.721&amp;lt;br/&amp;gt;life_exp=79.04'/>\\n   <circle id='svg_d0389b9b09825998_e96' cx='152.98' cy='137.28' r='1.47pt' fill='#4B9BDA' fill-opacity='1' stroke='#4B9BDA' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='96' title='96&amp;lt;br/&amp;gt;cell_phones_100=93.016&amp;lt;br/&amp;gt;life_exp=66.99'/>\\n   <circle id='svg_d0389b9b09825998_e97' cx='114.95' cy='137.8' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='97' title='97&amp;lt;br/&amp;gt;cell_phones_100=70.1401&amp;lt;br/&amp;gt;life_exp=66.91'/>\\n   <circle id='svg_d0389b9b09825998_e98' cx='198.27' cy='131.14' r='1.47pt' fill='#29567D' fill-opacity='1' stroke='#29567D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='98' title='98&amp;lt;br/&amp;gt;cell_phones_100=120.261&amp;lt;br/&amp;gt;life_exp=67.92'/>\\n   <circle id='svg_d0389b9b09825998_e99' cx='230.8' cy='64.47' r='1.47pt' fill='#51A6E8' fill-opacity='1' stroke='#51A6E8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='99' title='99&amp;lt;br/&amp;gt;cell_phones_100=139.829&amp;lt;br/&amp;gt;life_exp=78.02'/>\\n   <circle id='svg_d0389b9b09825998_e100' cx='173.69' cy='125.59' r='1.47pt' fill='#54ADF2' fill-opacity='1' stroke='#54ADF2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='100' title='100&amp;lt;br/&amp;gt;cell_phones_100=105.472&amp;lt;br/&amp;gt;life_exp=68.76'/>\\n   <circle id='svg_d0389b9b09825998_e101' cx='227.51' cy='84.73' r='1.47pt' fill='#4690CB' fill-opacity='1' stroke='#4690CB' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='101' title='101&amp;lt;br/&amp;gt;cell_phones_100=137.852&amp;lt;br/&amp;gt;life_exp=74.95'/>\\n   <circle id='svg_d0389b9b09825998_e102' cx='75.58' cy='141.7' r='1.47pt' fill='#18344F' fill-opacity='1' stroke='#18344F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='102' title='102&amp;lt;br/&amp;gt;cell_phones_100=46.4534&amp;lt;br/&amp;gt;life_exp=66.32'/>\\n   <circle id='svg_d0389b9b09825998_e103' cx='265.54' cy='179.98' r='1.47pt' fill='#4289C2' fill-opacity='1' stroke='#4289C2' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='103' title='103&amp;lt;br/&amp;gt;cell_phones_100=160.729&amp;lt;br/&amp;gt;life_exp=60.52'/>\\n   <circle id='svg_d0389b9b09825998_e104' cx='161.99' cy='168.96' r='1.47pt' fill='#448DC6' fill-opacity='1' stroke='#448DC6' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='104' title='104&amp;lt;br/&amp;gt;cell_phones_100=98.4373&amp;lt;br/&amp;gt;life_exp=62.19'/>\\n   <circle id='svg_d0389b9b09825998_e105' cx='146.3' cy='189.09' r='1.47pt' fill='#4FA2E3' fill-opacity='1' stroke='#4FA2E3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='105' title='105&amp;lt;br/&amp;gt;cell_phones_100=88.9958&amp;lt;br/&amp;gt;life_exp=59.14'/>\\n   <polyline id='svg_d0389b9b09825998_e106' points='48.23,151.51 64.85,152.84 81.47,154.16 98.10,155.49 114.72,156.81 131.34,158.14 147.97,159.46 164.59,160.79 181.21,162.11 197.84,163.44 214.46,164.76 231.08,166.09 247.70,167.41 264.33,168.74 280.95,170.06 297.57,171.39 314.20,172.71 330.82,174.04 347.44,175.36' fill='none' stroke='#132B43' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for vax_rate=60&amp;lt;br/&amp;gt;y = -0.02*x +65.44' data-id='1'/>\\n   <polyline id='svg_d0389b9b09825998_e107' points='48.23,153.40 64.85,152.69 81.47,151.98 98.10,151.28 114.72,150.57 131.34,149.87 147.97,149.16 164.59,148.46 181.21,147.75 197.84,147.05 214.46,146.34 231.08,145.63 247.70,144.93 264.33,144.22 280.95,143.52 297.57,142.81 314.20,142.11 330.82,141.40 347.44,140.69' fill='none' stroke='#22496C' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for vax_rate=70&amp;lt;br/&amp;gt;y = 0.01*x +64.23' data-id='20'/>\\n   <polyline id='svg_d0389b9b09825998_e108' points='48.23,155.28 64.85,152.54 81.47,149.80 98.10,147.07 114.72,144.33 131.34,141.60 147.97,138.86 164.59,136.12 181.21,133.39 197.84,130.65 214.46,127.92 231.08,125.18 247.70,122.44 264.33,119.71 280.95,116.97 297.57,114.24 314.20,111.50 330.82,108.76 347.44,106.03' fill='none' stroke='#336A98' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for vax_rate=80&amp;lt;br/&amp;gt;y = 0.04*x +63.02' data-id='39'/>\\n   <polyline id='svg_d0389b9b09825998_e109' points='48.23,157.16 64.85,152.39 81.47,147.63 98.10,142.86 114.72,138.09 131.34,133.33 147.97,128.56 164.59,123.79 181.21,119.03 197.84,114.26 214.46,109.49 231.08,104.73 247.70,99.96 264.33,95.19 280.95,90.43 297.57,85.66 314.20,80.90 330.82,76.13 347.44,71.36' fill='none' stroke='#448DC6' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for vax_rate=90&amp;lt;br/&amp;gt;y = 0.07*x +61.81' data-id='58'/>\\n   <polyline id='svg_d0389b9b09825998_e110' points='48.23,159.04 64.85,152.24 81.47,145.45 98.10,138.65 114.72,131.85 131.34,125.06 147.97,118.26 164.59,111.46 181.21,104.67 197.84,97.87 214.46,91.07 231.08,84.27 247.70,77.48 264.33,70.68 280.95,63.88 297.57,57.09 314.20,50.29 330.82,43.49 347.44,36.70' fill='none' stroke='#56B1F7' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for vax_rate=100&amp;lt;br/&amp;gt;y = 0.1*x +60.6' data-id='77'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_d0389b9b09825998_c1)'>\\n   <text x='18.54' y='252.57' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>50<\\/text>\\n   <text x='18.54' y='186.57' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>60<\\/text>\\n   <text x='18.54' y='120.56' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>70<\\/text>\\n   <text x='18.54' y='54.55' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>80<\\/text>\\n   <polyline points='30.53,249.42 33.27,249.42' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='30.53,183.41 33.27,183.41' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='30.53,117.41 33.27,117.41' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='30.53,51.40 33.27,51.40' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='81.47,259.01 81.47,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='164.59,259.01 164.59,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='247.70,259.01 247.70,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='330.82,259.01 330.82,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <text x='76.58' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>50<\\/text>\\n   <text x='157.25' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>100<\\/text>\\n   <text x='240.36' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>150<\\/text>\\n   <text x='323.48' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>200<\\/text>\\n   <text x='156.23' y='280.09' font-size='8.25pt' font-family='Helvetica'>cell_phones_100<\\/text>\\n   <text transform='translate(13.37,149.83) rotate(-90.00)' font-size='8.25pt' font-family='Helvetica'>life_exp<\\/text>\\n   <rect x='373.36' y='74.29' width='53.16' height='113.16' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <text x='378.84' y='88.88' font-size='8.25pt' font-family='Helvetica'>vax_rate<\\/text>\\n   <image x='378.84' y='95.57' width='17.28' height='86.4' preserveAspectRatio='none' xlink:href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAEsCAYAAAACUNnVAAAAmElEQVQ4ja2UQRLDMAgDd3hk/tnX5agcknFaCoa0vnkMCEnGsL12GQhDYDpPwoDrpBFlRDWi/9Wu6AHC9FkLYLrzlhD3oJ3mDvRHRYy7IC8A7bCK8gpWKYDzeQVArDcDyD2YAnSofZvzaOA6Q7Oahp/dmRuVTQ0xU5TGP2o8Waool1obVuv1q8qP9xPvg633XlGLDtfIhNUBcBeA5ss0BXMAAAAASUVORK5CYII=' xmlns:xlink='http://www.w3.org/1999/xlink'/>\\n   <polyline points='392.67,181.83 396.12,181.83' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='392.67,160.30 396.12,160.30' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='392.67,138.77 396.12,138.77' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='392.67,117.25 396.12,117.25' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='392.67,95.72 396.12,95.72' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='382.30,181.83 378.84,181.83' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='382.30,160.30 378.84,160.30' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='382.30,138.77 378.84,138.77' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='382.30,117.25 378.84,117.25' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='382.30,95.72 378.84,95.72' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <text x='401.6' y='184.98' font-size='6.6pt' font-family='Helvetica'>60<\\/text>\\n   <text x='401.6' y='163.46' font-size='6.6pt' font-family='Helvetica'>70<\\/text>\\n   <text x='401.6' y='141.93' font-size='6.6pt' font-family='Helvetica'>80<\\/text>\\n   <text x='401.6' y='120.4' font-size='6.6pt' font-family='Helvetica'>90<\\/text>\\n   <text x='401.6' y='98.87' font-size='6.6pt' font-family='Helvetica'>100<\\/text>\\n  <\\/g>\\n <\\/g>\\n<\\/svg>\",\"js\":null,\"uid\":\"svg_d0389b9b09825998\",\"ratio\":1.5,\"settings\":{\"tooltip\":{\"css\":\".tooltip_SVGID_ { background-color:white;font-style:italic;padding:10px;border-radius:10px 20px 10px 20px; ; position:absolute;pointer-events:none;z-index:999;}\",\"placement\":\"doc\",\"opacity\":0.75,\"offx\":10,\"offy\":0,\"use_cursor_pos\":true,\"use_fill\":false,\"use_stroke\":false,\"delay_over\":200,\"delay_out\":500},\"hover\":{\"css\":\".hover_data_SVGID_ { r:4px;cursor:pointer;stroke:red;stroke-width:2px; }\",\"reactive\":false,\"nearest_distance\":null},\"hover_inv\":{\"css\":\"\"},\"hover_key\":{\"css\":\".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_key_SVGID_ { stroke:orange; }\",\"reactive\":true},\"hover_theme\":{\"css\":\".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_theme_SVGID_ { stroke:orange; }\",\"reactive\":true},\"select\":{\"css\":\".select_data_SVGID_ { fill:#FF3333;stroke:black; }\",\"type\":\"multiple\",\"only_shiny\":true,\"selected\":[]},\"select_inv\":{\"css\":\"\"},\"select_key\":{\"css\":\".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_key_SVGID_ { stroke:none;fill:red; }\\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\\nimage.select_key_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"select_theme\":{\"css\":\".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\\nimage.select_theme_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"zoom\":{\"min\":1,\"max\":10,\"duration\":300,\"default_on\":false},\"toolbar\":{\"position\":\"topright\",\"pngname\":\"diagram\",\"tooltips\":null,\"fixed\":false,\"hidden\":[],\"delay_over\":200,\"delay_out\":500},\"sizing\":{\"rescale\":true,\"width\":1}}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n:::\n\n## Model with interaction between *two continuous variables*\n\nModel we are fitting:\n\n$$ LE = \\beta_0 + \\beta_1 CP^c + \\beta_2 VR^c + \\beta_3 CP^c \\cdot VR^c + \\epsilon$$\n\n-   $LE$ as life expectancy\n-   $CP^c$ as the **centered** around the mean number of cell phones per 100 people (continuous variable)\n-   $VR^c$ as the **centered** around the mean vaccination rate (continuous variable)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to center CP and VR\"}\ngapm = gapm %>% \n  mutate(CP_c = cell_phones_100 - mean(cell_phones_100), \n         VR_c = vax_rate - mean(vax_rate))\nmean_VR = mean(gapm$vax_rate) %>% round(digits = 2)\nmean_CP = mean(gapm$cell_phones_100) %>% round(digits = 2)\n```\n:::\n\n\nIn R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_vr = gapm %>% lm(formula = life_exp ~ CP_c + VR_c + CP_c*VR_c)\n```\n:::\n\n\nOR\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_vr = gapm %>% lm(formula = life_exp ~ CP_c*VR_c)\n```\n:::\n\n\n## Displaying the regression table and writing fitted regression equation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_m_vr = tidy(m_int_vr, conf.int=T) \ntidy_m_vr %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 5)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tvpuaizijh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tvpuaizijh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tvpuaizijh thead, #tvpuaizijh tbody, #tvpuaizijh tfoot, #tvpuaizijh tr, #tvpuaizijh td, #tvpuaizijh th {\n  border-style: none;\n}\n\n#tvpuaizijh p {\n  margin: 0;\n  padding: 0;\n}\n\n#tvpuaizijh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tvpuaizijh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tvpuaizijh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tvpuaizijh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tvpuaizijh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tvpuaizijh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tvpuaizijh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tvpuaizijh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tvpuaizijh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tvpuaizijh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tvpuaizijh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tvpuaizijh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tvpuaizijh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tvpuaizijh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tvpuaizijh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tvpuaizijh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tvpuaizijh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tvpuaizijh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tvpuaizijh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tvpuaizijh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tvpuaizijh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tvpuaizijh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tvpuaizijh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tvpuaizijh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tvpuaizijh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tvpuaizijh .gt_left {\n  text-align: left;\n}\n\n#tvpuaizijh .gt_center {\n  text-align: center;\n}\n\n#tvpuaizijh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tvpuaizijh .gt_font_normal {\n  font-weight: normal;\n}\n\n#tvpuaizijh .gt_font_bold {\n  font-weight: bold;\n}\n\n#tvpuaizijh .gt_font_italic {\n  font-style: italic;\n}\n\n#tvpuaizijh .gt_super {\n  font-size: 65%;\n}\n\n#tvpuaizijh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tvpuaizijh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tvpuaizijh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tvpuaizijh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tvpuaizijh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tvpuaizijh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tvpuaizijh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tvpuaizijh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tvpuaizijh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">70.56972</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.61989</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">113.84216</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">69.34002</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">71.79942</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">CP_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.07666</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.01832</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.18404</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00006</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.04032</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.11301</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">VR_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.23765</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.08409</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.82598</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00568</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.07083</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.40447</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">CP_c:VR_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.00308</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00192</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">1.59912</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.11292</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.00074</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.00689</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP^c + \\widehat\\beta_2 VR^c + \\widehat\\beta_3 CP^c \\cdot VR^c \\\\\n\\widehat{LE} = & 70.57 + 0.08 \\cdot CP^c + 0.24 \\cdot VR^c + 0.003 \\cdot CP^c \\cdot VR^c\n\\end{aligned}$$\n\n## Comparing fitted regression lines for various vaccination rates\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP^c + \\widehat\\beta_2 VR^c + \\widehat\\beta_3 CP^c \\cdot VR^c \\\\\n\\widehat{LE} = & 70.57 + 0.08 \\cdot CP^c + 0.24 \\cdot VR^c + 0.003 \\cdot CP^c \\cdot VR^c\n\\end{aligned}$$\n\nTo identify different lines, we need to pick example vaccination rates:\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: {.column width=\"33%\"}\n::: FS1\n::: FS1-title\nVaccination rate of 86.45 \\%\n:::\n\n::: FS1-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP^c + \\\\ & \\widehat\\beta_2 \\cdot (-5) + \\\\ & \\widehat\\beta_3 CP^c \\cdot (-5) \\\\\n\\widehat{LE} = & \\big(\\widehat\\beta_0 - 5 \\widehat\\beta_2 \\big)+ \\\\ & \\big(\\widehat\\beta_1 - 5 \\widehat\\beta_3  \\big) CP^c\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: FS2\n::: FS2-title\nVaccination rate of 91.45 \\%\n:::\n\n::: FS2-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP^c + \\\\ & \\widehat\\beta_2 \\cdot 0 + \\\\ & \\widehat\\beta_3 CP^c \\cdot 0 \\\\\n\\widehat{LE} = & \\big(\\widehat\\beta_0 \\big)+ \\\\ & \\big(\\widehat\\beta_1 \\big) CP^c\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: FS3\n::: FS3-title\nVaccination rate of 96.45 \\%\n:::\n\n::: FS3-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP^c + \\\\ & \\widehat\\beta_2 \\cdot 5 + \\\\ & \\widehat\\beta_3 CP^c \\cdot 5 \\\\\n\\widehat{LE} = & \\big(\\widehat\\beta_0 + 5 \\widehat\\beta_2 \\big)+ \\\\ & \\big(\\widehat\\beta_1 + 5 \\widehat\\beta_3  \\big) CP^c\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Poll Everywhere Question??\n\n## Interpretation for interaction between two continuous variables\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP^c + \\widehat\\beta_2 VR^c + \\widehat\\beta_3 CP^c \\cdot VR^c \\\\\n\\widehat{LE} = & \\bigg[\\widehat\\beta_0 + \\widehat\\beta_2 \\cdot VR^c \\bigg] + \\underbrace{\\bigg[\\widehat\\beta_1 + \\widehat\\beta_3 \\cdot VR^c \\bigg]}_\\text{CP's effect} CP \\\\\n\\end{aligned}$$\n\n-   Interpretation:\n\n    -   $\\beta_3$ = mean change in cell phones's effect, for every 1 \\% increase in vaccination rate\n\n-   In summary, the interaction term can be interpreted as \"difference in adjusted effect of number of cell phones for every 1 \\% increase in vaccination rate\"\n\n-   It will be helpful to test the interaction to round out this interpretation!!\n\n## Test interaction between two continuous variables (1/2)\n\n-   We run an F-test for a single coefficients ($\\beta_3$) in the below model (see lesson 9)\n\n$$ LE = \\beta_0 + \\beta_1 CP^c + \\beta_2 VR^c + \\beta_3 CP^c \\cdot VR^c + \\epsilon$$\n\n::: columns\n::: {.column width=\"10%\"}\n:::\n\n::: {.column width=\"40%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$$\\beta_3=0$$\n:::\n:::\n:::\n\n::: {.column width=\"40%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$$\\beta_3\\neq0$$\n:::\n:::\n:::\n\n::: {.column width=\"10%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"10%\"}\n:::\n\n::: {.column width=\"40%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$$ LE = \\beta_0 + \\beta_1 CP^c + \\beta_2 VR^c + \\epsilon$$\n:::\n:::\n:::\n\n::: {.column width=\"40%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$$\\begin{aligned}\nLE = & \\beta_0 + \\beta_1 CP^c + \\beta_2 VR^c + \\\\ & \\beta_3 CP^c \\cdot VR^c + \\epsilon\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Test interaction between two continuous variables (2/2)\n\n-   Fit the reduced and full model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_vr_red = gapm %>% \n  lm(formula = life_exp ~ CP_c + VR_c)\nm_int_vr_full = gapm %>%\n  lm(formula = life_exp ~ CP_c + VR_c + CP_c*VR_c)\n```\n:::\n\n\n \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Display the ANOVA table with F-statistic and p-value\"}\nanova_table2 = anova(m_int_vr_red, m_int_vr_full) \nanova_table2 %>% tidy() %>% gt() %>% tab_options(table.font.size = 35) %>% \n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qoixnvnbtu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qoixnvnbtu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qoixnvnbtu thead, #qoixnvnbtu tbody, #qoixnvnbtu tfoot, #qoixnvnbtu tr, #qoixnvnbtu td, #qoixnvnbtu th {\n  border-style: none;\n}\n\n#qoixnvnbtu p {\n  margin: 0;\n  padding: 0;\n}\n\n#qoixnvnbtu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qoixnvnbtu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qoixnvnbtu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qoixnvnbtu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qoixnvnbtu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qoixnvnbtu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qoixnvnbtu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qoixnvnbtu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qoixnvnbtu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qoixnvnbtu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qoixnvnbtu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qoixnvnbtu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qoixnvnbtu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qoixnvnbtu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qoixnvnbtu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qoixnvnbtu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qoixnvnbtu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qoixnvnbtu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qoixnvnbtu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qoixnvnbtu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qoixnvnbtu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qoixnvnbtu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qoixnvnbtu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qoixnvnbtu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qoixnvnbtu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qoixnvnbtu .gt_left {\n  text-align: left;\n}\n\n#qoixnvnbtu .gt_center {\n  text-align: center;\n}\n\n#qoixnvnbtu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qoixnvnbtu .gt_font_normal {\n  font-weight: normal;\n}\n\n#qoixnvnbtu .gt_font_bold {\n  font-weight: bold;\n}\n\n#qoixnvnbtu .gt_font_italic {\n  font-style: italic;\n}\n\n#qoixnvnbtu .gt_super {\n  font-size: 65%;\n}\n\n#qoixnvnbtu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qoixnvnbtu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qoixnvnbtu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qoixnvnbtu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qoixnvnbtu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qoixnvnbtu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qoixnvnbtu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qoixnvnbtu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qoixnvnbtu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ CP_c + VR_c</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">102.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,480.371</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">life_exp ~ CP_c + VR_c + CP_c * VR_c</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">101.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">3,394.429</td>\n<td headers=\"df\" class=\"gt_row gt_right\">1.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">85.942</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.113</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n-   Conclusion: There is not a significant interaction between cell phones and vaccination rate (p = 0.113). Vaccination rate is not an effect modifier of the association between cell phones and life expectancy.\n\n# Learning Objective\n\n**Last time:**\n\n1.  Define confounders and effect modifiers, and how they interact with the main relationship we model.\n2.  Interpret the interaction component of a model with **a binary categorical covariate and continuous covariate**, and how the main variable's effect changes.\n3.  Interpret the interaction component of a model with **a multi-level categorical covariate and continuous covariate**, and how the main variable's effect changes.\n\n**This time:**\n\n4.  Interpret the interaction component of a model with **two categorical covariates**, and how the main variable's effect changes.\n5.  Interpret the interaction component of a model with **two continuous covariates**, and how the main variable's effect changes.\n\n::: lob\n6. Report results for a best-fit line (with confidence intervals) at different levels of an effect measure modifier\n:::\n\n## How to find the confidence interval for each slope?\n\n- In the example with VR and CP, we showed:\n\n::: FS3\n::: FS3-title\nBest-fit line for vaccination rate of 96.45 \\%\n:::\n::: FS3-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\big(\\widehat\\beta_0 + 5 \\widehat\\beta_2 \\big)+  \\big(\\widehat\\beta_1 + 5 \\widehat\\beta_3  \\big) CP^c\n\\end{aligned}$$\n:::\n:::\n\n- Often, we want to report the estimate of the combined coefficients: $\\widehat\\beta_1 + 5 \\widehat\\beta_3$\n\n  - This allows us to make a statement like: \"At a vaccination rate of 96.45\\%, mean life expectancy increases $\\big(\\widehat\\beta_1 + 5 \\widehat\\beta_3 \\big)$ years for every one additional cell phone per 100 people (95% CI: \\_\\_, \\_\\_).\"\n\n \n\n- We can calculate $\\widehat\\beta_1 + 5 \\widehat\\beta_3$ by using the values of the estimated coefficients\n\n- BUT we always want to have a **95% confidence interval** when we report this combined estimate!!\n\n## Getting a 95% confidence interval requires linear combinations!\n\n- If we want a confidence interval for $\\widehat\\beta_1 + 5 \\widehat\\beta_3$, then we would use the formula:\n\n$$\\bigg(\\widehat\\beta_1 + 5 \\widehat\\beta_3 \\bigg) \\pm t^* \\times SE_{(\\beta_1 + 5 \\beta_3)}$$\n\n- The hard part is figuring out what $SE_{(\\beta_1 + 5 \\beta_3)}$ (or $\\text{Var}(\\beta_1 + 5 \\beta_3)$) equals\n\n- We need to go back to variance of linear combinations (BSTA 511/611, EPI 525):\n$$\\text{Var}(aX + bY) = a^2\\text{Var}(X) + b^2\\text{Var}(Y) + 2ab\\text{Cov}(X, Y)$$\nor\n$$\\text{Var}(aX - bY) = a^2\\text{Var}(X) + b^2\\text{Var}(Y) - 2ab\\text{Cov}(X, Y)$$\n\n## Calculating $SE_{(\\beta_1 + 5 \\beta_3)}$ \"by hand\" (REFERENCE)\n\n- A helpful function that returns the variance-covariance matric of all the coefficients in model `m_int_vr`:\n\n::: columns\n::: {.column width=\"70%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nvcov(m_int_vr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              (Intercept)          CP_c          VR_c     CP_c:VR_c\n(Intercept)  0.3842647156 -2.466140e-04 -1.098844e-02 -4.873521e-04\nCP_c        -0.0002466140  3.357335e-04 -5.354918e-04  1.872476e-06\nVR_c        -0.0109884449 -5.354918e-04  7.071783e-03  8.343243e-05\nCP_c:VR_c   -0.0004873521  1.872476e-06  8.343243e-05  3.700339e-06\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"30%\"}\n$$ \\begin{aligned}\n\\text{Var}(\\beta_1) & = 3.35733\\times 10^{-4} \\\\\n\\text{Var}(\\beta_3) & = 0.0070718 \\\\\n\\text{Cov}(\\beta_1, \\beta_3) & = -5.35492\\times 10^{-4} \\\\\n\\end{aligned}$$\n:::\n:::\n\n$$ \\begin{aligned}\n\\text{Var}(\\beta_1 + 5 \\beta_3) & = \\text{Var}(\\beta_1) + 5 ^2 \\text{Var}(\\beta_3) + 2 \\cdot 5 \\cdot \\text{Cov}(\\beta_1, \\beta_3) \\\\ \n\\text{Var}(\\beta_1 + 5 \\beta_3) & = 3.35733\\times 10^{-4} + 5^2 \\ \\times 3.7\\times 10^{-6} + 2 \\cdot 5 \\cdot 1.872\\times 10^{-6} \\\\ \n\\text{Var}(\\beta_1 + 5 \\beta_3) & = 4.46967\\times 10^{-4} \\\\\nSE_{(\\beta_1 + 5 \\beta_3)} & = \\sqrt{4.46967\\times 10^{-4}} \\\\ \nSE_{(\\beta_1 + 5 \\beta_3)} & = 0.0211416\n\\end{aligned}$$\n\n\n## We can use R and `estimable()` to find the estimate and CI\n\nFor $\\widehat\\beta_1 + 5 \\widehat\\beta_3$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gmodels)\nm_int_vr %>% estimable(\n                   c(\"(Intercept)\" = 0,      # beta0\n                     \"CP_c\"       = 1,      # beta1\n                     \"VR_c\"        = 0,      # beta2\n                     \"CP_c:VR_c\"  = 5),  # beta3\n                   conf.int = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value  DF     Pr(>|t|)   Lower.CI Upper.CI\n(0 1 0 5) 0.09204476 0.02114159 4.35373 101 3.213735e-05 0.05010553 0.133984\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n \n\n**Our conclusion:** At a vaccination rate of 96.45 \\%, mean life expectancy increases 0.092 years for every one additional cell phone per 100 people (95% CI: 0.05, 0.134).\n\n## Another example: income (binary) and CP (1/2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_inc2 = gapm %>% \n  lm(formula = life_exp ~ CP_c*income_level_2)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP^c + \\widehat\\beta_2 I(\\text{high income}) + \\widehat\\beta_3 CP^c \\cdot I(\\text{high income}) \\\\\n\\widehat{LE} = & 68.408 + 0.076 \\cdot CP^c + 6.247 \\cdot I(\\text{high income}) -0.066 \\cdot CP^c \\cdot I(\\text{high income})\n\\end{aligned}$$\n\n::: columns\n::: column\n::: proof1\n::: proof-title\nFor lower income countries: $I(\\text{high income}) =0$\n:::\n\n::: proof-cont\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 CP\\\\\n\\widehat{LE} = & 68.41 + 0.076 \\cdot CP\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: column\n::: fact\n::: fact-title\nFor higher income countries: $I(\\text{high income}) =1$\n:::\n\n::: fact-cont\n$$ \\begin{aligned}\n\\widehat{LE} = & (\\widehat\\beta_0 +\\widehat\\beta_2) + (\\widehat\\beta_1 +\\widehat\\beta_3) CP \\\\\n\\widehat{LE} = & (68.41 + 6.247) + (0.076 -0.066) \\cdot CP \\\\\n\\widehat{LE} = & 74.65 + 0.01 \\cdot CP\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Another example: income (binary) and CP (2/2)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(m_int_inc2$coefficients) # I just need to see the exact names\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"(Intercept)\"                      \"CP_c\"                            \n[3] \"income_level_2Higher income\"      \"CP_c:income_level_2Higher income\"\n```\n\n\n:::\n\n```{.r .cell-code}\nm_int_inc2 %>% estimable(\n                   c(\"(Intercept)\" = 0,      # beta0\n                     \"CP_c\"       = 1,      # beta1\n                     \"income_level_2Higher income\" = 0,      # beta2\n                     \"CP_c:income_level_2Higher income\"  = 1),  # beta3\n                   conf.int = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error   t value  DF  Pr(>|t|)    Lower.CI   Upper.CI\n(0 1 0 1) 0.01001064 0.02723878 0.3675143 101 0.7140044 -0.04402377 0.06404504\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n \n\n**Our conclusion:** For countries with high income, mean life expectancy increases 0.01 years for every one additional cell phone per 100 people (95% CI: -0.044, 0.064).\n\n## If our example had an effect measure modifier\n\n\n::: {.cell}\n\n:::\n\n\n- None of our examples had a significant interaction, so it's hard to demonstrate exactly how we would report this\n\n- Let's say, **just for example**, that income had a significant interaction with CP\n  - How would we report this to an audience??\n  \n- Here's how to report on an interaction/EMM:\n\n  - We found that a country's income status (high or low) is a significant effect measure modifier on number of cell phones (*include p-value for interaction test here*). For countries with high income, mean life expectancy increases 0.01 years for every additional cell phone per 100 people (95% CI: -0.044, 0.064). For countries with low income, mean life expectancy increases 6.247 years for every additional cell phone per 100 people (95% CI: 3.825, 8.668).\n",
    "supporting": [
      "12_Interactions_02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/ggiraphjs-0.9.2/girafe.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/ggiraphjs-0.9.2/girafe.js\"></script>\n<script src=\"../../site_libs/girafe-binding-0.9.2/girafe.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}