{
  "hash": "3361ccc3ce7f9b34e8459d9e1b15228b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 5: SLR-ish: Categorical Covariates\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"2026-01-21\"\ncategories: [\"Week 6\"]\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 5: Categorical Covariates\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\n# Learning Objectives\n\n1.  Understand why we need a new way to code categorical variables compared to continuous variables\n2.  Write the regression equation for a categorical variable using reference cell coding\n3.  Calculate and interpret coefficients for reference cell coding\n4.  Change the reference level in a categorical variable for reference cell coding\n5.  Create new variables and interpret coefficient for ordinal / scoring coding\n\n## Why \"SLR-*ish*\"?\n\n-   The **strict** definition of simple linear regression: only two variables that are BOTH continuous\n\n \n\n-   Common (but kinda wrong) use of simple linear regression: only two variables with outcome continuous and predictor not specified\n\n \n\n-   I'm including multi-level categorical covariates in SLR mostly because it's easier to learn now!\n\n## Let's map that to our regression analysis process\n\n:::::::::::::::::: box\n![](../img_slides/arrow2.png){.absolute top=\"13.5%\" right=\"62.1%\" width=\"155\"} ![](../img_slides/arrow2.png){.absolute top=\"13.5%\" right=\"28.4%\" width=\"155\"}![](../img_slides/arrow_back4.png){.absolute top=\"7.5%\" right=\"30.5%\" width=\"820\"} ![](../img_slides/arrow_down.png){.absolute top=\"60.5%\" right=\"48%\" width=\"85\"}\n\n::::::::::::::::: columns\n:::::: {.column width=\"30%\"}\n::::: RAP1\n::: RAP1-title\nModel Selection\n:::\n\n::: RAP1-cont\n-   Building a model\n\n-   Selecting variables\n\n-   Prediction vs interpretation\n\n-   Comparing potential models\n:::\n:::::\n::::::\n\n::: {.column width=\"4%\"}\n:::\n\n:::::: {.column width=\"30%\"}\n::::: RAP2\n::: RAP2-title\nModel Fitting\n:::\n\n::: RAP2-cont\n-   Find best fit line\n\n-   Using OLS in this class\n\n-   Parameter estimation\n\n-   Categorical covariates\n\n-   Interactions\n:::\n:::::\n::::::\n\n::: {.column width=\"4%\"}\n:::\n\n:::::: {.column width=\"30%\"}\n::::: RAP3\n::: RAP3-title\nModel Evaluation\n:::\n\n::: RAP3-cont\n-   Evaluation of model fit\n-   Testing model assumptions\n-   Residuals\n-   Transformations\n-   Influential points\n-   Multicollinearity\n:::\n:::::\n::::::\n:::::::::::::::::\n::::::::::::::::::\n\n:::::::: RAP4\n::: RAP4-title\nModel Use (Inference)\n:::\n\n:::::: RAP4-cont\n::::: columns\n::: {.column width=\"50%\"}\n-   Inference for coefficients\n-   Hypothesis testing for coefficients\n:::\n\n::: {.column width=\"50%\"}\n-   Inference for expected $Y$ given $X$\n:::\n:::::\n::::::\n::::::::\n\n# Learning Objectives\n\n::: lob\n1.  Understand why we need a new way to code categorical variables compared to continuous variables\n:::\n\n2.  Write the regression equation for a categorical variable using reference cell coding\n3.  Calculate and interpret coefficients for reference cell coding\n4.  Change the reference level in a categorical variable for reference cell coding\n5.  Create new variables and interpret coefficient for ordinal / scoring coding\n\n## Still looking at Gapminder Life Expectancy data\n\n-   We will look at life expectancy vs. these Freedom statuss\n\n-   [You can access my codebook here](../gapminder_codebook.qmd)\n\n-   Gapminder measures freedom status: This is a descriptive text of the real-world rights and freedoms enjoyed by individuals. It is determined by the freedom rating which is the average of political rights and civil liberties ratings.\n\n    -   Not free (NF)\n    -   Partly free (PF)\n    -   Free (F)\n\n-   Freedom status is a **multi-level categorical covariate**: it has three statuses\n\n \n\n-   Note: I am calling the expected life expectancy $\\widehat{LE}$\n    -   Previously, I have FSitten $\\widehat{\\text{life expectancy}}$\n\n## Visualizing the relationship\n\n:::::: columns\n::: {.column width=\"33%\"}\nBad option for visualization:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(gapm, aes(x = fct_reorder(freedom_status, fs_order), y = life_exp)) +\n  geom_point() +\n  labs(x = \"Freedom status\", \n       y = \"Country life expectancy (years)\",\n       title = \"Life expectancy vs. Freedom status\") +\n  theme(axis.title = element_text(size = 20), \n        axis.text = element_text(size = 20), \n        title = element_text(size = 20))\n```\n\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"33%\"}\nGood option for visualization:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(gapm, aes(x = fct_reorder(freedom_status, fs_order), y = life_exp)) +\n  geom_jitter(size = 1, alpha = .6, width = 0.2) +\n  stat_summary(fun = mean, geom = \"point\", size = 8, shape = 18) +\n  labs(x = \"Freedom status\", \n       y = \"Country life expectancy (years)\",\n       title = \"Life expectancy vs. Freedom status\",\n       caption = \"Diamonds = FS averages\") +\n  theme(axis.title = element_text(size = 20), \n        axis.text = element_text(size = 20), \n        title = element_text(size = 20))\n```\n\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n-   Used `geom_jitter()`\n:::\n\n::: {.column width=\"33%\"}\nGood option for visualization:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(gapm, aes(x = fct_reorder(freedom_status, fs_order), y = life_exp)) +\n  geom_boxplot() +\n  labs(x = \"Freedom status\", \n       y = \"Country life expectancy (years)\",\n       title = \"Life expectancy vs. Freedom status\") +\n  theme(axis.title = element_text(size = 20), \n        axis.text = element_text(size = 20), \n        title = element_text(size = 20))\n```\n\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=672}\n:::\n:::\n\n:::\n::::::\n\n## Linear regression with a categorical covariate\n\n::::: columns\n::: {.column width=\"50%\"}\n-   When using a categorical covariate/predictor,\n\n    -   We do **NOT**, technically, find a best-fit line\n\n-   Instead we model the **means** of the outcome\n\n    -   For the different levels of the categorical variable\n\n \n\n-   In 511/525, we used Kruskal-Wallis test and our ANOVA table to test if groups means were statistically different from one another\n\n-   We can do this [using linear models](https://lindeloev.github.io/tests-as-linear/linear_tests_cheat_sheet.pdf) AND we can include other variables in the model\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=672}\n:::\n:::\n\n:::\n:::::\n\n## There are different ways to code categorical variables\n\n::::::::::::::: columns\n:::::: {.column width=\"33%\"}\n::::: definition\n::: def-title\nReference Cell Coding\n:::\n\n::: def-cont\n-   Sometimes called dummy coding\n-   Compares each level of a variable to the omitted (reference) level\n:::\n:::::\n::::::\n\n:::::: {.column width=\"33%\"}\n::::: example\n::: ex-title\nEffect coding\n:::\n\n::: ex-cont\n-   Sometimes called sum coding or deviation coding\n-   Compares deviations from the grand mean\n-   Not covered in our class\n:::\n:::::\n::::::\n\n:::::: {.column width=\"33%\"}\n::::: fact\n::: fact-title\nOrdinal encoding\n:::\n\n::: fact-cont\n-   Sometimes called scoring\n-   Categories have a natural, even spaced ordering\n-   Linear relationship between levels\n:::\n:::::\n::::::\n:::::::::::::::\n\n \n\nIf you want to learn more about these and other coding schemes:\n\n-   [Coding Systems for Categorical Variables in Regression Analysis](https://stats.oarc.ucla.edu/spss/faq/coding-systems-for-categorical-variables-in-regression-analysis-2/)\n-   [Categorical Data Encoding Techniques](https://medium.com/aiskunks/categorical-data-encoding-techniques-d6296697a40f#:~:text=Ordinal%20Encoding%20is%20used%20when,variable%20have%20a%20Natural%20Ordering.&text=In%20this%20method%2C%20the%20categories,2%2C%20and%203%2C%20respectively.)\n-   [Coding Schemes for Categorical Variables](https://phillipalday.com/stats/coding.html)\n\n## Building the regression equation: problem with a single coefficient\n\n::::: columns\n::: column\n**Previously: simple linear regression**\n\n-   Outcome $Y$ = numerical variable\n-   Predictor $X$ = numerical variable\n\nThe regression (best-fit) line is: $$\\widehat{Y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot X $$\n:::\n\n::: column\n**New: what if the explanatory variable is categorical?**\n\n*Naively*, we could Write: $\\widehat{Y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot X$\n\nOr, with our variables: $$\\widehat{\\textrm{LE}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot \\textrm{FS} $$\n\n-   But what does $\\textrm{FS}$ (freedom status) mean in this equation?\n\n    -   What values can it take? How do we represent each FS?\n\n \n\n-   Note: the above is WRONG\n:::\n:::::\n\n## Building the regression equation: how do we map categories to means?\n\n-   If we only have freedom status in our model and want to map it to an average life expectancy...\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n:::\n\n\n-   We want to create a function that can map each freedom status to life expectancy\n\n    -   If not free: $\\widehat{LE} = 74.13$ years\n\n    -   If partly free: $\\widehat{LE} = 70.39$ years\n\n    -   If free: $\\widehat{LE} = 68.99$ years\n\n \n\n-   Can we make one equation for $\\widehat{LE}$ by putting the \"if\" statements within the equation?\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n:::::\n\n## Building the regression equation: Indicator functions\n\n-   In order to represent each status in the equation, we need to introduce a new function:\n\n    -   Indicator function:\n\n    $$I(X = x) \\text{ or } I(x) = \n    \\left\\{\n    \\begin{array}{@{}ll@{}}\n     1, & \\text{if}\\ X = x \\\\\n      0, & \\text{else}\n     \\end{array}\\right. $$\n\n    -   This basically a binary yes/no if $X$ is a specific value $x$\n\n-   For example, if we want to identify a country as partly free, we can make:\n\n    $$I(FS = \\text{partly free}) \\text{ or }I(\\text{partly free}) = \n    \\left\\{\n    \\begin{array}{@{}ll@{}}\n     1, & \\text{if}\\ FS = \\text{partly free} \\\\\n      0, & \\text{else}\n     \\end{array}\\right. $$\n\n## Poll Everywhere Question 1\n\n# Learning Objectives\n\n1.  Understand why we need a new way to code categorical variables compared to continuous variables\n\n::: lob\n2.  Write the regression equation for a categorical variable using reference cell coding\n:::\n\n3.  Calculate and interpret coefficients for reference cell coding\n4.  Change the reference level in a categorical variable for reference cell coding\n5.  Create new variables and interpret coefficient for ordinal / scoring coding\n\n## Building the regression equation: Indicators in our equation\n\n::::: columns\n::: {.column width=\"50%\"}\n$$\\begin{aligned}\n\\widehat{\\textrm{LE}} = & 74.13 \\cdot I(\\text{not free}) + 70.39 \\cdot I(\\text{partly free}) + \\\\ &68.99 \\cdot I(\\text{free})\n\\end{aligned}$$\n\n-   However, a linear regression equation still requires an intercept!\n\n    -   So one of our statuses need to become our \"reference\" group\n    -   We'll use \"not free\" as our reference\n    -   That means we need to adjust all the numbers\n\n$$\\begin{aligned}\n\\widehat{\\textrm{LE}} = & 74.13 + -3.74 \\cdot I(\\text{partly free}) + \\\\ &-5.14 \\cdot I(\\text{free}) \\\\\n\\widehat{\\textrm{LE}} = & \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{partly free}) + \\\\ & \\widehat\\beta_2 \\cdot I(\\text{free})\n\\end{aligned}$$\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n:::::\n\n## Viewing the regression equation another way\n\n$$\\widehat{\\textrm{LE}} = \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(FS = \\text{partly free}) + \\widehat\\beta_2 \\cdot I(FS = \\text{free})$$\n\n::::: columns\n::: {.column width=\"60%\"}\n| Freedom status | Regression equation for FS | Average Life Expectancy for FS |\n|------------------|------------------------------------|------------------|\n| Not free | $\\begin{aligned} \\widehat{\\textrm{LE}} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 0 + \\widehat\\beta_2 \\cdot 0 \\end{aligned}$ | $\\widehat{\\textrm{LE}} = \\widehat\\beta_0$ |\n| Partly free | $\\begin{aligned} \\widehat{\\textrm{LE}} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 1+ \\widehat\\beta_2 \\cdot 0\\end{aligned}$ | $\\widehat{\\textrm{LE}} = \\widehat\\beta_0 + \\widehat\\beta_1$ |\n| Free | $\\begin{aligned} \\widehat{\\textrm{LE}} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 0 + \\widehat\\beta_2 \\cdot 1\\end{aligned}$ | $\\widehat{\\textrm{LE}} = \\widehat\\beta_0 + \\widehat\\beta_2$ |\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n:::::\n\n# Learning Objectives\n\n1.  Understand why we need a new way to code categorical variables compared to continuous variables\n2.  Write the regression equation for a categorical variable using reference cell coding\n\n::: lob\n3.  Calculate and interpret coefficients for reference cell coding\n:::\n\n4.  Change the reference level in a categorical variable for reference cell coding\n5.  Create new variables and interpret coefficient for ordinal / scoring coding\n\n## Interpretation of regression equation coefficients\n\nRemember: expected, mean, and average are interchangeable\n\n<table style=\"width:98%;\">\n<colgroup>\n<col style=\"width: 23%\" />\n<col style=\"width: 73%\" />\n</colgroup>\n<thead>\n<tr>\n<th><p>Coefficient</p></th>\n<th><p>Interpretation</p></th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><p></p></td>\n<td><p>Expected/mean/average life expectancy of countries that are not free</p></td>\n</tr>\n<tr>\n<td><p></p></td>\n<td><p>Difference in mean life expectancy between partly free and not free countries -OR-</p>\n<p>Mean difference in life expectancy between partly free and not free countries</p></td>\n</tr>\n<tr>\n<td><p></p></td>\n<td><p>Difference in mean life expectancy between free and not free countries -OR-</p>\n<p>Mean difference in life expectancy between free and not free countries</p></td>\n</tr>\n</tbody>\n</table>\n\n## Poll Everywhere Question 2\n\n## Regression table with `lm()` function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 = gapm %>%\n  lm(formula = life_exp ~ freedom_status)\n\ntidy(model1, conf.int=T) %>% gt() %>% tab_options(table.font.size = 38) %>% \n  fmt_number(decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wyqygtaqqg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wyqygtaqqg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wyqygtaqqg thead, #wyqygtaqqg tbody, #wyqygtaqqg tfoot, #wyqygtaqqg tr, #wyqygtaqqg td, #wyqygtaqqg th {\n  border-style: none;\n}\n\n#wyqygtaqqg p {\n  margin: 0;\n  padding: 0;\n}\n\n#wyqygtaqqg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 38px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wyqygtaqqg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wyqygtaqqg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wyqygtaqqg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wyqygtaqqg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wyqygtaqqg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wyqygtaqqg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wyqygtaqqg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wyqygtaqqg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wyqygtaqqg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wyqygtaqqg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wyqygtaqqg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wyqygtaqqg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wyqygtaqqg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wyqygtaqqg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyqygtaqqg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wyqygtaqqg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wyqygtaqqg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wyqygtaqqg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyqygtaqqg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wyqygtaqqg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyqygtaqqg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wyqygtaqqg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyqygtaqqg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyqygtaqqg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyqygtaqqg .gt_left {\n  text-align: left;\n}\n\n#wyqygtaqqg .gt_center {\n  text-align: center;\n}\n\n#wyqygtaqqg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wyqygtaqqg .gt_font_normal {\n  font-weight: normal;\n}\n\n#wyqygtaqqg .gt_font_bold {\n  font-weight: bold;\n}\n\n#wyqygtaqqg .gt_font_italic {\n  font-style: italic;\n}\n\n#wyqygtaqqg .gt_super {\n  font-size: 65%;\n}\n\n#wyqygtaqqg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wyqygtaqqg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wyqygtaqqg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wyqygtaqqg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wyqygtaqqg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wyqygtaqqg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wyqygtaqqg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wyqygtaqqg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wyqygtaqqg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">68.99</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.17</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">58.88</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">66.67</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">71.32</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">freedom_statusF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">5.14</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.70</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.02</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.76</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">8.51</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">freedom_statusPF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.40</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.52</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.92</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.36</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.61</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">4.40</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n$$\\widehat{\\textrm{LE}} = 68.99 + 1.4 \\cdot I(\\text{PF}) + 5.14 \\cdot I(\\text{F})$$\n\n-   Which Freedom status did R choose as the reference level?\n\n-   How you would calculate the mean life expectancies of freedom statuss using *only* the results from the regression table?\n\n## Bringing in the numbers/units/95% CI\n\n| Coefficient | Interpretation |\n|------------------|------------------------------------------------------|\n| $\\widehat{\\beta}_0$ | Average life expectancy of countries that are not free is 68.99 (95% CI: 66.67, 71.32). |\n| $\\widehat{\\beta}_1$ | The difference in mean life expectancy between countries that are partly free and not free is 5.14 (95% CI: 1.76, 8.51). |\n| $\\widehat{\\beta}_2$ | The difference in mean life expectancy between countries that are free and not free is 1.4 (95% CI: -1.61, 4.4). |\n\n-   Don't forget that we can use the confidence intervals to assess whether the mean difference with Africa is significant or not\n\n## We can also use R to report each status's average life expectancy\n\n**Find the 95% CI's for the mean life expectancy for the countries that are partly free and free**\n\n-   Use the base R `predict()` function (see Lesson 4 for more info)\n-   Requires specification of a `newdata` \"value\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata = data.frame(freedom_status = c(\"NF\", \"PF\", \"F\")) \n```\n:::\n\n\n:::::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(pred = predict(model1, \n                newdata=newdata, \n                interval=\"confidence\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 68.99387 66.66958 71.31816\n2 70.39000 68.48194 72.29806\n3 74.12893 71.68329 76.57457\n```\n\n\n:::\n:::\n\n:::\n\n:::::: {.column width=\"50%\"}\n::::: fact\n::: fact-title\nInterpretations\n:::\n\n::: fact-cont\n-   The average life expectancy for countries that are partly free is 70.39 years (95% CI: 68.48, 72.3).\n-   The average life expectancy for countries that are free is 74.13 years (95% CI: 71.68, 76.57).\n:::\n:::::\n::::::\n::::::::\n\n## Another way to look at coefficient values\n\n$$\\widehat{\\textrm{LE}} =  \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{PF}) +  \\widehat\\beta_2 \\cdot I(\\text{F})$$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# means of each level of `freedom_status`\ngapm2_ave <- gapm %>% \n  group_by(freedom_status) %>% \n  summarise(life_ave = mean(life_exp))\n\n# mean of `africa`\nmean_NF <- gapm2_ave %>% \n  filter(freedom_status == \"NF\") %>% \n  pull(life_ave)\n\n# differences in means between levels of `freedom_status` and `africa`\ngapm2_ave_diff <- gapm2_ave %>% \n  mutate(`Difference with NF` = life_ave - mean_NF) %>%\n  rename(`Freedom status` = freedom_status, \n         `Average life expectancy` = life_ave)\n\n# At the beginning of the Rmd we loaded knitr, which is where the kable command is from\n# library(knitr)\ngapm2_ave_diff %>% kable(\n  digits = 1,\n  format = \"markdown\"\n  ) \n```\n\n::: {.cell-output-display}\n\n\n|Freedom status | Average life expectancy| Difference with NF|\n|:--------------|-----------------------:|------------------:|\n|NF             |                    69.0|                0.0|\n|F              |                    74.1|                5.1|\n|PF             |                    70.4|                1.4|\n\n\n:::\n:::\n\n\n$$\\widehat{\\textrm{LE}} = 68.99 + 1.4 \\cdot I(\\text{PF}) + 5.14 \\cdot I(\\text{F})$$\n\n# 10 minute break here?\n\n# Learning Objectives\n\n1.  Understand why we need a new way to code categorical variables compared to continuous variables\n2.  Write the regression equation for a categorical variable using reference cell coding\n3.  Calculate and interpret coefficients for reference cell coding\n\n::: lob\n4.  Change the reference level in a categorical variable for reference cell coding\n:::\n\n5.  Create new variables and interpret coefficient for ordinal / scoring coding\n\n## Reference levels\n\n**Why is `NF` not one of the variables in the regression equation?**\n\n$$\\widehat{\\textrm{LE}} =  \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{PF}) +  \\widehat\\beta_2 \\cdot I(\\text{F})$$\n\n-   Categorical variables must have at least 2 levels. If they have 2 levels, we call them *binary*\n\n \n\n-   We choose one level as our **reference level** to which all other levels of the categorical variable are compared\n\n    -   The levels \\text{partly free} and \\text{free}$ are compared to the level $\\text{not free}$\n\n \n\n-   The **intercept** of the regression equation is the *mean of the outcome restricted to the reference level*\n\n    -   Recall that the intercept is the mean life expectancy of countries that are not free, which was our reference level\n\n \n\n-   **If the categorical variable has** $r$ levels, then we need $r-1$ variables/coefficients to model it!\n\n## We can change the reference level to `PF` (1/2)\n\n-   Suppose we want to compare the mean life expectancies of freedom statuses to the $\\text{partly free}$ level instead of $\\text{not free}$\n\n-   Below is the estimated regression equation for when $\\text{not free}$ is the reference level\n\n$$\\widehat{\\textrm{LE}} =  \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{PF}) +  \\widehat\\beta_2 \\cdot I(\\text{F})$$\n\n-   Update the variables to make $\\text{partly free}$ the reference level:\n\n$$\\widehat{\\textrm{LE}} =  \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{NF}) +  \\widehat\\beta_2 \\cdot I(\\text{F})$$\n\n## We can change the reference level to `PF` (2/2)\n\n-   Now update the coefficients of the regression equation using the output below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Freedom status | Average life expectancy| Difference with PF|\n|:--------------|-----------------------:|------------------:|\n|NF             |                   68.99|              -1.40|\n|F              |                   74.13|               3.74|\n|PF             |                   70.39|               0.00|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n$$\\widehat{\\textrm{LE}} = 70.39 -1.4 \\cdot I(\\text{NF}) + 3.74 \\cdot I(\\text{F})$$\n\n## R: Change reference level to `Europe`\n\n-   `freedom_status` data type was originally a `character` - check this with `str()` or `class()` or `glimpse()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(gapm$freedom_status) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Factor w/ 3 levels \"NF\",\"F\",\"PF\": 1 3 1 2 3 1 3 3 2 3 ...\n```\n\n\n:::\n:::\n\n\n-   To change the reference level, we can use `fct_relevel()` from the `forcats` package (part of `tidyverse`)\n-   *Any levels not mentioned will be left in their existing order, after the explicitly mentioned levels.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm2 = gapm %>% \n mutate(\n   freedom_status = fct_relevel(freedom_status, \"PF\")\n     )\n```\n:::\n\n\n-   Check the order:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(gapm2$freedom_status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"PF\" \"NF\" \"F\" \n```\n\n\n:::\n:::\n\n\n## R: Run model with `PF` as the reference level\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(gapm2$freedom_status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"PF\" \"NF\" \"F\" \n```\n\n\n:::\n\n```{.r .cell-code}\nmodel2 = gapm2 %>% lm(formula = life_exp ~ freedom_status)\ntidy(model2) %>% gt() %>% tab_options(table.font.size = 35) %>% \n  fmt_number(decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bnaskbgflq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bnaskbgflq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bnaskbgflq thead, #bnaskbgflq tbody, #bnaskbgflq tfoot, #bnaskbgflq tr, #bnaskbgflq td, #bnaskbgflq th {\n  border-style: none;\n}\n\n#bnaskbgflq p {\n  margin: 0;\n  padding: 0;\n}\n\n#bnaskbgflq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bnaskbgflq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bnaskbgflq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bnaskbgflq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bnaskbgflq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bnaskbgflq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bnaskbgflq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bnaskbgflq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bnaskbgflq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bnaskbgflq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bnaskbgflq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bnaskbgflq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bnaskbgflq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bnaskbgflq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bnaskbgflq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnaskbgflq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bnaskbgflq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bnaskbgflq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bnaskbgflq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnaskbgflq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bnaskbgflq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnaskbgflq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bnaskbgflq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnaskbgflq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bnaskbgflq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnaskbgflq .gt_left {\n  text-align: left;\n}\n\n#bnaskbgflq .gt_center {\n  text-align: center;\n}\n\n#bnaskbgflq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bnaskbgflq .gt_font_normal {\n  font-weight: normal;\n}\n\n#bnaskbgflq .gt_font_bold {\n  font-weight: bold;\n}\n\n#bnaskbgflq .gt_font_italic {\n  font-style: italic;\n}\n\n#bnaskbgflq .gt_super {\n  font-size: 65%;\n}\n\n#bnaskbgflq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bnaskbgflq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bnaskbgflq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bnaskbgflq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bnaskbgflq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bnaskbgflq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bnaskbgflq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bnaskbgflq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bnaskbgflq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">70.39</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.96</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">73.17</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">freedom_statusNF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−1.40</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.52</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−0.92</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.36</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">freedom_statusF</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">3.74</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.56</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.39</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.02</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\\begin{aligned}\\widehat{\\textrm{LE}} &=  \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{NF}) +  \\widehat\\beta_2 \\cdot I(\\text{F}) + \\\\ \\widehat{\\textrm{LE}} &= 70.39 -1.4 \\cdot I(\\text{NF}) + 3.74 \\cdot I(\\text{F}) \\end{aligned}$$\n\n## Fitted values & residuals\n\n::::: columns\n::: {.column width=\"40%\"}\nSimilar to as before:\n\n-   **Observed values** $Y$ are the values in the dataset\n\n-   **Fitted values** $\\widehat{Y}$ are the values that ~~fall on the best-fit line for a specific value of x~~ are the *means of the outcome stratified by the categorical predictor's levels*\n\n-   **Residuals** ($\\widehat{\\epsilon} = Y - \\widehat{Y}$) are the differences between the two\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n:::::\n\n## Fitted values are the same as the means\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_aug <- augment(model1)\n\nggplot(m1_aug, aes(x = freedom_status, y = .fitted)) + geom_point() +\n  theme(axis.text = element_text(size = 22), axis.title = element_text(size = 22))\n```\n\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n## Residual plots (now the spread within each status)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(m1_aug, aes(x=.resid)) + geom_histogram() + \n  theme(axis.text = element_text(size = 22), title = element_text(size = 22))\n```\n\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-23-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n## Poll Everywhere Question 3\n\n# Learning Objectives\n\n1.  Understand why we need a new way to code categorical variables compared to continuous variables\n2.  Write the regression equation for a categorical variable using reference cell coding\n3.  Calculate and interpret coefficients for reference cell coding\n4.  Change the reference level in a categorical variable for reference cell coding\n\n::: lob\n5.  Create new variables and interpret coefficient for ordinal / scoring coding\n:::\n\n## Let's look at life expectancy vs. four income levels\n\n-   [Gapminder discusses individual income levels](https://www.gapminder.org/fw/income-levels/)\n\n \n\n-   **Income levels for a country** is based on average GDP per capita, and grouped into:\n\n    -   Low income\n\n    -   Lower middle income\n\n    -   Upper middle income\n\n    -   High income\n\n## Visualizing the ordinal variable, income levels\n\n::::: columns\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-24-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\nA few changes needed:\n\n-   Put the income levels in order\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm2 = gapm2 %>%\n mutate(income_level_4 = fct_relevel(\n          income_level_4, \n            \"Low income\", \n            \"Lower middle income\", \n            \"Upper middle income\", \n            \"High income\"\n ))\n```\n:::\n\n\n-   Make the income levels readable\n\n    -   [How to Rotate Axis Labels in ggplot2?](https://www.r-bloggers.com/2021/09/how-to-rotate-axis-labels-in-ggplot2/)\n:::\n:::::\n\n## Much better: Visualizing the ordinal variable, income levels {.smaller}\n\n::::: columns\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(gapm2, aes(x = income_level_4, y = life_exp)) +\n  geom_jitter(size = 1, alpha = .6, width = 0.2) +\n  stat_summary(fun = mean, geom = \"point\", size = 8, shape = 18) +\n  labs(x = \"Income levels\", \n       y = \"Country life expectancy (years)\",\n       title = \"Life expectancy vs. income levels\",\n       caption = \"Diamonds = Income level averages\") +\n  theme(axis.title = element_text(size = 20), \n        axis.text = element_text(size = 20), \n        title = element_text(size = 20), \n        axis.text.x=element_text(angle = 20, vjust = 1, hjust=1))\n```\n:::\n\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-27-1.png){fig-align='center' width=672}\n:::\n:::\n\n:::\n:::::\n\n## How can we code this variable?\n\nWe have two options:\n\n::::::::::: columns\n:::::: column\n::::: definition\n::: def-title\nTreat the levels as nominal, and use reference cell coding\n:::\n\n::: def-cont\n-   Like we did with freedom status\n\n-   This option will not break the linearity assumption\n\n-   For $g$ categories of the variable, we will have $g-1$ coefficients to estimate\n:::\n:::::\n::::::\n\n:::::: column\n::::: proof1\n::: proof-title\nUse the ordinal values to score the levels and treat as a numerical variable\n:::\n\n::: proof-cont\n-   Even if a variable is inherently ordered, we need to check that linearity holds if categories are represented as numbers\n\n-   This way of coding preserves more power in the model (less coefficients to estimate means more power)\n\n-   Only one coefficient to estimate\n:::\n:::::\n::::::\n:::::::::::\n\n## Some important considerations when scoring ordinal variables\n\n-   Even if a variable is inherently ordered, we need to check that linearity holds if categories are represented as numbers (more in next lessons)\n    -   Linearity is an assumption of linear regression: that the relationship between X and Y is linear\n\n \n\n-   Assumes differences between adjacent groups are equal\n\n    -   Income levels are pre-set groups by Gapminder\n    -   Might be hard to interpret \"every 1-level increase in income level\"\n\n \n\n-   Is the variable part of the main relationship that you are investigating? (even if linearity holds)\n\n    -   If yes, consider leaving as reference cell coding unless the interpretation makes sense\n\n    -   If no, and just needed as an adjustment in your model, then power benefit of scoring might be worth it!\n\n## Check that linearity holds for income levels\n\n::::: columns\n::: {.column width=\"40%\"}\n-   Using visual assessment, linearity holds for our income levels (more in next lessons)\n\n-   We can use the ordinal encoding for income levels\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-28-1.png){fig-align='center' width=720}\n:::\n:::\n\n:::\n:::::\n\n## Poll Everywhere Question 4\n\n## Ordinal coding / Scoring\n\n::: columns\n::: {.column width=\"40%\"}\n\n-   Map each income level to a number\n\n-   Usually start at 1\n\n| Income Level        | Score |\n|---------------------|-------|\n| Low income          | 1     |\n| Lower middle income | 2     |\n| Upper middle income | 3     |\n| High income         | 4     |\n\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm2 = gapm2 %>%\n  mutate(income_num = case_when(\n    income_level_4 == \"Low income\" ~ 1,\n    income_level_4 == \"Lower middle income\" ~ 2,\n    income_level_4 == \"Upper middle income\" ~ 3,\n    income_level_4 == \"High income\" ~ 4\n  ))\ngapm2 %>% select(income_level_4, income_num) %>% \n  head(6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  income_level_4      income_num\n  <fct>                    <dbl>\n1 Low income                   1\n2 Upper middle income          3\n3 High income                  4\n4 Upper middle income          3\n5 Upper middle income          3\n6 Upper middle income          3\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Run the model with the scored income\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_inc2 = gapm2 %>% lm(formula = life_exp ~ income_num)\ntidy(mod_inc2) %>% gt() %>% tab_options(table.font.size = 37) %>%\n  fmt_number(decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"juzrcmccyf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#juzrcmccyf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#juzrcmccyf thead, #juzrcmccyf tbody, #juzrcmccyf tfoot, #juzrcmccyf tr, #juzrcmccyf td, #juzrcmccyf th {\n  border-style: none;\n}\n\n#juzrcmccyf p {\n  margin: 0;\n  padding: 0;\n}\n\n#juzrcmccyf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 37px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#juzrcmccyf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#juzrcmccyf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#juzrcmccyf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#juzrcmccyf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#juzrcmccyf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#juzrcmccyf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#juzrcmccyf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#juzrcmccyf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#juzrcmccyf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#juzrcmccyf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#juzrcmccyf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#juzrcmccyf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#juzrcmccyf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#juzrcmccyf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#juzrcmccyf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#juzrcmccyf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#juzrcmccyf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#juzrcmccyf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#juzrcmccyf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#juzrcmccyf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#juzrcmccyf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#juzrcmccyf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#juzrcmccyf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#juzrcmccyf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#juzrcmccyf .gt_left {\n  text-align: left;\n}\n\n#juzrcmccyf .gt_center {\n  text-align: center;\n}\n\n#juzrcmccyf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#juzrcmccyf .gt_font_normal {\n  font-weight: normal;\n}\n\n#juzrcmccyf .gt_font_bold {\n  font-weight: bold;\n}\n\n#juzrcmccyf .gt_font_italic {\n  font-style: italic;\n}\n\n#juzrcmccyf .gt_super {\n  font-size: 65%;\n}\n\n#juzrcmccyf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#juzrcmccyf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#juzrcmccyf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#juzrcmccyf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#juzrcmccyf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#juzrcmccyf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#juzrcmccyf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#juzrcmccyf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#juzrcmccyf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">58.51</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.38</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">42.47</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_num</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">4.90</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.51</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">9.66</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\\begin{aligned}\n\\widehat{\\textrm{LE}} &=  \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot \\text{Income level} \\\\\n\\widehat{\\textrm{LE}} &=  58.51 + 4.9 \\cdot \\text{Income level}\n\\end{aligned}$$\n\n-   Keep in mind: We cannot calculate the expected outcome outside of the scoring values\n\n    -   For example, we cannot find the mean life expectancy for an income level of 1.5\n\n## Interpreting the model\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"woxsowznhm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#woxsowznhm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#woxsowznhm thead, #woxsowznhm tbody, #woxsowznhm tfoot, #woxsowznhm tr, #woxsowznhm td, #woxsowznhm th {\n  border-style: none;\n}\n\n#woxsowznhm p {\n  margin: 0;\n  padding: 0;\n}\n\n#woxsowznhm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 37px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#woxsowznhm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#woxsowznhm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#woxsowznhm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#woxsowznhm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#woxsowznhm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#woxsowznhm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#woxsowznhm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#woxsowznhm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#woxsowznhm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#woxsowznhm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#woxsowznhm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#woxsowznhm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#woxsowznhm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#woxsowznhm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#woxsowznhm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#woxsowznhm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#woxsowznhm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#woxsowznhm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#woxsowznhm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#woxsowznhm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#woxsowznhm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#woxsowznhm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#woxsowznhm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#woxsowznhm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#woxsowznhm .gt_left {\n  text-align: left;\n}\n\n#woxsowznhm .gt_center {\n  text-align: center;\n}\n\n#woxsowznhm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#woxsowznhm .gt_font_normal {\n  font-weight: normal;\n}\n\n#woxsowznhm .gt_font_bold {\n  font-weight: bold;\n}\n\n#woxsowznhm .gt_font_italic {\n  font-style: italic;\n}\n\n#woxsowznhm .gt_super {\n  font-size: 65%;\n}\n\n#woxsowznhm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#woxsowznhm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#woxsowznhm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#woxsowznhm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#woxsowznhm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#woxsowznhm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#woxsowznhm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#woxsowznhm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#woxsowznhm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">58.51</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.38</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">42.47</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">55.78</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">61.24</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_num</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">4.90</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.51</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">9.66</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">3.90</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">5.91</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\\widehat{\\textrm{LE}} =  54.01 + 6.25 \\cdot \\text{Income level}$$\n\n-   **Interpreting the intercept:** At an income level of 0, mean life expectancy is 54.01 (95% CI: 51.92, 56.10).\n\n    -   Note: this does not make sense because there is no income level of 0!\n\n-   **Interpreting the coefficient for income:** For every 1-level increase in income level, mean life expectancy increases 4.9 years (95% CI: 3.9, 5.91).\n\n## What if life expectancy vs. income level looked like this?\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05_Cat_covariates_files/figure-revealjs/unnamed-chunk-33-1.png){fig-align='center' width=720}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n-   No longer maintaining the linearity assumption\n-   Need to use reference cell coding\n\n \n\n-   We would fit the following model: $$\\begin{aligned}\n    \\textrm{LE} = & \\beta_0 + \\beta_1 \\cdot I(\\text{Lower middle income}) + \\\\ & \\beta_2 \\cdot I(\\text{Upper middle income}) + \\\\ & \\beta_3 \\cdot I(\\text{High income}) + \\epsilon\n    \\end{aligned}$$\n:::\n:::::\n\n## If time...\n\n[Let's walk through categorical variables that have multiple selections](https://weallcount.com/2022/10/27/4-approaches-to-multiple-race-questions/)\n\n-   So each group is not mutually exclusive\n\n-   We could make an indicator for each category, but individuals could be a part of multiple categories\n\n \n\n-   Also, thinking about income levels - can we combine two groups to make one??\n",
    "supporting": [
      "05_Cat_covariates_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}